# Setup

In [1]:
# set parameters
import numpy as np
import pandas as pd
pd.options.mode.chained_assignment = None  # default='warn'
import plotly.graph_objects as go
import scipy
import sys
sys.path.append('../../assets/python/')
import dmg5e
import estats5e
import tfb

METADATA = {'Contributor': 'T. Dunn'}
SAVEFIGS = False

COLORS = [
    '#1f77b4',  # muted blue
    '#ff7f0e',  # safety orange
    '#2ca02c',  # cooked asparagus green
    '#d62728',  # brick red
    '#9467bd',  # muted purple
    '#8c564b',  # chestnut brown
    '#e377c2',  # raspberry yogurt pink
    '#7f7f7f',  # middle gray
    '#bcbd22',  # curry yellow-green
    '#17becf'   # blue-teal
]

ABILITY_MOD_COLUMNS = ['Str Mod','Dex Mod','Con Mod','Int Mod','Wis Mod','Cha Mod',]
SAVE_BONUS_COLUMNS = ['Str Save','Dex Save','Con Save','Int Save','Wis Save','Cha Save',]
CONDITION_COLUMNS = ['Blinded','Charmed','Deafened','Exhaustion','Frightened','Grappled','Incapacitated',
    'Invisible','Paralyzed','Petrified','Poisoned','Prone','Restrained','Stunned','Unconscious',]
DAMAGE_COLUMNS = ['Bludgeoning','Piercing','Slashing','Acid','Cold','Fire','Force','Lightning','Necrotic','Poison','Psychic','Radiant','Thunder',]

In [2]:
# useful functions
def jitter(vals, sigma):
    if type(vals) is list:
        return np.array(vals) + np.random.normal(0, sigma, len(vals))
    else:
        return vals + np.random.normal(0, sigma, len(vals))

TFB_MONSTER_DEFAULTS = {
    'CR': [0, 1/8, 1/4, 1/2, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 
        14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30],
    'XP': [2, 15, 38, 70, 152, 330, 583, 980, 1406, 2104, 2715, 3640, 4593, 
        5899, 7006, 8666, 10189, 12361, 14080, 16748, 19016, 21808, 24575, 29344, 
        35879, 44877, 55101, 66811, 78655, 92811, 108626, 126102, 143173, 165404],
    'PB': [2, 2, 2, 2, 2, 2, 2, 2, 3, 3, 3, 3, 4, 4, 4, 4, 5, 5, 
        5, 5, 6, 6, 6, 6, 7, 7, 7, 7, 8, 8, 8, 8, 9, 9],
    'AC': [13, 13, 13, 13, 14, 14, 15, 15, 15, 16, 16, 16, 17, 17, 17, 17, 18, 18, 
        18, 19, 19, 19, 19, 20, 20, 20, 21, 21, 21, 21, 22, 22, 22, 23],
    'SB': [0, 0, 0, 0, 0, 1, 1, 2, 2, 3, 3, 4, 4, 5, 5, 6, 6, 7, 7, 7, 
        8, 8, 9, 9, 10, 10, 11, 11, 12, 12, 13, 13, 14, 14],
    'HP': [4.0, 9.5, 15.0, 21.0, 32.0, 49.0, 66.0, 83.0, 100.0, 117.0, 134.0, 
        151.0, 168.0, 184.5, 201.0, 218.0, 235.0, 252.0, 269.0, 286.0, 303.0, 320.0, 
        337.0, 361.5, 402.0, 450.5, 499.0, 547.5, 596.0, 644.5, 692.5, 741.0, 789.5, 838.0],
    'AB': [5, 5, 5, 5, 5, 5, 5, 6, 6, 7, 7, 8, 8, 9, 9, 10, 10, 11, 11, 
        12, 12, 13, 13, 14, 14, 15, 15, 16, 16, 17, 17, 18, 18, 19],
    'DC': [13, 13, 13, 13, 13, 13, 13, 14, 14, 15, 15, 16, 16, 17, 17, 18, 
        18, 19, 19, 20, 20, 21, 21, 22, 22, 23, 23, 24, 24, 25, 25, 26, 26, 27],
    'DPR': [1.5, 5.0, 8.0, 10.5, 14.5, 20.0, 25.5, 31.5, 37.5, 43.5, 49.0, 54.5, 
        60.5, 66.5, 72.5, 78.0, 83.5, 89.5, 95.5, 101.5, 107.0, 112.5, 118.5, 126.0, 
        136.5, 148.0, 159.5, 171.5, 183.0, 194.5, 206.5, 218.5, 230.0, 241.5],
}

def _find_nearest_loc(array, value):
    array = np.asarray(array)
    idx = (np.abs(array - value)).argmin()
    return idx

def monster_default_stats(cr, **kwargs):
    """Returns default monster stats.
    cr -- challenge rating
    """
    mon_stats = kwargs.get('monster_stats', TFB_MONSTER_DEFAULTS)
    id = _find_nearest_loc(mon_stats['CR'], cr)
    return {
        'CR': mon_stats['CR'][id],
        'XP': mon_stats['XP'][id],
        'PB': mon_stats['PB'][id],
        'AC': mon_stats['AC'][id],
        'SB': mon_stats['SB'][id],
        'HP': mon_stats['HP'][id],
        'AB': mon_stats['AB'][id],
        'DC': mon_stats['DC'][id],
        'DPR': mon_stats['DPR'][id],
    }

def monster_defensive_challenge_rating(hp, ac, **kwargs):
    """Returns offensive challenge rating
    hp -- average hit points
    ac -- armor class
    """
    mon_stats = kwargs.get('monster_stats', TFB_MONSTER_DEFAULTS)
    id = _find_nearest_loc(mon_stats['HP'], hp)
    if ac:
        ac_delta = ac - mon_stats['AC'][id]
        id = int(max(0, min(33, id + np.fix(0.5*ac_delta))))
    return mon_stats['CR'][id]

def monster_offensive_challenge_rating(dpr, ab, **kwargs):
    """Returns offensive challenge rating
    dpr -- average damage per round
    ab -- attack bonus
    """
    mon_stats = kwargs.get('monster_stats', TFB_MONSTER_DEFAULTS)
    id = _find_nearest_loc(mon_stats['DPR'], dpr)
    if ab:
        ab_delta = ab - mon_stats['AB'][id]
        id = int(max(0, min(33, id + np.fix(0.5*ab_delta))))
    return mon_stats['CR'][id]

def count_save_proficiencies(row):
    n = 0
    for ab in ['Str','Dex','Con','Int','Wis','Cha']:
        if row[f'{ab} Save'] > row[f'{ab} Mod']:
            n += 1
    return n


def list_immunities(row):
    return [dt for dt in DAMAGE_COLUMNS if (row[dt] < 0.5)]

def list_resistances(row):
    return [dt for dt in DAMAGE_COLUMNS if (row[dt] >= 0.5) and (row[dt] < 1)]

def count_damage_immunities(row):
    return len(list_immunities(row))

def count_damage_resistances(row):
    return len(list_resistances(row))

def average_ability_modifier(row):
    v  = row[f'Str Mod'] + row[f'Dex Mod'] + row[f'Con Mod'] 
    v += row[f'Int Mod'] + row[f'Wis Mod'] + row[f'Cha Mod']
    return v/6

def initiative_adjustment(row):
    return 1 + (0.5/2.5)*(row['Initiative']/20)

def fit_to_linear(x, y):
    coefs = np.polyfit(x, y, 1)
    poly = np.poly1d(coefs)
    return poly(np.linspace(1,30,30))

def legendary_resistance_hp_value(cr):
    if cr <= 4: return 10
    if cr <= 10: return 20
    return 30

def unadjust_hit_points(row):
    hp = row['adj HP']
    if row['Book'] not in ['MM (2024)']: return hp

    if row['Legendary'] in ['L','LL']:
        lr_hp = legendary_resistance_hp_value(row['CR'])
        lr_count = 3
        if row['CR'] >= 20: lr_count = 4
        if row['CR'] >= 30: lr_count = 6
        if row['Legendary'] == 'LL': lr_count += 1
        hp -= lr_hp*lr_count

    return hp

def mitigation(row):
    if row['Immunities'] >= 3:
        return 'I3+'
    
    if (row['Bludgeoning'] < 1) and (row['Piercing'] < 1) and (row['Slashing'] < 1):
        return 'BPS'
    
    if row['Resistances'] >= 3:
        return 'R3+'
    
    return 'none'

def mitigation_multiplier(row):
    match row['Mitigation']:
        case 'I3+':
            if row['CR'] <= 4:
                return 2.0
            elif row['CR'] <= 10:
                return 2.0
            elif row['CR'] <= 16:
                return 1.5
            else:
                return 1.25
        case 'R3+':
            if row['Book'] not in ['MM (2024)']:
                if row['CR'] <= 4:
                    return 2.0
                elif row['CR'] <= 10:
                    return 1.5
                elif row['CR'] <= 16:
                    return 1.25
                else:
                    return 1.0
            else:
                return 1.0
        case 'BPS':
            if row['CR'] <= 4:
                return 2.0
            elif row['CR'] <= 10:
                return 1.5
            elif row['CR'] <= 16:
                return 1.25
            else:
                return 1.0
        case _:
            return 1.0

In [3]:
dfT = pd.DataFrame(TFB_MONSTER_DEFAULTS)
dfT['adj AC'] = dfT['AC']
dfT['adj SB'] = dfT['SB']
dfT['adj HP'] = dfT['HP']
dfT['adj AB'] = dfT['AB']
dfT['adj DC'] = dfT['DC']
dfT['adj DPR'] = dfT['DPR']
dfT['HP Multiplier'] = dfT['adj HP']/dfT['HP']
dfT['eAC'] = (dfT['AC'] + dfT['SB'] + 14)/2
dfT['eHP']  = dfT.apply(lambda row: estats5e.effHP(row['adj HP'], row['eAC']), axis=1)
dfT['eDPR'] = dfT.apply(lambda row: estats5e.effDPR(row['adj DPR'], row['adj AB']), axis=1)
dfT['eXP']  = dfT.apply(lambda row: estats5e.effXP(row['adj HP'], row['eAC'], row['adj DPR'], row['adj AB']), axis=1)
dfT['adj AC Delta'] = dfT['adj AC'] - dfT['adj AC']
dfT['adj SB Delta'] = dfT['adj SB'] - dfT['adj SB']
dfT['adj AB Delta'] = dfT['adj AB'] - dfT['adj AB']
dfT['DPR Ratio']  = dfT['DPR']/dfT['DPR']
dfT['HP Ratio']  = dfT['HP']/dfT['HP']
dfT['adj HP Ratio']  = dfT['adj HP']/dfT['adj HP']
dfT['adj DPR Ratio']  = dfT['adj DPR']/dfT['adj DPR']
dfT['eHP Ratio']  = dfT['eHP']/dfT['eHP']
dfT['eDPR Ratio']  = dfT['eDPR']/dfT['eDPR']
dfT['eXP Ratio']  = dfT['eXP']/dfT['XP']

In [4]:
name_decoder = {
    # 2014 name --> 2025 equivalent
    'Aarakocra': 'Aarakocra Skirmisher',
    'Acolyte': 'Priest Acolyte',
    'Adult Blue Dracolich': 'Dracolich',
    'Androsphinx': 'Sphinx of Valor',
    'Azer': 'Azer Sentinel',
    'Bugbear': 'Bugbear Warrior',
    'Bullywug': 'Bullywug Warrior',
    'Centaur': 'Centaur Trooper',
    'Cult Fanatic': 'Cultist Fanatic',
    'Cyclops': 'Cyclops Sentry',
    'Deep Gnome': 'Scout',
    'Drow': 'Priest Acolyte',
    'Drow Elite Warrior': 'Gladiator',
    'Drow Mage': 'Bandit Deceiver',
    'Drow Priestess of Lolth': 'Fiend Cultist',
    'Duergar': 'Spy',
    'Duodrone': 'Modron Duodrone',
    'Faerie Dragon (Older)': 'Faerie Dragon Adult',
    'Faerie Dragon (Younger)': 'Faerie Dragon Youth',
    'Fire Snake': 'Salamander Fire Snake',
    'Flying Sword': 'Animated Flying Sword',
    'Gas Spore': 'Gas Spore Fungus',
    'Giant Poisonous Snake': 'Giant Venomous Snake',
    'Gnoll': 'Gnoll Warrior',
    'Goblin': 'Goblin Warrior',
    'Grick Alpha': 'Grick Ancient',
    'Gynosphinx': 'Sphinx of Lore',
    'Half-Ogre': 'Ogrillon Ogre',
    'Half-Red Dragon Veteran': 'Half-Dragon',
    'Hobgoblin': 'Hobgoblin Warrior',
    'Kobold': 'Kobold Warrior',
    'Lizardfolk': 'Scout',
    'Lizardfolk Shaman': 'Lizardfolk Geomancer',
    'Lizard King/Queen': 'Lizardfolk Sovereign',
    'Merfolk': 'Merfolk Skirmisher',
    'Minotaur': 'Minotaur of Baphomet',
    'Monodrone': 'Modron Monodrone',
    'Orc': 'Tough',
    'Orc Eye of Gruumsh': 'Cultist Fanatic',
    'Orc War Chief': 'Tough Boss',
    'Orog': 'Berserker',
    'Pentadrone': 'Modron Pentadrone',
    'Poisonous Snake': 'Venomous Snake',
    'Quadrone': 'Modron Quadrone',
    'Quaggoth Spore Servant': 'Myconid Spore Servant',
    'Quipper': 'Piranha',
    'Rug of Smothering': 'Animated Rug of Smothering',
    'Sahuagin': 'Sahuagin Warrior',
    'Sahuagin Priestess': 'Sahuagin Priest',
    'Shrieker': 'Shrieker Fungus',
    'Swarm of Poisonous Snakes': 'Swarm of Venomous Snakes',
    'Swarm of Quippers': 'Swarm of Piranhas',
    'Thri-kreen': 'Thri-kreen Marauder',
    'Thug': 'Tough',
    'Tribal Warrior': 'Warrior Infantry',
    'Tridrone': 'Modron Tridrone',
    'Veteran': 'Warrior Veteran',
    "Will-o'-Wisp": "Will-o’-Wisp",
    'Young Red Shadow Dragon': 'Shadow Dragon',
    'Yuan-ti Pureblood': 'Yuan-ti Infiltrator',
}

In [5]:
# load monster data
df1 = pd.read_csv('./monsters-2014.csv')
df2 = pd.read_csv('./monsters-2024.csv')
df0 = pd.concat([df1, df2])

#df0['adj HP'] = df0.apply(lambda row: unadjust_hit_points(row), axis=1)

df0['Type'] = df0['Type'].str.title()
df0['Size'] = df0['Size'].str.title()
df0 = df0.astype({'Book': 'category', 'Size': 'category', 'Type': 'category'})

df0['Size'] = df0['Size'].cat.set_categories(['Tiny','Small','Medium','Large','Huge','Gargantuan'], ordered=True)

df0['Str Save Prof'] = df0.apply(lambda row: int(row['Str Save'] > row['Str Mod']), axis=1)
df0['Dex Save Prof'] = df0.apply(lambda row: int(row['Dex Save'] > row['Dex Mod']), axis=1)
df0['Con Save Prof'] = df0.apply(lambda row: int(row['Con Save'] > row['Con Mod']), axis=1)
df0['Int Save Prof'] = df0.apply(lambda row: int(row['Int Save'] > row['Int Mod']), axis=1)
df0['Wis Save Prof'] = df0.apply(lambda row: int(row['Wis Save'] > row['Wis Mod']), axis=1)
df0['Cha Save Prof'] = df0.apply(lambda row: int(row['Cha Save'] > row['Cha Mod']), axis=1)

df0['Save Proficiencies'] = df0.apply(lambda row: count_save_proficiencies(row), axis=1)

df0['DC'] = df0['Save DC']
df0['adj DC'] = df0['DC']
df0['AM'] = df0.apply(lambda row: average_ability_modifier(row), axis=1)
#df0['HP multiplier'] = df0['adj HP']/df0['HP']

df0['eAC']  = (df0['adj AC'] + df0['adj SB'] + 14)/2
df0['eHP']  = df0.apply(lambda row: estats5e.effHP(row['adj HP'], row['eAC']), axis=1)
df0['eDPR'] = df0.apply(lambda row: estats5e.effDPR(row['adj DPR'], row['adj AB']), axis=1)
df0['eXP']  = df0.apply(lambda row: estats5e.effXP(row['adj HP'], row['eAC'], row['adj DPR'], row['adj AB']), axis=1)
#df0['eXP']  = df0.apply(lambda row: estats5e.effXP(row['adj HP'], row['eAC'], row['adj DPR'], row['adj AB'])*initiative_adjustment(row), axis=1)
df0['eCR']  = df0.apply(lambda row: np.round(np.interp(row['eXP'], dfT['eXP'],  dfT['CR'], left=0, right=30), 0), axis=1)
df0['eCR Delta']  = df0['eCR'] - df0['CR']


df0['Immunities'] = df0.apply(lambda row: count_damage_immunities(row), axis=1)
df0['Resistances'] = df0.apply(lambda row: count_damage_resistances(row), axis=1)
df0['Mitigation'] = df0.apply(lambda row: mitigation(row), axis=1)
df0['Mitigation Multiplier'] = df0.apply(lambda row: mitigation_multiplier(row), axis=1)

#df0['XP'] = df0.apply(lambda row: dmg5e.monster_default_stats(row['CR'])['XP'], axis=1)
df0['XP'] = df0.apply(lambda row: monster_default_stats(row['CR'])['XP'], axis=1)
df0['Monster Alias'] = df0.apply(lambda row: name_decoder.get(row['Monster'], row['Monster']), axis=1)

dfB = dfT.set_index('CR')

df0['D-CR Base'] = df0.apply(lambda row: monster_defensive_challenge_rating(row['adj HP'], None), axis=1)
df0['D-CR'] = df0.apply(lambda row: monster_defensive_challenge_rating(row['adj HP'], row['eAC']), axis=1)
df0['D-CR AC Delta'] = df0.apply(lambda row: row['eAC'] - dfB.loc[row['D-CR Base']]['AC'], axis=1)

df0['O-CR Base'] = df0.apply(lambda row: monster_offensive_challenge_rating(row['adj DPR'], None), axis=1)
df0['O-CR'] = df0.apply(lambda row: monster_offensive_challenge_rating(row['adj DPR'], row['adj AB']), axis=1)
df0['O-CR AB Delta'] = df0.apply(lambda row: row['adj AB'] - dfB.loc[row['O-CR Base']]['AB'], axis=1)

df0['adj AB Delta'] = df0.apply(lambda row: row['adj AB'] - dfB.loc[row['CR']]['adj AB'], axis=1)
df0['adj AC Delta'] = df0.apply(lambda row: row['adj AC'] - dfB.loc[row['CR']]['adj AC'], axis=1)
df0['adj SB Delta'] = df0.apply(lambda row: row['adj SB'] - dfB.loc[row['CR']]['adj SB'], axis=1)
df0['eAC Delta'] = (df0['adj AC Delta'] + df0['adj SB Delta'])/2
df0['DPR Ratio'] = df0.apply(lambda row: row['DPR']/dfB.loc[row['CR']]['DPR'], axis=1)
df0['HP Ratio'] = df0.apply(lambda row: row['HP']/dfB.loc[row['CR']]['HP'], axis=1)
df0['adj HP Ratio'] = df0.apply(lambda row: row['adj HP']/dfB.loc[row['CR']]['adj HP'], axis=1)
df0['adj DPR Ratio'] = df0.apply(lambda row: row['adj DPR']/dfB.loc[row['CR']]['adj DPR'], axis=1)
df0['eHP Ratio'] = df0.apply(lambda row: row['eHP']/dfB.loc[row['CR']]['eHP'], axis=1)
df0['eDPR Ratio'] = df0.apply(lambda row: row['eDPR']/dfB.loc[row['CR']]['eDPR'], axis=1)
df0['eXP Ratio'] = df0.apply(lambda row: row['eXP']/dfB.loc[row['CR']]['eXP'], axis=1)
#df0 = df0[df0['CR'].between(1,30)]
df0

,Monster,Book,Page,Type,Size,Category,Legendary,CR,PB,XP,...,adj AC Delta,adj SB Delta,eAC Delta,DPR Ratio,HP Ratio,adj HP Ratio,adj DPR Ratio,eHP Ratio,eDPR Ratio,eXP Ratio
0,Aarakocra,MM (2014),12.0,Humanoid,Medium,generic,N,0.250,2,38,...,-1.0,0.5,-0.25,0.687500,0.900000,0.900000,0.833333,0.884483,0.777778,0.693182
1,Aarakocra Simulacrum,SKT,188.0,Humanoid,Medium,generic,N,0.125,2,15,...,-1.0,0.5,-0.25,1.100000,0.631579,0.631579,1.333333,0.620690,1.244444,0.778309
2,Aartuk Elder,SAiS:BAM,8.0,Plant,Large,generic,N,3.000,2,583,...,1.0,0.7,0.85,0.862745,1.136364,1.136364,0.862745,1.196733,0.920261,1.081155
3,Aartuk Starhorror,SAiS:BAM,9.0,Plant,Medium,generic,N,2.000,2,330,...,0.0,0.2,0.10,0.800000,1.061224,1.061224,0.800000,1.068071,0.693333,0.756805
4,Aartuk Weedling,SAiS:BAM,9.0,Plant,Medium,generic,N,2.000,2,330,...,1.0,-0.2,0.40,0.800000,0.785714,0.785714,0.800000,0.805991,0.746667,0.607020
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
535,Yuan-ti Infiltrator,MM (2024),342.0,Monstrosity,Medium,generic,N,1.000,2,152,...,-3.0,4.8,0.90,0.620690,1.265625,1.265625,0.620690,1.341563,0.579310,0.780939
536,Yuan-ti Malison (Type 1),MM (2024),343.0,Monstrosity,Medium,generic,N,3.000,2,583,...,-3.0,5.0,1.00,0.980392,1.000000,1.000000,0.980392,1.062500,0.980392,1.034858
537,Yuan-ti Malison (Type 2),MM (2024),343.0,Monstrosity,Medium,generic,N,3.000,2,583,...,-3.0,5.0,1.00,1.137255,1.000000,1.000000,1.137255,1.062500,1.137255,1.200436
538,Yuan-ti Malison (Type 3),MM (2024),344.0,Monstrosity,Medium,generic,N,3.000,2,583,...,-3.0,5.0,1.00,0.941176,1.000000,1.000000,0.941176,1.062500,0.941176,0.993464
539,Zombie,MM (2024),346.0,Undead,Medium,generic,N,0.250,2,38,...,-5.0,-0.8,-2.90,0.687500,1.000000,1.466667,0.687500,1.173333,0.595833,0.708889

# Figures

In [283]:
# Fig. 1: Attack bonus vs challenge rating
column = 'adj AB'

groups = [
    {
        'name': 'MM 2014',
        'Book': 'MM (2014)',
        'Legendary': ['N','L','LL'],
        'color': COLORS[0],
        'line_color': COLORS[0],
        'symbol': 'circle',
    },
    {
        'name': 'MM 2024',
        'Book': 'MM (2024)',
        'Legendary': ['N','L','LL'],
        'color': COLORS[1],
        'line_color': COLORS[1],
        'symbol': 'circle',
    },
]

# create figure
fig = go.Figure(
    layout=go.Layout(
        template=tfb.FIG_TEMPLATE,
        margin=dict(l=70, r=25, b=55, t=20, pad=4),
        xaxis=dict(
            title_text='challenge rating',
            range=[0,31],
            tick0=0, dtick=5,
            minor=dict(tick0=0, dtick=1),
        ),
        yaxis=dict(
            title_text=f'attack bonus',
            #range=[0,3],
            tick0=0, dtick=2,
            minor=dict(tick0=0, dtick=1),
        ),
        legend=dict(
            xanchor='left', yanchor='top',
            x=0.00, y=1.00,
            orientation='v',
            tracegroupgap=0,
        )
    )
)

# plot monster data
for group in groups:
    name = group['name']
    book = group['Book']
    legendary = group['Legendary']
    df1 = df0[df0['Book'].isin([book]) & df0['Legendary'].isin(legendary)]
    dfG = df1[['CR',column]].groupby(['CR']).mean().reset_index()
    fig.add_trace(go.Scatter(
        x=dfG['CR'], 
        y=dfG[column],
        mode='markers+lines', 
        name=name,
        marker_color=group['color'],
        marker_symbol=group['symbol'],
        line_color=group['line_color'],
        hovertemplate = f'<b>{name}</b><br>'
            + 'CR %{x:.0f}<br>'
            + 'AB %{y:.1f}'
            + '<extra></extra>'
    ))

fig.add_trace(go.Scatter(
    x=dfT['CR'], 
    y=dfT[column],
    mode='lines', 
    name=f'baseline',
    showlegend=False,
    line_color='black',
    line_dash='dash',
    hoverinfo='skip',
))

# show figure
fig.update_layout(width=600, height=450)
fig.show(config=tfb.FIG_CONFIG)

# save figures
if SAVEFIGS:
    fig.update_layout(autosize=True, width=None, height=None)
    tfb.save_fig_html(fig, format='large', name=f'./fig-ab-vs-cr-large')
    tfb.save_fig_html(fig, format='small', name=f'./fig-ab-vs-cr-small')

In [284]:
# Fig. 2: Save DC vs challenge rating
column = 'DC'
groups = [
    {
        'name': 'MM 2014',
        'Book': 'MM (2014)',
        'Legendary': ['N','L','LL'],
        'color': COLORS[0],
        'line_color': COLORS[0],
        'symbol': 'circle',
    },
    {
        'name': 'MM 2024',
        'Book': 'MM (2024)',
        'Legendary': ['N','L','LL'],
        'color': COLORS[1],
        'line_color': COLORS[1],
        'symbol': 'circle',
    },
]

# create figure
fig = go.Figure(
    layout=go.Layout(
        template=tfb.FIG_TEMPLATE,
        margin=dict(l=70, r=25, b=55, t=20, pad=4),
        xaxis=dict(
            title_text='challenge rating',
            range=[0,31],
            tick0=0, dtick=5,
            minor=dict(tick0=0, dtick=1),
        ),
        yaxis=dict(
            title_text=f'save difficulty class',
            #range=[0,3],
            tick0=0, dtick=2,
            minor=dict(tick0=0, dtick=1),
        ),
        legend=dict(
            xanchor='left', yanchor='top',
            x=0.00, y=1.00,
            orientation='v',
            tracegroupgap=0,
        )
    )
)

# plot monster data
for group in groups:
    name = group['name']
    book = group['Book']
    legendary = group['Legendary']
    df1 = df0[df0['Book'].isin([book]) & df0['Legendary'].isin(legendary)]
    dfG = df1[['CR',column]].groupby(['CR']).mean().reset_index()
    fig.add_trace(go.Scatter(
        x=dfG['CR'], 
        y=dfG[column],
        mode='markers+lines', 
        name=name,
        marker_color=group['color'],
        marker_symbol=group['symbol'],
        line_color=group['line_color'],
        hovertemplate = f'<b>{name}</b><br>'
            + 'CR %{x:.0f}<br>'
            + 'DC %{y:.1f}'
            + '<extra></extra>'
    ))

fig.add_trace(go.Scatter(
    x=dfT['CR'], 
    y=dfT[column],
    mode='lines', 
    name=f'baseline',
    showlegend=False,
    line_color='black',
    line_dash='dash',
    hoverinfo='skip',
))

# show figure
fig.update_layout(width=600, height=450)
fig.show(config=tfb.FIG_CONFIG)

# save figures
if SAVEFIGS:
    fig.update_layout(autosize=True, width=None, height=None)
    tfb.save_fig_html(fig, format='large', name=f'./fig-save-dc-vs-cr-large')
    tfb.save_fig_html(fig, format='small', name=f'./fig-save-dc-vs-cr-small')

In [285]:
# Fig. 3: DPR vs challenge rating
column = 'adj DPR'
groups = [
    {
        'name': 'MM 2014',
        'Book': 'MM (2014)',
        'Legendary': ['N','L','LL'],
        'color': COLORS[0],
        'line_color': COLORS[0],
        'symbol': 'circle',
    },
    {
        'name': 'MM 2024',
        'Book': 'MM (2024)',
        'Legendary': ['N','L','LL'],
        'color': COLORS[1],
        'line_color': COLORS[1],
        'symbol': 'circle',
    },
]

# create figure
fig = go.Figure(
    layout=go.Layout(
        template=tfb.FIG_TEMPLATE,
        margin=dict(l=70, r=25, b=55, t=20, pad=4),
        xaxis=dict(
            title_text='challenge rating',
            range=[0,31],
            tick0=0, dtick=5,
            minor=dict(tick0=0, dtick=1),
        ),
        yaxis=dict(
            title_text='damage per round',
            #range=[0,3],
            tick0=0, dtick=50,
            minor=dict(tick0=0, dtick=10),
        ),
        legend=dict(
            xanchor='left', yanchor='top',
            x=0.00, y=1.00,
            orientation='v',
            tracegroupgap=0,
        )
    )
)

# plot monster data
for group in groups:
    name = group['name']
    book = group['Book']
    legendary = group['Legendary']
    df1 = df0[df0['Book'].isin([book]) & df0['Legendary'].isin(legendary)]
    dfG = df1[['CR',column]].groupby(['CR']).mean().reset_index()
    fig.add_trace(go.Scatter(
        x=dfG['CR'], 
        y=dfG[column],
        mode='markers+lines', 
        name=name,
        marker_color=group['color'],
        marker_symbol=group['symbol'],
        line_color=group['line_color'],
        hovertemplate = f'<b>{name}</b><br>'
            + 'CR %{x:.0f}<br>'
            + 'DPR %{y:.1f}'
            + '<extra></extra>'
    ))

fig.add_trace(go.Scatter(
    x=dfT['CR'], 
    y=dfT[column],
    mode='lines', 
    name=f'baseline',
    showlegend=False,
    line_color='black',
    line_dash='dash',
    hoverinfo='skip',
))

# show figure
fig.update_layout(width=600, height=450)
fig.show(config=tfb.FIG_CONFIG)

# save figures
if SAVEFIGS:
    fig.write_image('../../assets/images/monster-manual-2024.png')
    fig.update_layout(autosize=True, width=None, height=None)
    tfb.save_fig_html(fig, format='large', name=f'./fig-dpr-vs-cr-large')
    tfb.save_fig_html(fig, format='small', name=f'./fig-dpr-vs-cr-small')

In [286]:
# Fig. 4: DPR vs challenge rating
column = 'adj DPR Ratio'
groups = [
    {
        'name': 'MM 2014',
        'Book': 'MM (2014)',
        'Legendary': ['N','L','LL'],
        'color': COLORS[0],
        'line_color': COLORS[0],
        'symbol': 'circle',
    },
    {
        'name': 'MM 2024 - normal',
        'Book': 'MM (2024)',
        'Legendary': ['N'],
        'color': COLORS[1],
        'line_color': COLORS[1],
        'symbol': 'circle',
    },
    {
        'name': 'MM 2024 - legendary',
        'Book': 'MM (2024)',
        'Legendary': ['L','LL'],
        'color': COLORS[1],
        'line_color': COLORS[1],
        'symbol': 'square',
    }
]

# create figure
fig = go.Figure(
    layout=go.Layout(
        template=tfb.FIG_TEMPLATE,
        margin=dict(l=70, r=25, b=55, t=20, pad=4),
        xaxis=dict(
            title_text='challenge rating',
            range=[0,31],
            tick0=0, dtick=5,
            minor=dict(tick0=0, dtick=1),
        ),
        yaxis=dict(
            title_text='normalized damage per round',
            range=[0,2],
            tick0=0, dtick=0.5,
            minor=dict(tick0=0, dtick=0.1),
            tickformat='.1f',
        ),
        legend=dict(
            xanchor='left', yanchor='bottom',
            x=0.00, y=0.00,
            orientation='v',
            tracegroupgap=0,
        )
    )
)

# plot monster data
for group in groups:
    name = group['name']
    book = group['Book']
    legendary = group['Legendary']
    df1 = df0[df0['Book'].isin([book]) & df0['Legendary'].isin(legendary)]
    dfG = df1[['CR',column]].groupby(['CR']).mean().reset_index()
    fig.add_trace(go.Scatter(
        x=dfG['CR'], 
        y=dfG[column],
        mode='markers+lines', 
        name=name,
        marker_color=group['color'],
        marker_symbol=group['symbol'],
        line_color=group['line_color'],
        hovertemplate = f'<b>{name}</b><br>'
            + 'CR %{x:.0f}<br>'
            + 'DPR ratio %{y:.2f}'
            + '<extra></extra>'
    ))

fig.add_trace(go.Scatter(
    x=dfT['CR'], 
    y=dfT[column],
    mode='lines', 
    name=f'baseline',
    showlegend=False,
    line_color='black',
    line_dash='dash',
    hoverinfo='skip',
))

# show figure
fig.update_layout(width=600, height=450)
fig.show(config=tfb.FIG_CONFIG)

# save figures
if SAVEFIGS:
    fig.update_layout(autosize=True, width=None, height=None)
    tfb.save_fig_html(fig, format='large', name=f'./fig-dpr-ratio-vs-cr-large')
    tfb.save_fig_html(fig, format='small', name=f'./fig-dpr-ratio-vs-cr-small')

In [287]:
# Fig. 5: armor class vs challenge rating
column = 'adj AC'
groups = [
    {
        'name': 'MM 2014',
        'Book': 'MM (2014)',
        'Legendary': ['N','L','LL'],
        'color': COLORS[0],
        'line_color': COLORS[0],
        'symbol': 'circle',
    },
    {
        'name': 'MM 2024',
        'Book': 'MM (2024)',
        'Legendary': ['N','L','LL'],
        'color': COLORS[1],
        'line_color': COLORS[1],
        'symbol': 'circle',
    },
]

# create figure
fig = go.Figure(
    layout=go.Layout(
        template=tfb.FIG_TEMPLATE,
        margin=dict(l=70, r=25, b=55, t=20, pad=4),
        xaxis=dict(
            title_text='challenge rating',
            range=[0,31],
            tick0=0, dtick=5,
            minor=dict(tick0=0, dtick=1),
        ),
        yaxis=dict(
            title_text='armor class',
            range=[12,30],
            tick0=0, dtick=2,
            minor=dict(tick0=0, dtick=1),
            tickformat='.0f',
        ),
        legend=dict(
            xanchor='left', yanchor='top',
            x=0.00, y=1.00,
            orientation='v',
            tracegroupgap=0,
        )
    )
)

# plot monster data
for group in groups:
    name = group['name']
    book = group['Book']
    legendary = group['Legendary']
    df1 = df0[df0['Book'].isin([book]) & df0['Legendary'].isin(legendary)]
    dfG = df1[['CR',column]].groupby(['CR']).mean().reset_index()
    fig.add_trace(go.Scatter(
        x=dfG['CR'], 
        y=dfG[column],
        mode='markers+lines', 
        name=name,
        marker_color=group['color'],
        marker_symbol=group['symbol'],
        line_color=group['line_color'],
        hovertemplate = f'<b>{name}</b><br>'
            + 'CR %{x:.0f}<br>'
            + 'AC %{y:.1f}'
            + '<extra></extra>'
    ))

fig.add_trace(go.Scatter(
    x=dfT['CR'], 
    y=dfT[column],
    mode='lines', 
    name=f'baseline',
    showlegend=False,
    line_color='black',
    line_dash='dash',
    hoverinfo='skip',
))

# show figure
fig.update_layout(width=600, height=450)
fig.show(config=tfb.FIG_CONFIG)

# save figures
if SAVEFIGS:
    fig.update_layout(autosize=True, width=None, height=None)
    tfb.save_fig_html(fig, format='large', name=f'./fig-ac-vs-cr-large')
    tfb.save_fig_html(fig, format='small', name=f'./fig-ac-vs-cr-small')

In [288]:
# Fig. 6: save bonus vs challenge rating
column = 'adj SB'
groups = [
    {
        'name': 'MM 2014',
        'Book': 'MM (2014)',
        'Legendary': ['N','L','LL'],
        'color': COLORS[0],
        'line_color': COLORS[0],
        'symbol': 'circle',
    },
    {
        'name': 'MM 2024',
        'Book': 'MM (2024)',
        'Legendary': ['N','L','LL'],
        'color': COLORS[1],
        'line_color': COLORS[1],
        'symbol': 'circle',
    },
]

# create figure
fig = go.Figure(
    layout=go.Layout(
        template=tfb.FIG_TEMPLATE,
        margin=dict(l=70, r=25, b=55, t=20, pad=4),
        xaxis=dict(
            title_text='challenge rating',
            range=[0,31],
            tick0=0, dtick=5,
            minor=dict(tick0=0, dtick=1),
        ),
        yaxis=dict(
            title_text='save bonus',
            range=[-2,16],
            tick0=0, dtick=2,
            minor=dict(tick0=0, dtick=1),
            tickformat='.0f',
        ),
        legend=dict(
            xanchor='left', yanchor='top',
            x=0.00, y=1.00,
            orientation='v',
            tracegroupgap=0,
        )
    )
)

# plot monster data
for group in groups:
    name = group['name']
    book = group['Book']
    legendary = group['Legendary']
    df1 = df0[df0['Book'].isin([book]) & df0['Legendary'].isin(legendary)]
    dfG = df1[['CR',column]].groupby(['CR']).mean().reset_index()
    fig.add_trace(go.Scatter(
        x=dfG['CR'], 
        y=dfG[column],
        mode='markers+lines', 
        name=name,
        marker_color=group['color'],
        marker_symbol=group['symbol'],
        line_color=group['line_color'],
        hovertemplate = f'<b>{name}</b><br>'
            + 'CR %{x:.0f}<br>'
            + 'SB %{y:.1f}'
            + '<extra></extra>'
    ))
    coefs = np.polyfit(dfG['CR'], dfG[column], 1)
    print(f'{name}: {coefs[1]:.3f} + {coefs[0]:.3f}*CR')

fig.add_trace(go.Scatter(
    x=dfT['CR'], 
    y=dfT[column],
    mode='lines', 
    name=f'baseline',
    showlegend=False,
    line_color='black',
    line_dash='dash',
    hoverinfo='skip',
))


# show figure
fig.update_layout(width=600, height=450)
fig.show(config=tfb.FIG_CONFIG)

# save figures
if SAVEFIGS:
    fig.update_layout(autosize=True, width=None, height=None)
    tfb.save_fig_html(fig, format='large', name=f'./fig-sb-vs-cr-large')
    tfb.save_fig_html(fig, format='small', name=f'./fig-sb-vs-cr-small')

MM 2014: 0.951 + 0.435*CR
MM 2024: 1.282 + 0.352*CR

In [289]:
# Fig. 7: number of monsters who gained or lost saving throw proficiencies
# create figure
fig = go.Figure(
    layout=go.Layout(
        template=tfb.FIG_TEMPLATE,
        margin=dict(l=70, r=25, b=55, t=20, pad=4),
        barmode='relative',
        #xaxis=dict(title_text='change'),
        yaxis=dict(
            title_text='monsters',
            #range=[0,100],
            tick0=0, dtick=10,
            minor=dict(tick0=0, dtick=5),
        ),
        legend=dict(
            xanchor='left', yanchor='bottom',
            x=0.00, y=0.00,
            orientation='v',
            tracegroupgap=0,
            traceorder='normal',
        )
    )
)

names = ['Strength','Dexterity','Constitution','Intelligence','Wisdom','Charisma']
stats = [
    'Str Save Prof','Dex Save Prof','Con Save Prof',
    'Int Save Prof','Wis Save Prof','Cha Save Prof',
]

df1 = df0[df0['Book'].isin(['MM (2014)','MM (2024)']) & df0['Legendary'].isin(['N','L','LL'])]
dfMP = pd.pivot_table(df1, 
    values=['HP'] + stats, 
    index=['Monster', 'CR'], columns=['Book']).reset_index()
dfMP = dfMP[dfMP['HP']['MM (2014)'].isna() == False]
dfMP = dfMP[dfMP['HP']['MM (2024)'].isna() == False]
m_count = dfMP.shape[0]

data = {}
for name, stat in zip(names, stats):
    data[name] = np.sum((dfMP[stat]['MM (2024)'] - dfMP[stat]['MM (2014)']) > 0)

fig.add_trace(go.Bar(
    #x=np.array([k[0:3] for k in data.keys()]),
    x=np.array(names),
    y=np.array(list(data.values()))*(1), #(100/m_count),
    name='gained proficiency',
    hovertemplate = ''
        + '%{y:,.0f} gained proficiency'
        + '<extra></extra>'
))

data = {}
for stat in stats:
    data[stat] = np.sum((dfMP[stat]['MM (2024)'] - dfMP[stat]['MM (2014)']) < 0)

fig.add_trace(go.Bar(
    #x=np.array([k[0:3] for k in data.keys()]),
    x=np.array(names),
    y=np.array(list(data.values()))*(-1), #(-100/m_count),
    customdata=np.array(list(data.values())),
    name='lost proficiency',
    hovertemplate = ''
        + '%{customdata:,.0f} lost proficiency'
        + '<extra></extra>'
))

# show figure
fig.update_layout(width=600, height=450, hovermode='x unified')
fig.show(config=tfb.FIG_CONFIG)

# save figures
if SAVEFIGS:
    fig.update_layout(autosize=True, width=None, height=None)
    tfb.save_fig_html(fig, format='large', name=f'./fig-sp-delta-by-ability-large')
    fig.update_xaxes(tickmode='array', tickvals=names, ticktext=[n[0:3] for n in names])
    tfb.save_fig_html(fig, format='small', name=f'./fig-sp-delta-by-ability-small')

/var/folders/k4/phz5f3ss2_91t6j4s71jmp540000gn/T/ipykernel_25198/2990474350.py:32: FutureWarning:

The default value of observed=False is deprecated and will change to observed=True in a future version of pandas. Specify observed=False to silence this warning and retain the current behavior

In [145]:
# Fig. 8: save bonus vs challenge rating
columns = ['Str Save','Dex Save','Con Save','Int Save','Wis Save','Cha Save']
colors = ['#d62728','#9467bd','#8c564b','#1f77b4','#2ca02c','#ff7f0e']
groups = [
    {
        'name': 'MM 2024',
        'Book': 'MM (2024)',
        'Legendary': ['N','L','LL'],
        'color': COLORS[1],
        'line_color': COLORS[1],
        'symbol': 'circle',
    },
]

# create figure
fig = go.Figure(
    layout=go.Layout(
        template=tfb.FIG_TEMPLATE,
        margin=dict(l=70, r=25, b=55, t=20, pad=4),
        xaxis=dict(
            title_text='challenge rating',
            range=[0,31],
            tick0=0, dtick=5,
            minor=dict(tick0=0, dtick=1),
        ),
        yaxis=dict(
            title_text='save bonus',
            range=[-2,16],
            tick0=0, dtick=2,
            minor=dict(tick0=0, dtick=1),
            tickformat='.0f',
        ),
        legend=dict(
            xanchor='left', yanchor='top',
            x=0.00, y=1.00,
            orientation='v',
            tracegroupgap=0,
        )
    )
)

# plot monster data
for group in groups:
    name = group['name']
    book = group['Book']
    legendary = group['Legendary']
    

    df1 = df0[df0['Book'].isin([book]) & df0['Legendary'].isin(legendary)]
    dfG = df1[['CR','SB','adj SB',*columns]].groupby(['CR']).mean().reset_index()

    for column, color in zip(columns, colors):
        tfb.plot_data_and_fit(
            fig, 
            x=dfG['CR'], 
            y=dfG[column] + dfG['adj SB'] - dfG['SB'],
            name=column,
            legendgroup=column,
            line=dict(color=color),
            print_coefficients=False,
            hovertemplate = f'<b>{name}</b><br>'
                + 'CR %{x:.0f}<br>'
                + column + ' %{y:.1f}'
                + '<extra></extra>'
        )

# show figure
fig.update_layout(width=600, height=450)
fig.show(config=tfb.FIG_CONFIG)

# save figures
if SAVEFIGS:
    fig.update_layout(autosize=True, width=None, height=None)
    tfb.save_fig_html(fig, format='large', name=f'./fig-all-sb-vs-cr-large', marker_size=6)
    tfb.save_fig_html(fig, format='small', name=f'./fig-all-sb-vs-cr-small', marker_size=4)

In [290]:
# Fig. 9: hit points vs challenge rating
column = 'adj HP'
groups = [
    {
        'name': 'MM 2014',
        'Book': 'MM (2014)',
        'Legendary': ['N','L','LL'],
        'color': COLORS[0],
        'line_color': COLORS[0],
        'symbol': 'circle',
    },
    {
        'name': 'MM 2024',
        'Book': 'MM (2024)',
        'Legendary': ['N','L','LL'],
        'color': COLORS[1],
        'line_color': COLORS[1],
        'symbol': 'circle',
    },
]

# create figure
fig = go.Figure(
    layout=go.Layout(
        template=tfb.FIG_TEMPLATE,
        margin=dict(l=70, r=25, b=55, t=20, pad=4),
        xaxis=dict(
            title_text='challenge rating',
            range=[0,31],
            tick0=0, dtick=5,
            minor=dict(tick0=0, dtick=1),
        ),
        yaxis=dict(
            title_text='hit points',
            tick0=0, dtick=200,
            minor=dict(tick0=0, dtick=100),
            tickformat='.0f',
        ),
        legend=dict(
            xanchor='left', yanchor='top',
            x=0.00, y=1.00,
            orientation='v',
            tracegroupgap=0,
        )
    )
)

def unadjust_legendary(row):
    if row['Legendary'] not in ['L','LL']: return row['adj HP']
    
    lr_hp = 10
    if row['CR'] >= 5: lr_hp += 10
    if row['CR'] >= 11: lr_hp += 10
    
    lr_count = 3
    if row['CR'] >= 20: lr_count += 1
    if row['CR'] >= 30: lr_count += 2

    if row['Legendary'] == 'LL': lr_count += 1

    return row['adj HP'] - lr_count*lr_hp

# plot monster data
for group in groups:
    name = group['name']
    book = group['Book']
    legendary = group['Legendary']
    df1 = df0[df0['Book'].isin([book]) & df0['Legendary'].isin(legendary)]
    #if book == 'MM (2024)':
    #    df1['adj HP'] = df1.apply(lambda r: unadjust_legendary(r), axis=1)
    #    df1['adj HP Ratio'] = df1.apply(lambda r: r['adj HP']/dfB.loc[r['CR']]['adj HP'], axis=1)
    dfG = df1[['CR',column]].groupby(['CR']).mean().reset_index()
    fig.add_trace(go.Scatter(
        x=dfG['CR'], 
        y=dfG[column],
        mode='markers+lines', 
        name=name,
        marker_color=group['color'],
        marker_symbol=group['symbol'],
        line_color=group['line_color'],
        hovertemplate = f'<b>{name}</b><br>'
            + 'CR %{x:.0f}<br>'
            + 'HP %{y:.1f}'
            + '<extra></extra>'
    ))

fig.add_trace(go.Scatter(
    x=dfT['CR'], 
    y=dfT[column],
    mode='lines', 
    name=f'baseline',
    showlegend=False,
    line_color='black',
    line_dash='dash',
    hoverinfo='skip',
))

# show figure
fig.update_layout(width=600, height=450)
fig.show(config=tfb.FIG_CONFIG)

# save figures
if SAVEFIGS:
    fig.update_layout(autosize=True, width=None, height=None)
    tfb.save_fig_html(fig, format='large', name=f'./fig-hp-vs-cr-large')
    tfb.save_fig_html(fig, format='small', name=f'./fig-hp-vs-cr-small')

In [281]:
# Fig. 10: hit points vs challenge rating
column = 'adj HP Ratio'
groups = [
    {
        'name': 'MM 2014',
        'Book': 'MM (2014)',
        'Legendary': ['N','L','LL'],
        'color': COLORS[0],
        'line_color': COLORS[0],
        'symbol': 'circle',
    },
    {
        'name': 'MM 2024 - normal',
        'Book': 'MM (2024)',
        'Legendary': ['N'],
        'color': COLORS[1],
        'line_color': COLORS[1],
        'symbol': 'circle',
    },
    {
        'name': 'MM 2024 - legendary',
        'Book': 'MM (2024)',
        'Legendary': ['L','LL'],
        'color': COLORS[1],
        'line_color': COLORS[1],
        'symbol': 'square',
    }
]

# create figure
fig = go.Figure(
    layout=go.Layout(
        template=tfb.FIG_TEMPLATE,
        margin=dict(l=70, r=25, b=55, t=20, pad=4),
        xaxis=dict(
            title_text='challenge rating',
            range=[0,31],
            tick0=0, dtick=5,
            minor=dict(tick0=0, dtick=1),
        ),
        yaxis=dict(
            title_text='normalized hit points',
            range=[0,2],
            tick0=0, dtick=0.5,
            minor=dict(tick0=0, dtick=0.1),
        ),
        legend=dict(
            xanchor='left', yanchor='bottom',
            x=0.00, y=0.00,
            orientation='v',
            tracegroupgap=0,
        )
    )
)




# plot monster data
for group in groups:
    name = group['name']
    book = group['Book']
    legendary = group['Legendary']
    df1 = df0[df0['Book'].isin([book]) & df0['Legendary'].isin(legendary)]
    print(f"{name} - {column} = {np.mean(df1[column]):.3f}")
    dfG = df1[['CR',column]].groupby(['CR']).mean().reset_index()
    fig.add_trace(go.Scatter(
        x=dfG['CR'], 
        y=dfG[column],
        mode='markers+lines', 
        name=name,
        marker_color=group['color'],
        marker_symbol=group['symbol'],
        line_color=group['line_color'],
        hovertemplate = f'<b>{name}</b><br>'
            + 'CR %{x:.0f}<br>'
            + 'HP ratio %{y:.2f}'
            + '<extra></extra>'
    ))

fig.add_trace(go.Scatter(
    x=dfT['CR'], 
    y=dfT[column],
    mode='lines', 
    name=f'baseline',
    showlegend=False,
    line_color='black',
    line_dash='dash',
    hoverinfo='skip',
))

# show figure
fig.update_layout(width=600, height=450)
fig.show(config=tfb.FIG_CONFIG)

# save figures
if SAVEFIGS:
    fig.update_layout(autosize=True, width=None, height=None)
    tfb.save_fig_html(fig, format='large', name=f'./fig-hp-ratio-vs-cr-large')
    tfb.save_fig_html(fig, format='small', name=f'./fig-hp-ratio-vs-cr-small')

MM 2014 - adj HP Ratio = 1.081
MM 2024 - normal - adj HP Ratio = 1.034
MM 2024 - legendary - adj HP Ratio = 1.257

In [ ]:
# Fig. 11: hit points (no legendary resistances) vs challenge rating
column = 'adj HP Ratio'
groups = [
    {
        'name': 'MM 2014',
        'Book': 'MM (2014)',
        'Legendary': ['N','L','LL'],
        'color': COLORS[0],
        'line_color': COLORS[0],
        'symbol': 'circle',
    },
    {
        'name': 'MM 2024 - normal',
        'Book': 'MM (2024)',
        'Legendary': ['N'],
        'color': COLORS[1],
        'line_color': COLORS[1],
        'symbol': 'circle',
    },
    {
        'name': 'MM 2024 - legendary',
        'Book': 'MM (2024)',
        'Legendary': ['L','LL'],
        'color': COLORS[1],
        'line_color': COLORS[1],
        'symbol': 'square',
    }
]

# create figure
fig = go.Figure(
    layout=go.Layout(
        template=tfb.FIG_TEMPLATE,
        margin=dict(l=70, r=25, b=55, t=20, pad=4),
        xaxis=dict(
            title_text='challenge rating',
            range=[0,31],
            tick0=0, dtick=5,
            minor=dict(tick0=0, dtick=1),
        ),
        yaxis=dict(
            title_text='normalized hit points',
            range=[0,2],
            tick0=0, dtick=0.5,
            minor=dict(tick0=0, dtick=0.1),
        ),
        legend=dict(
            xanchor='left', yanchor='bottom',
            x=0.00, y=0.00,
            orientation='v',
            tracegroupgap=0,
        )
    )
)

# plot monster data
for group in groups:
    name = group['name']
    book = group['Book']
    legendary = group['Legendary']
    df1 = df0[df0['Book'].isin([book]) & df0['Legendary'].isin(legendary)]
    if book in ['MM (2024)']:
        df1['adj HP'] = df1.apply(lambda row: unadjust_hit_points(row), axis=1)
        df1['adj HP Ratio'] = df1.apply(lambda row: row['adj HP']/dfB.loc[row['CR']]['adj HP'], axis=1)

    print(f"{name} - {column} = {np.mean(df1[column]):.3f}")
    dfG = df1[['CR',column]].groupby(['CR']).mean().reset_index()
    fig.add_trace(go.Scatter(
        x=dfG['CR'], 
        y=dfG[column],
        mode='markers+lines', 
        name=name,
        marker_color=group['color'],
        marker_symbol=group['symbol'],
        line_color=group['line_color'],
        hovertemplate = f'<b>{name}</b><br>'
            + 'CR %{x:.0f}<br>'
            + 'HP ratio %{y:.2f}'
            + '<extra></extra>'
    ))

fig.add_trace(go.Scatter(
    x=dfT['CR'], 
    y=dfT[column],
    mode='lines', 
    name=f'baseline',
    showlegend=False,
    line_color='black',
    line_dash='dash',
    hoverinfo='skip',
))

# show figure
fig.update_layout(width=600, height=450)
fig.show(config=tfb.FIG_CONFIG)

# save figures
if SAVEFIGS:
    fig.update_layout(autosize=True, width=None, height=None)
    tfb.save_fig_html(fig, format='large', name=f'./fig-mod-hp-ratio-vs-cr-large')
    tfb.save_fig_html(fig, format='small', name=f'./fig-mod-hp-ratio-vs-cr-small')

MM 2014 - adj HP Ratio = 1.064
MM 2014 - adj HP Ratio = 1.044
MM 2024 - normal - adj HP Ratio = 1.040
MM 2024 - normal - adj HP Ratio = 1.048
MM 2024 - legendary - adj HP Ratio = 0.912
MM 2024 - legendary - adj HP Ratio = 0.928

In [ ]:
# Fig. 12: Shows normalized XP vs challenge rating
column = 'eXP Ratio'
groups = [
    {
        'name': 'MM 2014',
        'Book': 'MM (2014)',
        'Legendary': ['N','L','LL'],
        'color': COLORS[0],
        'line_color': COLORS[0],
        'symbol': 'circle',
    },
    {
        'name': 'MM 2024 - normal',
        'Book': 'MM (2024)',
        'Legendary': ['N'],
        'color': COLORS[1],
        'line_color': COLORS[1],
        'symbol': 'circle',
    },
    {
        'name': 'MM 2024 - legendary',
        'Book': 'MM (2024)',
        'Legendary': ['L','LL'],
        'color': COLORS[1],
        'line_color': COLORS[1],
        'symbol': 'square',
    }
]

# create figure
fig = go.Figure(
    layout=go.Layout(
        template=tfb.FIG_TEMPLATE,
        margin=dict(l=70, r=25, b=55, t=20, pad=4),
        xaxis=dict(
            title_text='challenge rating',
            range=[0,31],
            tick0=0, dtick=5,
            minor=dict(tick0=0, dtick=1),
        ),
        yaxis=dict(
            title_text='normalized XP',
            range=[0,2.5],
            tick0=0, dtick=0.5, tickformat='.1f',
            minor=dict(tick0=0, dtick=0.1),
        ),
        legend=dict(
            xanchor='left', yanchor='bottom',
            x=0.00, y=0.00,
            orientation='v',
            tracegroupgap=0,
        )
    )
)

# plot monster data
for group in groups:
    name = group['name']
    book = group['Book']
    legendary = group['Legendary']
    df1 = df0[df0['Book'].isin([book]) & df0['Legendary'].isin(legendary)]
    print(f"{name} - {column} = {np.mean(df1[column]):.3f}")
    dfG = df1[['CR',column]].groupby(['CR']).mean().reset_index()
    fig.add_trace(go.Scatter(
        x=dfG['CR'], 
        y=dfG[column],
        mode='markers+lines', 
        name=name,
        marker_color=group['color'],
        marker_symbol=group['symbol'],
        line_color=group['line_color'],
        hovertemplate = f'<b>{name}</b><br>'
            + 'CR %{x:.0f}<br>'
            + 'XP ratio %{y:.2f}'
            + '<extra></extra>'
    ))

fig.add_trace(go.Scatter(
    x=dfT['CR'], 
    y=dfT[column],
    mode='lines', 
    name=f'baseline',
    showlegend=False,
    line_color='black',
    line_dash='dash',
    hoverinfo='skip',
))

# show figure
fig.update_layout(width=600, height=450)
fig.show(config=tfb.FIG_CONFIG)

# save figures
if SAVEFIGS:
    fig.update_layout(autosize=True, width=None, height=None)
    tfb.save_fig_html(fig, format='large', name=f'./fig-xp-ratio-vs-cr-large')
    tfb.save_fig_html(fig, format='small', name=f'./fig-xp-ratio-vs-cr-small')

MM 2014 - eXP Ratio = 0.931
MM 2024 - normal - eXP Ratio = 1.005
MM 2024 - legendary - eXP Ratio = 1.737

In [ ]:
# Fig. 13: Shows normalized XP distributions
column = 'eXP Ratio'
groups = [
    {
        'name': 'MM 2014 - normal',
        'Book': 'MM (2014)',
        'Legendary': ['N'],
        'color': COLORS[0],
        'line_color': COLORS[0],
        'symbol': 'circle',
    },
    {
        'name': 'MM 2014 - legendary',
        'Book': 'MM (2014)',
        'Legendary': ['L','LL'],
        'color': COLORS[0],
        'line_color': COLORS[0],
        'symbol': 'square',
    },
    {
        'name': 'MM 2024 - normal',
        'Book': 'MM (2024)',
        'Legendary': ['N'],
        'color': COLORS[1], 
        'line_color': COLORS[1], 
        'symbol': 'circle',
    },
    {
        'name': 'MM 2024 - legendary',
        'Book': 'MM (2024)',
        'Legendary': ['L','LL'],
        'color': COLORS[1],
        'line_color': COLORS[1], 
        'symbol': 'square',
    },
]

# create figure
fig = go.Figure(
    layout=go.Layout(
        template=tfb.FIG_TEMPLATE,
        margin=dict(l=60, r=25, b=65, t=20, pad=4),
        xaxis=dict(
            autorange=True,
            tickmode='array',
            tickvals=['MM 2014 - normal','MM 2014 - legendary','MM 2024 - normal','MM 2024 - legendary'],
            ticktext=['normal','legendary','normal','legendary'],
        ),
        yaxis=dict(
            title_text=f'normalized XP',
            range=[0, 2.5],
            tick0=0, dtick=0.5,
            minor=dict(tick0=0, dtick=0.1),
        ),
    )
)

for group in groups:
    book = group['Book']
    name = group['name']
    df1 = df0[df0['Book'].isin([book]) & df0['Legendary'].isin(group['Legendary'])]
    print(f"{name} - {column} = {np.mean(df1[column]):.3f}")
    fig.add_trace(go.Box(
        y=df1[column],
        name=name,
        customdata=df1['Monster'],
        showlegend=False,
        boxpoints='all',
        jitter=0.8,
        whiskerwidth=0.4,
        pointpos=-2,
        marker_size=2,
        marker_symbol=group['symbol'],
        marker_color=group['color'],
        marker_line_color=group['line_color'],
        marker_line_width=2,
        hoveron='points',
        hovertemplate=f'<b>{name}</b><br>'+
            '%{customdata}<br>'+
            'XP ratio %{y:.2f}<br>'+
            '<extra></extra>'
    ))

fig.add_annotation(
    text='MM 2014',
    xref='paper', yref='paper',
    xanchor='center', yanchor='top',
    x=0.3, y=-0.1, 
    showarrow=False,
)
fig.add_annotation(
    text='MM 2024',
    xref='paper', yref='paper',
    xanchor='center', yanchor='top',
    x=0.73, y=-0.1, 
    showarrow=False,
)

# show figure
fig.update_layout(width=600, height=450)
fig.show(config=tfb.FIG_CONFIG)

# save figures
if SAVEFIGS:
    fig.update_layout(autosize=True, width=None, height=None)
    tfb.save_fig_html(fig, format='large', name=f'./fig-xp-ratio-distribution-large')
    fig.update_traces(marker_size=1)
    tfb.save_fig_html(fig, format='small', name=f'./fig-xp-ratio-distribution-small')

MM 2014 - normal - eXP Ratio = 0.897
MM 2014 - legendary - eXP Ratio = 1.165
MM 2024 - normal - eXP Ratio = 1.005
MM 2024 - legendary - eXP Ratio = 1.737

In [ ]:
# Fig. 14: initiative vs challenge rating.
column = 'Initiative'
groups = [
    {
        'name': 'MM 2014',
        'Book': 'MM (2014)',
        'Legendary': ['N','L','LL'],
        'color': COLORS[0],
        'line_color': COLORS[0],
        'symbol': 'circle',
    },
    {
        'name': 'MM 2024',
        'Book': 'MM (2024)',
        'Legendary': ['N','L','LL'],
        'color': COLORS[1],
        'line_color': COLORS[1],
        'symbol': 'circle',
    },
]

# create figure
fig = go.Figure(
    layout=go.Layout(
        template=tfb.FIG_TEMPLATE,
        margin=dict(l=70, r=25, b=55, t=20, pad=4),
        xaxis=dict(
            title_text='challenge rating',
            range=[0,30],
            tick0=0, dtick=5,
            minor=dict(tick0=0, dtick=1),
        ),
        yaxis=dict(
            title_text='initiative bonus',
            autorange=True,
            #range=[0,3],
            #tick0=0, dtick=50,
            #minor=dict(tick0=0, dtick=10),
        ),
        legend=dict(
            xanchor='left', yanchor='top',
            x=0.00, y=1.00,
            orientation='v',
            tracegroupgap=0,
        )
    )
)

# plot monster data
for group in groups:
    name = group['name']
    book = group['Book']
    legendary = group['Legendary']
    df1 = df0[df0['Book'].isin([book]) & df0['Legendary'].isin(legendary)]
    dfG = df1[['CR',column]].groupby(['CR']).mean().reset_index()
    fig.add_trace(go.Scatter(
        x=dfG['CR'], 
        y=dfG[column],
        mode='markers+lines', 
        name=name,
        marker_color=group['color'],
        marker_symbol=group['symbol'],
        line_color=group['line_color'],
        hovertemplate = f'<b>{name}</b><br>'
            + 'CR %{x:.0f}<br>'
            + 'Initiative %{y:.1f}'
            + '<extra></extra>'
    ))

# show figure
fig.update_layout(width=600, height=450)
fig.show(config=tfb.FIG_CONFIG)

# save figures
if SAVEFIGS:
    fig.update_layout(autosize=True, width=None, height=None)
    tfb.save_fig_html(fig, format='large', name=f'./fig-initiative-vs-cr-large')
    tfb.save_fig_html(fig, format='small', name=f'./fig-initiative-vs-cr-small')

In [ ]:
# Fig. 15: initiative proficiency vs challenge rating.
column = 'Initiative'
groups = [
    {
        'name': 'MM 2014',
        'Book': 'MM (2014)',
        'Legendary': ['N','L','LL'],
        'color': COLORS[0],
        'line_color': COLORS[0],
        'symbol': 'circle',
    },
    {
        'name': 'MM 2024 - normal',
        'Book': 'MM (2024)',
        'Legendary': ['N'],
        'color': COLORS[1],
        'line_color': COLORS[1],
        'symbol': 'circle',
    },
    {
        'name': 'MM 2024 - legendary',
        'Book': 'MM (2024)',
        'Legendary': ['L'],
        'color': COLORS[1],
        'line_color': COLORS[1],
        'symbol': 'square',
    },
]

# create figure
fig = go.Figure(
    layout=go.Layout(
        template=tfb.FIG_TEMPLATE,
        margin=dict(l=70, r=25, b=55, t=20, pad=4),
        xaxis=dict(
            title_text='challenge rating',
            range=[0,31],
            tick0=0, dtick=5,
            minor=dict(tick0=0, dtick=1),
        ),
        yaxis=dict(
            title_text='initiative proficiency',
            autorange=True,
            #range=[0,3],
            #tick0=0, dtick=50,
            #minor=dict(tick0=0, dtick=10),
            tickformat='.1f',
        ),
        legend=dict(
            xanchor='right', yanchor='bottom',
            x=1.00, y=0.15,
            orientation='v',
            tracegroupgap=0,
        )
    )
)

# plot monster data
for group in groups:
    name = group['name']
    book = group['Book']
    legendary = group['Legendary']
    df1 = df0[df0['Book'].isin([book]) & df0['Legendary'].isin(legendary)]
    df1['Initiative ratio'] = (df1['Initiative'] - df1['Dex Mod'])/df1['PB']
    dfG = df1[['CR','Initiative ratio']].groupby(['CR']).mean().reset_index()
    fig.add_trace(go.Scatter(
        x=dfG['CR'], 
        y=dfG['Initiative ratio'],
        mode='markers+lines', 
        name=name,
        marker_color=group['color'],
        marker_symbol=group['symbol'],
        line_color=group['line_color'],
        hovertemplate = f'<b>{name}</b><br>'
            + 'CR %{x:.0f}<br>'
            + 'Proficiency %{y:.2f}'
            + '<extra></extra>'
    ))

# show figure
fig.update_layout(width=600, height=450)
fig.show(config=tfb.FIG_CONFIG)

# save figures
if SAVEFIGS:
    fig.update_layout(autosize=True, width=None, height=None)
    tfb.save_fig_html(fig, format='large', name=f'./fig-initiative-proficiency-vs-cr-large')
    tfb.save_fig_html(fig, format='small', name=f'./fig-initiative-proficiency-vs-cr-small')

# Tables

In [ ]:
# Tab. 1: create baseline table
import numpy as np
from scipy import optimize
import pandas as pd
from pprint import pprint
import sys
sys.path.append('../../assets/python/')
import estats5e as e5e

def average_save_bonus(row, **kwargs):
    saves = kwargs.get('saves', ['Str Save','Dex Save','Con Save','Int Save','Wis Save','Cha Save'])
    ave = np.mean([row[s] for s in saves])
    return ave

def count_save_proficiencies(row):
    return row['Str Prof'] + row['Dex Prof'] + row['Con Prof'] + row['Int Prof'] + row['Wis Prof'] + row['Cha Prof']

def unadjusted_armor_class(row):
    ac = row['adj AC']
    ac -= 2 if 'magic resistance' in row['AC adjustments'] else 0
    match count_save_proficiencies(row):
        case 3:
            ac -= 2
        case 4:
            ac -= 2
        case 5:
            ac -= 4
        case 6:
            ac -= 4
        case _:
            ac += 0
    return ac

def piecewise_linear(x, x0, y0, k1, k2):
    #return np.piecewise(x, [x < x0], [lambda x:k1*x + y0-k1*x0, lambda x:k2*x + y0-k2*x0])
    return np.piecewise(x, [x < 20], [lambda x:k1*x + y0-k1*20, lambda x:k2*x + y0-k2*20])

def fit_to_piecewise_linear(x, y, **kwargs):
    p, e = optimize.curve_fit(piecewise_linear, x, y)
    xp = kwargs.get('xp', np.linspace(1,30,30))
    return piecewise_linear(xp, *p)

def fit_to_linear(x, y):
    coefs = np.polyfit(x, y, 1)
    poly = np.poly1d(coefs)
    return poly(np.linspace(1,30,30))

# get monster data
dfM = pd.read_csv('../../assets/data/monsters-2014.csv')
dfM = dfM[['CR','adj HP','AC','adj AC','adj DPR','adj AB','adj SB']].groupby(['CR']).mean().reset_index()
dfM = dfM[dfM['CR'].between(1, 30)]
dfM.sort_values(by='CR', inplace=True)

xp = np.linspace(1,30,30).tolist()
xpm = [0.5] + [(xp[i] + xp[i+1])/2 for i in range(len(xp)-1)] + [30.5]
dpr = list(fit_to_piecewise_linear(dfM['CR'].to_numpy(), dfM['adj DPR'].to_numpy(), xp=np.array(xpm)))
dpr_range = [f'{np.ceil(dpr[i]):.0f} - {np.ceil(dpr[i+1])-1:.0f}' for i in range(len(xp))]

dpr = list(fit_to_piecewise_linear(dfM['CR'].to_numpy(), 1.25*dfM['adj DPR'].to_numpy(), xp=np.array(xpm)))
legendary_dpr_range = [f'{np.ceil(dpr[i]):.0f} - {np.ceil(dpr[i+1])-1:.0f}' for i in range(len(xp))]

hp = list(fit_to_piecewise_linear(dfM['CR'].to_numpy(), dfM['adj HP'].to_numpy(), xp=np.array(xpm)))
hp_range = [f'{np.ceil(hp[i]):.0f} - {np.ceil(hp[i+1])-1:.0f}' for i in range(len(xp))]

n_round = 0
fit = {
    'CR':  list(range(1,31)),
    'Attack Bonus':  list(fit_to_linear(dfM['CR'].to_numpy(), dfM['adj AB'].to_numpy()).round(n_round)),
    'Armor Class':  list(fit_to_linear(dfM['CR'].to_numpy(), dfM['adj AC'].to_numpy()).round(n_round)),
    'Save DC':  list(fit_to_linear(dfM['CR'].to_numpy(), dfM['adj AB'].to_numpy()+8).round(n_round)),
    'DPR Mean': list(fit_to_piecewise_linear(dfM['CR'].to_numpy(), dfM['adj DPR'].to_numpy())),
    'Damage / Round': dpr_range,
    'Legendary Damage / Round': legendary_dpr_range,
    'HP Mean':  list(fit_to_piecewise_linear(dfM['CR'].to_numpy(), dfM['adj HP'].to_numpy())),
    'Hit Points': hp_range,
    'Save Bonus':  list(fit_to_piecewise_linear(dfM['CR'].to_numpy(), dfM['adj SB'].to_numpy()).round(n_round)),
}

dfB = pd.DataFrame(fit)
dfB = dfB[['CR','Armor Class','Save Bonus','Hit Points','Attack Bonus','Save DC','Damage / Round','Legendary Damage / Round']]
dfB = dfB.style.format({
    'CR': '{:,.0f}',
    'Attack Bonus': '{:+,.0f}',
    'Armor Class': '{:,.0f}',
    'Save DC': '{:,.0f}',
    #'DPR Mean': '{:,.0f}',
    #'HP Mean': '{:,.0f}',
    'Save Bonus': '{:+,.0f}',
}).hide().set_table_styles([
        {'selector': 'th', 'props': 'text-align: center;'},
        {'selector': 'td', 'props': 'text-align: center;;'},
    ], overwrite=False)
dfB.to_html(
    './tab-monster-baseline-stats.html',
    index=False, classes='wide', border=0)
dfB

/var/folders/k4/phz5f3ss2_91t6j4s71jmp540000gn/T/ipykernel_73401/710304080.py:39: OptimizeWarning: Covariance of the parameters could not be estimated
  p, e = optimize.curve_fit(piecewise_linear, x, y)

# Unused Plots

In [295]:
column = 'adj AB Delta'
groups = [
    {
        'name': '2014 - normal',
        'Book': 'MM (2014)',
        'Legendary': ['N'],
        'color': COLORS[0], #'rgba(0,0,250,1)',
        'line_color': COLORS[0], #'rgba(0,0,250,1)',
        'symbol': 'circle',
    },
    {
        'name': '2014 - legendary',
        'Book': 'MM (2014)',
        'Legendary': ['L','LL'],
        'color': COLORS[0],
        'line_color': COLORS[0], #'rgba(0,0,250,1)',
        'symbol': 'square',
    },
    {
        'name': '2024 - normal',
        'Book': 'MM (2024)',
        'Legendary': ['N'],
        'color': COLORS[1], #'rgba(250,0,0,1)',
        'line_color': COLORS[1], #'rgba(250,0,0,1)',
        'symbol': 'circle',
    },
    {
        'name': '2024 - legendary',
        'Book': 'MM (2024)',
        'Legendary': ['L','LL'],
        'color': COLORS[1],
        'line_color': COLORS[1], #'rgba(250,0,0,1)',
        'symbol': 'square',
    }
]

# create figure
fig = go.Figure(
    layout=go.Layout(
        template=tfb.FIG_TEMPLATE,
        xaxis=dict(
            #title_text='encounter type',
            autorange=True,
            
        ),
        yaxis=dict(
            title_text=f'{column}',
            autorange=True,
            #range=[0, 2.5],
            #tick0=0, dtick=0.5,
            #minor=dict(tick0=0, dtick=0.1),
        ),
    )
)

for group in groups:
    book = group['Book']
    name = group['name']
    df1 = df0[df0['Book'].isin([book]) & df0['Legendary'].isin(group['Legendary'])]
    fig.add_trace(go.Box(
        y=df1[column],
        name=name,
        customdata=df1['Monster'],
        showlegend=False,
        boxpoints='all',
        jitter=0.4,
        whiskerwidth=0.4,
        marker_size=2,
        marker_symbol=group['symbol'],
        marker_color=group['color'],
        marker_line_color=group['line_color'],
        marker_line_width=2,
        hoveron='points',
        hovertemplate=f'<b>{name}</b><br>'+
            '%{customdata}<br>'+
            column + ' %{y:.2f}<br>'+
            '<extra></extra>'
    ))

# show figure
fig.update_layout(width=600, height=450)
fig.show(config=tfb.FIG_CONFIG)

# save figures
if SAVEFIGS:
    #fig.update_layout(autosize=True, width=None, height=None)
    #tfb.save_fig_html(fig, format='large', name=f'./fig-xp-ratio-vs-cr-large')
    #tfb.save_fig_html(fig, format='small', name=f'./fig-xp-ratio-vs-cr-small')
    pass

In [54]:
xColumn = 'adj AB Delta'; xjitter = 0.1
yColumn = 'adj DPR Ratio'; yjitter = 0.01
groups = [
    {
        'name': 'MM 2014 - normal',
        'Book': 'MM (2014)',
        'Legendary': ['N'],
        'CR_range': [2,30],
        'color': COLORS[0], 
        'line_color': COLORS[0], 
        'symbol': 'circle',
    },
    {
        'name': 'MM 2024 - normal',
        'Book': 'MM (2024)',
        'Legendary': ['N'],
        'CR_range': [2,30],
        'color': COLORS[1],
        'line_color': COLORS[1],
        'symbol': 'circle',
    },
]

# create figure
fig = go.Figure()

# plot monster data
for group in groups:
    name = group['name']
    book = group['Book']
    df1 = df0[df0['Book'].isin([book]) 
              & df0['Legendary'].isin(group['Legendary'])
              & df0['CR'].between(*group['CR_range'])]
    
    slope, intercept, r_value, p_value, std_err = scipy.stats.linregress(df1[xColumn], df1[yColumn])

    fig.add_trace(go.Scatter(
        x=tfb.jitter(df1[xColumn], xjitter), 
        y=tfb.jitter(df1[yColumn], yjitter),
        mode='markers',
        name=f'{name}; y = {slope:.3f}x + {intercept:.2f}',
        legendgroup=name,
        showlegend=False,
        marker_size=4,
        marker_symbol=group['symbol'],
        marker_color=group['color'],
        marker_line_color=group['line_color'],
        marker_line_width=0,
        customdata=np.stack((df1['Monster'], df1['CR']), axis=-1),
        hovertemplate = '<b>%{customdata[0]}' + f' - {name}</b><br>'
            + 'CR %{customdata[1]}<br>'
            + 'AB Delta %{x:.0f}<br>'
            + 'AC Delta %{y:.0f}'
            + '<extra></extra>'
    ))

    
    x = df1[xColumn]
    x = np.linspace(min(x), max(x), 100)
    fig.add_trace(go.Scatter(
        x=x, 
        y=x*slope + intercept,
        mode='lines',
        name=f'{name}; y = {slope:.3f}x + {intercept:.2f}',
        legendgroup=name,
        showlegend=True,
        line_color=group['color'],
        hoverinfo='skip',
        customdata=np.stack((df1['Monster'], df1['CR']), axis=-1),
    ))
    print(f'{name} fit: {slope:.3f}x + {intercept:.2f}; r-squared = {r_value**2:.3f}; p-value = {p_value:.3e}')


# show figure
fig.update_layout(
template=tfb.FIG_TEMPLATE,
    margin=dict(l=70, r=25, b=70, t=20, pad=4),
    xaxis=dict(
        title_text=xColumn,
        tickmode='auto',
        range=[-3,6],
    ),
    yaxis=dict(
        title_text=yColumn,
        tickmode='auto',
        range=[0,2],
        tickformat='.1f',
    ),
    legend=dict(
        xanchor='right', yanchor='top',
        x=1.00, y=1.00,
        orientation='v',
        tracegroupgap=0,
    ),
    width=600, 
    height=450,
)
fig.show(config=tfb.FIG_CONFIG)

# save figures
if SAVEFIGS:
    #fig.update_layout(autosize=True, width=None, height=None)
    #tfb.save_fig_html(fig, format='large', name=f'./fig-xp-ratio-vs-cr-large')
    #tfb.save_fig_html(fig, format='small', name=f'./fig-xp-ratio-vs-cr-small')
    pass

MM 2014 - normal fit: -0.033x + 0.89; r-squared = 0.035; p-value = 4.335e-03
MM 2024 - normal fit: -0.034x + 1.00; r-squared = 0.049; p-value = 1.879e-04

In [ ]:
xColumn = 'adj AC Delta'; xjitter = 0.1
yColumn = 'adj HP Ratio'; yjitter = 0.01
groups = [
    {
        'name': 'MM 2014 - normal',
        'Book': 'MM (2014)',
        'Legendary': ['N'],
        'CR_range': [1,30],
        'color': COLORS[0], 
        'line_color': COLORS[0], 
        'symbol': 'circle',
    },
    {
        'name': 'MM 2024 - normal',
        'Book': 'MM (2024)',
        'Legendary': ['N'],
        'CR_range': [1,30],
        'color': COLORS[1],
        'line_color': COLORS[1],
        'symbol': 'circle',
    },
]

# create figure
fig = go.Figure()

# plot monster data
for group in groups:
    name = group['name']
    book = group['Book']
    df1 = df0[df0['Book'].isin([book]) 
              & df0['Legendary'].isin(group['Legendary'])
              & df0['CR'].between(*group['CR_range'])]
    
    slope, intercept, r_value, p_value, std_err = scipy.stats.linregress(df1[xColumn], df1[yColumn])

    fig.add_trace(go.Scatter(
        x=tfb.jitter(df1[xColumn], xjitter), 
        y=tfb.jitter(df1[yColumn], yjitter),
        mode='markers',
        name=f'{name}; y = {slope:.3f}x + {intercept:.2f}',
        legendgroup=name,
        showlegend=False,
        marker_size=4,
        marker_symbol=group['symbol'],
        marker_color=group['color'],
        marker_line_color=group['line_color'],
        marker_line_width=0,
        customdata=np.stack((df1['Monster'], df1['CR']), axis=-1),
        hovertemplate = '<b>%{customdata[0]}' + f' - {name}</b><br>'
            + 'CR %{customdata[1]}<br>'
            + 'AB Delta %{x:.0f}<br>'
            + 'AC Delta %{y:.0f}'
            + '<extra></extra>'
    ))

    
    x = df1[xColumn]
    x = np.linspace(min(x), max(x), 100)
    fig.add_trace(go.Scatter(
        x=x, 
        y=x*slope + intercept,
        mode='lines',
        name=f'{name}; y = {slope:.3f}x + {intercept:.2f}',
        legendgroup=name,
        showlegend=True,
        line_color=group['color'],
        hoverinfo='skip',
        customdata=np.stack((df1['Monster'], df1['CR']), axis=-1),
    ))
    print(f'{name} fit: {slope:.3f}x + {intercept:.2f}; r-squared = {r_value**2:.3f}; p-value = {p_value:.3e}')


# show figure
fig.update_layout(
template=tfb.FIG_TEMPLATE,
    margin=dict(l=70, r=25, b=70, t=20, pad=4),
    xaxis=dict(
        title_text=xColumn,
        tickmode='auto',
        range=[-7,7],
    ),
    yaxis=dict(
        title_text=yColumn,
        tickmode='auto',
        range=[0,2],
        tickformat='.1f',
    ),
    legend=dict(
        xanchor='left', yanchor='bottom',
        x=0.00, y=0.00,
        orientation='v',
        tracegroupgap=0,
    ),
    width=600, 
    height=450,
)
fig.show(config=tfb.FIG_CONFIG)

# save figures
if SAVEFIGS:
    #fig.update_layout(autosize=True, width=None, height=None)
    #tfb.save_fig_html(fig, format='large', name=f'./fig-xp-ratio-vs-cr-large')
    #tfb.save_fig_html(fig, format='small', name=f'./fig-xp-ratio-vs-cr-small')
    pass

MM 2014 - normal fit: -0.054x + 1.07; r-squared = 0.114; p-value = 1.835e-08
MM 2024 - normal fit: -0.028x + 1.04; r-squared = 0.087; p-value = 6.340e-08

In [12]:
import numpy as np
import scipy

def confidence_ellipse(x, y, p=0.95, size=100):
    """
    Get the covariance confidence ellipse of *x* and *y*.
    Parameters
    ----------
    x, y : array-like, shape (n, )
        Input data.
    n_std : float
        The number of standard deviations to determine the ellipse's radiuses.
    size : int
        Number of points defining the ellipse
    Returns
    -------
    String containing an SVG path for the ellipse
    
    References (H/T)
    ----------------
    https://matplotlib.org/3.1.1/gallery/statistics/confidence_ellipse.html
    https://community.plotly.com/t/arc-shape-with-path/7205/5
    """
    if x.size != y.size:
        raise ValueError("x and y must be the same size")

    n_std = scipy.special.erfinv(p)*np.sqrt(2)

    cov = np.cov(x, y)
    pearson = cov[0, 1]/np.sqrt(cov[0, 0] * cov[1, 1])
    # Using a special case to obtain the eigenvalues of this
    # two-dimensionl dataset.
    ell_radius_x = np.sqrt(1 + pearson)
    ell_radius_y = np.sqrt(1 - pearson)
    theta = np.linspace(0, 2 * np.pi, size)
    ellipse_coords = np.column_stack([ell_radius_x * np.cos(theta), ell_radius_y * np.sin(theta)])
    
    # Calculating the stdandard deviation of x from
    # the squareroot of the variance and multiplying
    # with the given number of standard deviations.
    x_scale = np.sqrt(cov[0, 0]) * n_std
    x_mean = np.mean(x)

    # calculating the stdandard deviation of y ...
    y_scale = np.sqrt(cov[1, 1]) * n_std
    y_mean = np.mean(y)
  
    translation_matrix = np.tile([x_mean, y_mean], (ellipse_coords.shape[0], 1))
    rotation_matrix = np.array([[np.cos(np.pi / 4), np.sin(np.pi / 4)],
                                [-np.sin(np.pi / 4), np.cos(np.pi / 4)]])
    scale_matrix = np.array([[x_scale, 0],
                            [0, y_scale]])
    ellipse_coords = ellipse_coords.dot(rotation_matrix).dot(scale_matrix) + translation_matrix
        
    path = f'M {ellipse_coords[0, 0]}, {ellipse_coords[0, 1]}'
    for k in range(1, len(ellipse_coords)):
        path += f'L{ellipse_coords[k, 0]}, {ellipse_coords[k, 1]}'
    path += ' Z'
    return path

In [32]:
xjitter = 0.1
yjitter = 0.01
groups = [
    {
        'name': 'MM 2014 - normal',
        'Book': 'MM (2014)',
        'Legendary': ['N'],
        'CR_range': [1,30],
        'color': COLORS[0], 
        'line_color': COLORS[0], 
        'symbol': 'circle',
    },
    {
        'name': 'MM 2024 - normal',
        'Book': 'MM (2024)',
        'Legendary': ['N'],
        'CR_range': [1,30],
        'color': COLORS[1],
        'line_color': COLORS[1],
        'symbol': 'circle',
    },
]

# create figure
fig = go.Figure()

# plot monster data
for group in groups:
    name = group['name']
    book = group['Book']
    df1 = df0[df0['Book'].isin([book]) 
              & df0['Legendary'].isin(group['Legendary'])
              & df0['CR'].between(*group['CR_range'])]
    
    df1 = df1[(df1['D-CR Base'] != df1['D-CR']) | (df1['O-CR Base'] != df1['O-CR'])]
    #df1 = df1[(df1['D-CR Base'] == df1['D-CR']) & (df1['O-CR Base'] == df1['O-CR'])]
    #df1 = df1[df1['O-CR Base'] != df1['O-CR']]

    x = df1['D-CR AC Delta'] + df1['O-CR AB Delta']
    y = df1['adj HP Ratio']*df1['adj DPR Ratio']
    slope, intercept, r_value, p_value, std_err = scipy.stats.linregress(x, y)

    fig.add_trace(go.Scatter(
        x=tfb.jitter(x, xjitter), 
        y=tfb.jitter(y, yjitter),
        mode='markers',
        name=f'{name}; y = {slope:.3f}x + {intercept:.2f}',
        legendgroup=name,
        showlegend=False,
        marker_size=4,
        marker_symbol=group['symbol'],
        marker_color=group['color'],
        marker_line_color=group['line_color'],
        marker_line_width=0,
        customdata=np.stack((df1['Monster'], df1['CR']), axis=-1),
        hovertemplate = '<b>%{customdata[0]}' + f' - {name}</b><br>'
            + 'CR %{customdata[1]}<br>'
            + 'AB Delta %{x:.0f}<br>'
            + 'AC Delta %{y:.0f}'
            + '<extra></extra>'
    ))

    
    xt = np.linspace(min(x), max(x), 100)
    fig.add_trace(go.Scatter(
        x=xt, 
        y=xt*slope + intercept,
        mode='lines',
        name=f'{name}; y = {slope:.3f}x + {intercept:.2f}',
        legendgroup=name,
        showlegend=True,
        line_color=group['color'],
        hoverinfo='skip',
        customdata=np.stack((df1['Monster'], df1['CR']), axis=-1),
    ))
    print(f'{name} fit: {slope:.3f}x + {intercept:.2f}; r-squared = {r_value**2:.3f}; p-value = {p_value:.3e}')

    fig.add_shape(type='path',
                  path=confidence_ellipse(x, y, p=0.9),
                  line={'dash': 'dot'},
                  line_color=group['color'])


# show figure
fig.update_layout(
template=tfb.FIG_TEMPLATE,
    margin=dict(l=70, r=25, b=70, t=20, pad=4),
    xaxis=dict(
        title_text='AC + AB Delta',
        tickmode='auto',
        range=[-6,12],
    ),
    yaxis=dict(
        title_text='HP x DPR Ratio',
        tickmode='auto',
        range=[0,2],
        tickformat='.1f',
    ),
    legend=dict(
        xanchor='left', yanchor='bottom',
        x=0.00, y=0.00,
        orientation='v',
        tracegroupgap=0,
    ),
    width=600, 
    height=450,
)
fig.show(config=tfb.FIG_CONFIG)

# save figures
if SAVEFIGS:
    #fig.update_layout(autosize=True, width=None, height=None)
    #tfb.save_fig_html(fig, format='large', name=f'./fig-xp-ratio-vs-cr-large')
    #tfb.save_fig_html(fig, format='small', name=f'./fig-xp-ratio-vs-cr-small')
    pass

MM 2014 - normal fit: -0.057x + 1.00; r-squared = 0.401; p-value = 6.976e-19
MM 2024 - normal fit: -0.038x + 1.05; r-squared = 0.285; p-value = 3.436e-15

In [18]:
xjitter = 0.1
yjitter = 0.1
groups = [
    {
        'name': 'MM 2014 - normal',
        'Book': 'MM (2014)',
        'Legendary': ['N'],
        'CR_range': [1,30],
        'color': COLORS[0], 
        'line_color': COLORS[0], 
        'symbol': 'circle',
    },
    {
        'name': 'MM 2024 - normal',
        'Book': 'MM (2024)',
        'Legendary': ['N'],
        'CR_range': [1,30],
        'color': COLORS[1],
        'line_color': COLORS[1],
        'symbol': 'circle',
    },
]

# create figure
fig = go.Figure()

# plot monster data
for group in groups:
    name = group['name']
    book = group['Book']
    df1 = df0[df0['Book'].isin([book]) 
              & df0['Legendary'].isin(group['Legendary'])
              & df0['CR'].between(*group['CR_range'])]
    
    
    x = df1['CR']
    y = df1['eAC Delta'] + df1['adj AB Delta']
    g1 = sum((y < 4) & (y > -4))
    g2 = len(y) - g1
    print(name, g1, g2)
    g1 = sum((y < 2) & (y > -2))
    g2 = len(y) - g1
    print(name, g1, g2)
    #slope, intercept, r_value, p_value, std_err = scipy.stats.linregress(x, y)

    fig.add_trace(go.Scatter(
        x=tfb.jitter(x, xjitter), 
        y=tfb.jitter(y, yjitter),
        mode='markers',
        name=f'{name}; y = {slope:.3f}x + {intercept:.2f}',
        legendgroup=name,
        showlegend=False,
        marker_size=4,
        marker_symbol=group['symbol'],
        marker_color=group['color'],
        marker_line_color=group['line_color'],
        marker_line_width=0,
        customdata=np.stack((df1['Monster'], df1['CR']), axis=-1),
        hovertemplate = '<b>%{customdata[0]}' + f' - {name}</b><br>'
            + 'CR %{customdata[1]}<br>'
            + 'AB Delta %{x:.0f}<br>'
            + 'AC Delta %{y:.0f}'
            + '<extra></extra>'
    ))

    """
    xt = np.linspace(min(x), max(x), 100)
    fig.add_trace(go.Scatter(
        x=xt, 
        y=xt*slope + intercept,
        mode='lines',
        name=f'{name}; y = {slope:.3f}x + {intercept:.2f}',
        legendgroup=name,
        showlegend=True,
        line_color=group['color'],
        hoverinfo='skip',
        customdata=np.stack((df1['Monster'], df1['CR']), axis=-1),
    ))
    print(f'{name} fit: {slope:.3f}x + {intercept:.2f}; r-squared = {r_value**2:.3f}; p-value = {p_value:.3e}')

    fig.add_shape(type='path',
                  path=confidence_ellipse(x, y, p=0.9),
                  line={'dash': 'dot'},
                  line_color=group['color'])"""

fig.add_trace(go.Scatter(
    x=[1,30], 
    y=[4,4],
    mode='lines',
    line_color='black',
    line_dash='dash',
    hoverinfo='skip',
    showlegend=False,
))


fig.add_trace(go.Scatter(
    x=[1,30],
    y=[-4,-4],
    mode='lines',
    line_color='black',
    line_dash='dash',
    hoverinfo='skip',
    showlegend=False,
))

# show figure
fig.update_layout(
template=tfb.FIG_TEMPLATE,
    margin=dict(l=70, r=25, b=70, t=20, pad=4),
    xaxis=dict(
        title_text='challenge rating',
        autorange=True,
        tickmode='auto',
        range=[0,31],
    ),
    yaxis=dict(
        title_text='AC + AB Delta',
        autorange=True,
        #tickmode='auto',
        range=[-7,7],
        tickformat='.0f',
        tick0=0, dtick=4,
    ),
    legend=dict(
        xanchor='left', yanchor='bottom',
        x=0.00, y=0.00,
        orientation='v',
        tracegroupgap=0,
    ),
    width=600, 
    height=450,
)
fig.show(config=tfb.FIG_CONFIG)

# save figures
if SAVEFIGS:
    #fig.update_layout(autosize=True, width=None, height=None)
    #tfb.save_fig_html(fig, format='large', name=f'./fig-xp-ratio-vs-cr-large')
    #tfb.save_fig_html(fig, format='small', name=f'./fig-xp-ratio-vs-cr-small')
    pass

MM 2014 - normal 238 27
MM 2014 - normal 172 93
MM 2024 - normal 278 46
MM 2024 - normal 203 121

In [296]:
column = 'adj DPR Ratio'
groups = [
    {
        'name': '2014 - normal',
        'Book': 'MM (2014)',
        'Legendary': ['N'],
        'color': COLORS[0], #'rgba(0,0,250,1)',
        'line_color': COLORS[0], #'rgba(0,0,250,1)',
        'symbol': 'circle',
    },
    {
        'name': '2014 - legendary',
        'Book': 'MM (2014)',
        'Legendary': ['L','LL'],
        'color': COLORS[0],
        'line_color': COLORS[0], #'rgba(0,0,250,1)',
        'symbol': 'square',
    },
    {
        'name': '2024 - normal',
        'Book': 'MM (2024)',
        'Legendary': ['N'],
        'color': COLORS[1], #'rgba(250,0,0,1)',
        'line_color': COLORS[1], #'rgba(250,0,0,1)',
        'symbol': 'circle',
    },
    {
        'name': '2024 - legendary',
        'Book': 'MM (2024)',
        'Legendary': ['L','LL'],
        'color': COLORS[1],
        'line_color': COLORS[1], #'rgba(250,0,0,1)',
        'symbol': 'square',
    }
]

# create figure
fig = go.Figure(
    layout=go.Layout(
        template=tfb.FIG_TEMPLATE,
        xaxis=dict(
            #title_text='encounter type',
            autorange=True,
            
        ),
        yaxis=dict(
            title_text=f'{column}',
            range=[0, 2],
            tick0=0, dtick=0.5,
            minor=dict(tick0=0, dtick=0.1),
        ),
    )
)

for group in groups:
    book = group['Book']
    name = group['name']
    df1 = df0[df0['Book'].isin([book]) & df0['Legendary'].isin(group['Legendary'])]
    fig.add_trace(go.Box(
        y=df1[column],
        name=name,
        customdata=df1['Monster'],
        showlegend=False,
        boxpoints='all',
        jitter=0.4,
        whiskerwidth=0.4,
        marker_size=2,
        marker_symbol=group['symbol'],
        marker_color=group['color'],
        marker_line_color=group['line_color'],
        marker_line_width=2,
        hoveron='points',
        hovertemplate=f'<b>{name}</b><br>'+
            '%{customdata}<br>'+
            column + ' %{y:.2f}<br>'+
            '<extra></extra>'
    ))

# show figure
fig.update_layout(width=600, height=450)
fig.show(config=tfb.FIG_CONFIG)

# save figures
if SAVEFIGS:
    #fig.update_layout(autosize=True, width=None, height=None)
    #tfb.save_fig_html(fig, format='large', name=f'./fig-xp-ratio-vs-cr-large')
    #tfb.save_fig_html(fig, format='small', name=f'./fig-xp-ratio-vs-cr-small')
    pass

In [297]:
column = 'HP'

# create figure
fig = go.Figure(
    layout=go.Layout(
        template=tfb.FIG_TEMPLATE,
        margin=dict(l=70, r=25, b=55, t=20, pad=4),
        xaxis=dict(
            title_text='CR',
            range=[0,31],
            tick0=0, dtick=5,
            minor=dict(tick0=0, dtick=1),
        ),
        yaxis=dict(
            title_text=f'{column}',
            #range=[0,3],
            tick0=0, dtick=200,
            minor=dict(tick0=0, dtick=100),
        ),
        legend=dict(
            xanchor='left', yanchor='top',
            x=0.00, y=1.00,
            orientation='v',
            tracegroupgap=0,
        )
    )
)

# plot monster data
book = 'MM (2014)'
df1 = df0[df0['Book'].isin([book])]
dfG = df1[['CR',column]].groupby(['CR']).mean().reset_index()
fig.add_trace(go.Scatter(
    x=dfG['CR'], 
    y=dfG[column],
    mode='markers+lines', 
    name=f'{book}',
    hovertemplate = f'<b>{book}</b><br>'
        + 'CR %{x:.0f}<br>'
        + column +' %{y:.1f}'
        + '<extra></extra>'
))

# plot monster data
book = 'MM (2024)'
df1 = df0[df0['Book'].isin([book])]
dfG = df1[['CR',column]].groupby(['CR']).mean().reset_index()
fig.add_trace(go.Scatter(
    x=dfG['CR'], 
    y=dfG[column],
    mode='markers+lines', 
    name=f'{book}',
    hovertemplate = f'<b>{book}</b><br>'
        + 'CR %{x:.0f}<br>'
        + column +' %{y:.1f}'
        + '<extra></extra>'
))

fig.add_trace(go.Scatter(
    x=dfT['CR'], 
    y=dfT[column],
    mode='lines', 
    name=f'baseline',
    line_color='black',
    line_dash='dash',
    hovertemplate = f'<b>{book}</b><br>'
        + 'CR %{x:.0f}<br>'
        + 'DPR %{y:.1f}'
        + '<extra></extra>'
))

# show figure
fig.update_layout(width=600, height=450)
fig.show(config=tfb.FIG_CONFIG)

# save figures
if SAVEFIGS:
    #fig.update_layout(autosize=True, width=None, height=None)
    #tfb.save_fig_html(fig, format='large', name=f'./fig-xp-ratio-vs-cr-large')
    #tfb.save_fig_html(fig, format='small', name=f'./fig-xp-ratio-vs-cr-small')
    pass

In [298]:
column = 'AC'

# create figure
fig = go.Figure(
    layout=go.Layout(
        template=tfb.FIG_TEMPLATE,
        margin=dict(l=70, r=25, b=55, t=20, pad=4),
        xaxis=dict(
            title_text='CR',
            range=[0,31],
            tick0=0, dtick=5,
            minor=dict(tick0=0, dtick=1),
        ),
        yaxis=dict(
            title_text=f'{column}',
            #range=[0,3],
            tick0=0, dtick=2,
            minor=dict(tick0=0, dtick=1),
        ),
        legend=dict(
            xanchor='left', yanchor='top',
            x=0.00, y=1.00,
            orientation='v',
            tracegroupgap=0,
        )
    )
)

# plot monster data
book = 'MM (2014)'
df1 = df0[df0['Book'].isin([book])]
dfG = df1[['CR',column]].groupby(['CR']).mean().reset_index()
fig.add_trace(go.Scatter(
    x=dfG['CR'], 
    y=dfG[column],
    mode='markers+lines', 
    name=f'{book}',
    hovertemplate = f'<b>{book}</b><br>'
        + 'CR %{x:.0f}<br>'
        + column +' %{y:.1f}'
        + '<extra></extra>'
))

# plot monster data
book = 'MM (2024)'
df1 = df0[df0['Book'].isin([book])]
dfG = df1[['CR',column]].groupby(['CR']).mean().reset_index()
fig.add_trace(go.Scatter(
    x=dfG['CR'], 
    y=dfG[column],
    mode='markers+lines', 
    name=f'{book}',
    hovertemplate = f'<b>{book}</b><br>'
        + 'CR %{x:.0f}<br>'
        + column +' %{y:.1f}'
        + '<extra></extra>'
))

fig.add_trace(go.Scatter(
    x=dfT['CR'], 
    y=dfT[column],
    mode='lines', 
    name=f'baseline',
    line_color='black',
    line_dash='dash',
    hovertemplate = f'<b>{book}</b><br>'
        + 'CR %{x:.0f}<br>'
        + 'DPR %{y:.1f}'
        + '<extra></extra>'
))

# show figure
fig.update_layout(width=600, height=450)
fig.show(config=tfb.FIG_CONFIG)

# save figures
if SAVEFIGS:
    #fig.update_layout(autosize=True, width=None, height=None)
    #tfb.save_fig_html(fig, format='large', name=f'./fig-xp-ratio-vs-cr-large')
    #tfb.save_fig_html(fig, format='small', name=f'./fig-xp-ratio-vs-cr-small')
    pass

In [299]:
column = 'adj AC Delta'
groups = [
    {
        'name': '2014 - normal',
        'Book': 'MM (2014)',
        'Legendary': ['N'],
        'color': COLORS[0], #'rgba(0,0,250,1)',
        'line_color': COLORS[0], #'rgba(0,0,250,1)',
        'symbol': 'circle',
    },
    {
        'name': '2014 - legendary',
        'Book': 'MM (2014)',
        'Legendary': ['L','LL'],
        'color': COLORS[0],
        'line_color': COLORS[0], #'rgba(0,0,250,1)',
        'symbol': 'square',
    },
    {
        'name': '2024 - normal',
        'Book': 'MM (2024)',
        'Legendary': ['N'],
        'color': COLORS[1], #'rgba(250,0,0,1)',
        'line_color': COLORS[1], #'rgba(250,0,0,1)',
        'symbol': 'circle',
    },
    {
        'name': '2024 - legendary',
        'Book': 'MM (2024)',
        'Legendary': ['L','LL'],
        'color': COLORS[1],
        'line_color': COLORS[1], #'rgba(250,0,0,1)',
        'symbol': 'square',
    }
]

# create figure
fig = go.Figure(
    layout=go.Layout(
        template=tfb.FIG_TEMPLATE,
        xaxis=dict(
            #title_text='encounter type',
            autorange=True,
            
        ),
        yaxis=dict(
            title_text=f'{column}',
            autorange=True,
            #range=[0, 2.5],
            #tick0=0, dtick=0.5,
            #minor=dict(tick0=0, dtick=0.1),
        ),
    )
)

for group in groups:
    book = group['Book']
    name = group['name']
    df1 = df0[df0['Book'].isin([book]) & df0['Legendary'].isin(group['Legendary'])]
    fig.add_trace(go.Box(
        y=df1[column],
        name=name,
        customdata=df1['Monster'],
        showlegend=False,
        boxpoints='all',
        jitter=0.4,
        whiskerwidth=0.4,
        marker_size=2,
        marker_symbol=group['symbol'],
        marker_color=group['color'],
        marker_line_color=group['line_color'],
        marker_line_width=2,
        hoveron='points',
        hovertemplate=f'<b>{name}</b><br>'+
            '%{customdata}<br>'+
            column + ' %{y:.2f}<br>'+
            '<extra></extra>'
    ))

# show figure
fig.update_layout(width=600, height=450)
fig.show(config=tfb.FIG_CONFIG)

# save figures
if SAVEFIGS:
    #fig.update_layout(autosize=True, width=None, height=None)
    #tfb.save_fig_html(fig, format='large', name=f'./fig-xp-ratio-vs-cr-large')
    #tfb.save_fig_html(fig, format='small', name=f'./fig-xp-ratio-vs-cr-small')
    pass

In [ ]:
column = 'Save Proficiencies'

groups = [
    {
        'name': 'MM 2014',
        'Book': 'MM (2014)',
        'Legendary': ['N','L','LL'],
        'color': COLORS[0],
        'line_color': COLORS[0],
        'symbol': 'circle',
    },
    {
        'name': 'MM 2024',
        'Book': 'MM (2024)',
        'Legendary': ['N','L','LL'],
        'color': COLORS[1],
        'line_color': COLORS[1],
        'symbol': 'circle',
    },
]

# create figure
fig = go.Figure(
    layout=go.Layout(
        template=tfb.FIG_TEMPLATE,
        margin=dict(l=70, r=25, b=55, t=20, pad=4),
        xaxis=dict(
            title_text='challenge rating',
            range=[0,31],
            tick0=0, dtick=5,
            minor=dict(tick0=0, dtick=1),
        ),
        yaxis=dict(
            title_text='save proficiencies',
            range=[0,6],
            tick0=0, dtick=1,
            minor=dict(tick0=0, dtick=1),
            tickformat='.0f',
        ),
        legend=dict(
            xanchor='left', yanchor='top',
            x=0.00, y=1.00,
            orientation='v',
            tracegroupgap=0,
        )
    )
)

# plot monster data
for group in groups:
    name = group['name']
    book = group['Book']
    legendary = group['Legendary']
    df1 = df0[df0['Book'].isin([book]) & df0['Legendary'].isin(legendary)]
    dfG = df1[['CR',column]].groupby(['CR']).mean().reset_index()
    fig.add_trace(go.Scatter(
        x=dfG['CR'], 
        y=dfG[column],
        mode='markers+lines', 
        name=name,
        marker_color=group['color'],
        marker_symbol=group['symbol'],
        line_color=group['line_color'],
        hovertemplate = f'<b>{name}</b><br>'
            + 'CR %{x:.0f}<br>'
            + 'Proficiencies %{y:.1f}'
            + '<extra></extra>'
    ))

# show figure
fig.update_layout(width=600, height=450)
fig.show(config=tfb.FIG_CONFIG)

In [ ]:
column = 'Save Proficiencies'


# create figure
fig = go.Figure()

# plot monster data
colors = iter(COLORS)
for stat in ['Str','Dex','Con','Int','Wis','Cha']:
    column = f'{stat} Save Prof'
    color = next(colors)
    df1 = df0[df0['Book'].isin(['MM (2024)']) & df0['Legendary'].isin(['N','L','LL'])]
    dfG = df1[['CR',column]].groupby(['CR']).mean().reset_index()
    """fig.add_trace(go.Scatter(
        x=dfG['CR'], 
        y=dfG[column],
        mode='markers+lines', 
        name=stat,
        line_color=color,
        hovertemplate = f'<b>{stat}</b><br>'
            + 'CR %{x:.0f}<br>'
            + 'Proficient %{y:.1%}'
            + '<extra></extra>'
    ))"""
    tfb.plot_data_and_fit(
        fig, 
        x=dfG['CR'], 
        y=dfG[column],
        name=column,
        legendgroup=column,
        line=dict(color=color),
        print_coefficients=False,
        hovertemplate = f'<b>{stat}</b><br>'
            + 'CR %{x:.0f}<br>'
            + 'Proficient %{y:.1%}'
            + '<extra></extra>'
    )

# show figure
fig.update_layout(
    template=tfb.FIG_TEMPLATE,
    margin=dict(l=70, r=25, b=55, t=20, pad=4),
    xaxis=dict(
        title_text='challenge rating',
        range=[0,31],
        tick0=0, dtick=5,
        minor=dict(tick0=0, dtick=1),
    ),
    yaxis=dict(
        title_text='probability',
        range=[-0.02,1.02],
        tick0=0, dtick=0.2,
        minor=dict(tick0=0, dtick=0.05),
        tickformat='.0%',
    ),
    legend=dict(
        xanchor='left', yanchor='top',
        x=0.00, y=1.00,
        orientation='v',
        tracegroupgap=0,
    ),
    width=600, 
    height=450,
)
fig.show(config=tfb.FIG_CONFIG)

In [ ]:
# Number of monsters with different number of save proficiencies
# create figure
fig = go.Figure()

for book in ['MM (2014)','MM (2024)']:
    df1 = df0[df0['Book'].isin([book]) & df0['Legendary'].isin(['N','L','LL'])]
    dfG = df1[['Save Proficiencies','Monster']].groupby(['Save Proficiencies']).count().reset_index()

    fig.add_trace(go.Bar(
        x=dfG['Save Proficiencies'],
        y=dfG['Monster']/sum(dfG['Monster']),
        name=book,
        hovertemplate = f'{book}<br>'
            + '%{x:.0f} proficiencies<br>'
            + '%{y:,.0f} monsters'
            + '<extra></extra>'
    ))

# show figure
fig.update_layout(
    template=tfb.FIG_TEMPLATE,
    margin=dict(l=70, r=25, b=55, t=20, pad=4),
    #barmode='relative',
    xaxis=dict(title_text='saving throw proficiencies', range=[-0.5,6.5]),
    yaxis=dict(
        title_text='probability',
        tick0=0, dtick=0.2,
        minor=dict(tick0=0, dtick=0.05),
        tickformat='.0%',
    ),
    legend=dict(
        xanchor='right', yanchor='top',
        x=1.00, y=1.00,
        orientation='v',
        tracegroupgap=0,
        traceorder='normal',
    ),
    width=600, 
    height=450,
)
fig.show(config=tfb.FIG_CONFIG)

In [301]:
column = 'adj SB Delta'
groups = [
    {
        'name': '2014 - normal',
        'Book': 'MM (2014)',
        'Legendary': ['N'],
        'color': COLORS[0], #'rgba(0,0,250,1)',
        'line_color': COLORS[0], #'rgba(0,0,250,1)',
        'symbol': 'circle',
    },
    {
        'name': '2014 - legendary',
        'Book': 'MM (2014)',
        'Legendary': ['L','LL'],
        'color': COLORS[0],
        'line_color': COLORS[0], #'rgba(0,0,250,1)',
        'symbol': 'square',
    },
    {
        'name': '2024 - normal',
        'Book': 'MM (2024)',
        'Legendary': ['N'],
        'color': COLORS[1], #'rgba(250,0,0,1)',
        'line_color': COLORS[1], #'rgba(250,0,0,1)',
        'symbol': 'circle',
    },
    {
        'name': '2024 - legendary',
        'Book': 'MM (2024)',
        'Legendary': ['L','LL'],
        'color': COLORS[1],
        'line_color': COLORS[1], #'rgba(250,0,0,1)',
        'symbol': 'square',
    }
]

# create figure
fig = go.Figure(
    layout=go.Layout(
        template=tfb.FIG_TEMPLATE,
        xaxis=dict(
            #title_text='encounter type',
            autorange=True,
            
        ),
        yaxis=dict(
            title_text=f'{column}',
            autorange=True,
            #range=[0, 2.5],
            #tick0=0, dtick=0.5,
            #minor=dict(tick0=0, dtick=0.1),
        ),
    )
)

for group in groups:
    book = group['Book']
    name = group['name']
    df1 = df0[df0['Book'].isin([book]) & df0['Legendary'].isin(group['Legendary'])]
    fig.add_trace(go.Box(
        y=df1[column],
        name=name,
        customdata=df1['Monster'],
        showlegend=False,
        boxpoints='all',
        jitter=0.4,
        whiskerwidth=0.4,
        marker_size=2,
        marker_symbol=group['symbol'],
        marker_color=group['color'],
        marker_line_color=group['line_color'],
        marker_line_width=2,
        hoveron='points',
        hovertemplate=f'<b>{name}</b><br>'+
            '%{customdata}<br>'+
            column + ' %{y:.2f}<br>'+
            '<extra></extra>'
    ))

# show figure
fig.update_layout(width=600, height=450)
fig.show(config=tfb.FIG_CONFIG)

# save figures
if SAVEFIGS:
    #fig.update_layout(autosize=True, width=None, height=None)
    #tfb.save_fig_html(fig, format='large', name=f'./fig-xp-ratio-vs-cr-large')
    #tfb.save_fig_html(fig, format='small', name=f'./fig-xp-ratio-vs-cr-small')
    pass

In [302]:
column = 'adj HP Ratio'
groups = [
    {
        'name': '2014 - normal',
        'Book': 'MM (2014)',
        'Legendary': ['N'],
        'color': COLORS[0], #'rgba(0,0,250,1)',
        'line_color': COLORS[0], #'rgba(0,0,250,1)',
        'symbol': 'circle',
    },
    {
        'name': '2014 - legendary',
        'Book': 'MM (2014)',
        'Legendary': ['L','LL'],
        'color': COLORS[0],
        'line_color': COLORS[0], #'rgba(0,0,250,1)',
        'symbol': 'square',
    },
    {
        'name': '2024 - normal',
        'Book': 'MM (2024)',
        'Legendary': ['N'],
        'color': COLORS[1], #'rgba(250,0,0,1)',
        'line_color': COLORS[1], #'rgba(250,0,0,1)',
        'symbol': 'circle',
    },
    {
        'name': '2024 - legendary',
        'Book': 'MM (2024)',
        'Legendary': ['L','LL'],
        'color': COLORS[1],
        'line_color': COLORS[1], #'rgba(250,0,0,1)',
        'symbol': 'square',
    }
]

# create figure
fig = go.Figure(
    layout=go.Layout(
        template=tfb.FIG_TEMPLATE,
        xaxis=dict(
            #title_text='encounter type',
            autorange=True,
            
        ),
        yaxis=dict(
            title_text=f'{column}',
            range=[0, 2.5],
            tick0=0, dtick=0.5,
            minor=dict(tick0=0, dtick=0.1),
        ),
    )
)

for group in groups:
    book = group['Book']
    name = group['name']
    df1 = df0[df0['Book'].isin([book]) & df0['Legendary'].isin(group['Legendary'])]
    fig.add_trace(go.Box(
        y=df1[column],
        name=name,
        customdata=df1['Monster'],
        showlegend=False,
        boxpoints='all',
        jitter=0.4,
        whiskerwidth=0.4,
        marker_size=2,
        marker_symbol=group['symbol'],
        marker_color=group['color'],
        marker_line_color=group['line_color'],
        marker_line_width=2,
        hoveron='points',
        hovertemplate=f'<b>{name}</b><br>'+
            '%{customdata}<br>'+
            column + ' %{y:.2f}<br>'+
            '<extra></extra>'
    ))

# show figure
fig.update_layout(width=600, height=450)
fig.show(config=tfb.FIG_CONFIG)

# save figures
if SAVEFIGS:
    #fig.update_layout(autosize=True, width=None, height=None)
    #tfb.save_fig_html(fig, format='large', name=f'./fig-xp-ratio-vs-cr-large')
    #tfb.save_fig_html(fig, format='small', name=f'./fig-xp-ratio-vs-cr-small')
    pass

In [303]:
column = 'eXP Ratio'
groups = [
    {
        'Book': 'MM (2014)',
        'Legendary': ['N'],
        'color': COLORS[0], #'rgba(0,0,250,1)',
        'line_color': COLORS[0], #'rgba(0,0,250,1)',
        'symbol': 'circle',
    },
    {
        'Book': 'MM (2014)',
        'Legendary': ['L','LL'],
        'color': COLORS[0], #'rgba(0,0,250,0)',
        'line_color': COLORS[0], #'rgba(0,0,250,1)',
        'symbol': 'square',
    },
    {
        'Book': 'MM (2024)',
        'Legendary': ['N'],
        'color': COLORS[1], #'rgba(250,0,0,1)',
        'line_color': COLORS[1], #'rgba(250,0,0,1)',
        'symbol': 'circle',
    },
    {
        'Book': 'MM (2024)',
        'Legendary': ['L','LL'],
        'color': COLORS[1], #'rgba(250,0,0,0)',
        'line_color': COLORS[1], #'rgba(250,0,0,1)',
        'symbol': 'square',
    }
]

# create figure
fig = go.Figure(
    layout=go.Layout(
        template=tfb.FIG_TEMPLATE,
        margin=dict(l=70, r=25, b=55, t=20, pad=4),
        xaxis=dict(
            title_text='CR',
            range=[0,31],
            tick0=0, dtick=5,
            minor=dict(tick0=0, dtick=1),
        ),
        yaxis=dict(
            title_text=f'{column}',
            range=[0,2.5],
            tick0=0, dtick=0.5,
            minor=dict(tick0=0, dtick=0.1),
            tickformat='.1f',
        ),
        legend=dict(
            xanchor='right', yanchor='top',
            x=1.00, y=1.00,
            orientation='v',
            tracegroupgap=0,
        )
    )
)

# plot CR ranges
x = list(range(1, 30))
y_bounds = [
    {
        'x': x,
        'y0': [0.5*(monster_default_stats(cr-1)['XP'] + monster_default_stats(cr)['XP'])/monster_default_stats(cr)['XP'] for cr in x],
        'y1': [0.5*(monster_default_stats(cr+1)['XP'] + monster_default_stats(cr)['XP'])/monster_default_stats(cr)['XP'] for cr in x],
        'fillcolor': 'rgba(0,0,0,0.1)',
    },
    {
        'x': x,
        'y0': [0.5*(monster_default_stats(cr-2)['XP'] + monster_default_stats(cr-1)['XP'])/monster_default_stats(cr)['XP'] for cr in x],
        'y1': [0.5*(monster_default_stats(cr+2)['XP'] + monster_default_stats(cr+1)['XP'])/monster_default_stats(cr)['XP'] for cr in x],
        'fillcolor': 'rgba(0,0,0,0.1)',
    },
    {
        'x': x,
        'y0': [0.5*(monster_default_stats(cr-3)['XP'] + monster_default_stats(cr-2)['XP'])/monster_default_stats(cr)['XP'] for cr in x],
        'y1': [0.5*(monster_default_stats(cr+3)['XP'] + monster_default_stats(cr+2)['XP'])/monster_default_stats(cr)['XP'] for cr in x],
        'fillcolor': 'rgba(0,0,0,0.1)',
    },
]

for y_bound in y_bounds:
    fig.add_trace(go.Scatter(
        x=y_bound['x'], 
        y=y_bound['y0'],
        mode='lines', 
        showlegend=False,
        line_width=0,
        hoverinfo='skip',
    ))

    fig.add_trace(go.Scatter(
        x=y_bound['x'], 
        y=y_bound['y1'],
        mode='lines', 
        showlegend=False,
        fill='tonexty',
        fillcolor=y_bound['fillcolor'],
        line_width=0,
        hoverinfo='skip',
    ))

# plot monster data
for group in groups:
    book = group['Book']
    df1 = df0[df0['Book'].isin([book]) & df0['Legendary'].isin(group['Legendary'])]
    fig.add_trace(go.Scatter(
        x=df1['CR'], 
        y=df1[column],
        mode='markers',
        marker_symbol=group['symbol'],
        marker_color=group['color'],
        marker_line_color=group['line_color'],
        marker_line_width=0,
        name=f'{book}',
        customdata=np.stack((df1['Monster'], df1['CR']), axis=-1),
        hovertemplate = '<b>%{customdata[0]}' + f' - {book}</b><br>'
            + 'CR %{x}<br>'
            + 'eXP Ratio %{y:.3f}'
            + '<extra></extra>'
    ))

# show figure
fig.update_layout(width=600, height=450)
fig.show(config=tfb.FIG_CONFIG)

# save figures
if SAVEFIGS:
    #fig.update_layout(autosize=True, width=None, height=None)
    #tfb.save_fig_html(fig, format='large', name=f'./fig-xp-ratio-vs-cr-large')
    #tfb.save_fig_html(fig, format='small', name=f'./fig-xp-ratio-vs-cr-small')
    pass

In [14]:
# XP ratio for legendary monsters by monster type
column = 'eXP Ratio'

# create figure
fig = go.Figure(
    layout=go.Layout(
        template=tfb.FIG_TEMPLATE,
        margin=dict(l=60, r=40, b=90, t=20, pad=4),
        xaxis=dict(
            autorange=True,
            title_text='monster type',
            #tickmode='array',
            #tickvals=['MM 2014 - normal','MM 2014 - legendary','MM 2024 - normal','MM 2024 - legendary'],
            #ticktext=['normal','legendary','normal','legendary'],
        ),
        yaxis=dict(
            title_text=f'normalized XP',
            tickmode='auto',
            autorange=True,
            range=[0.0, 3.0],
            tickformat='.1f',
            #tick0=0, dtick=0.5,
            #minor=dict(tick0=0, dtick=0.1),
        ),
    )
)

#monster_types = list(df0['Type'].sort_values().unique())
monster_types = ['Aberration', 'Beast', 'Celestial', 'Construct', 'Dragon', 'Elemental', 'Fey', 'Fiend', 'Giant', 'Humanoid', 'Monstrosity', 'Ooze', 'Plant', 'Undead']

for mt in monster_types:
    book = 'MM (2024)'
    name = mt
    df1 = df0[df0['Book'].isin([book]) & df0['Legendary'].isin(['N']) & df0['Type'].eq(mt)]
    print(f"{name} - {column} = {np.median(df1[column]):.3f}")
    fig.add_trace(go.Box(
        y=df1[column],
        name=name,
        customdata=df1['Monster'],
        showlegend=False,
        #boxpoints='all',
        jitter=0.8,
        #whiskerwidth=0.4,
        #pointpos=0,
        #line_color = 'rgba(0,0,0,0)',
        #fillcolor = 'rgba(0,0,0,0)',
        #marker_size=2,
        #marker_symbol=group['symbol'],
        #marker_color=group['color'],
        #marker_line_color=group['line_color'],
        #marker_line_width=2,
        hoveron='points',
        hovertemplate=f'<b>{name}</b><br>'+
            '%{customdata}<br>'+
            'XP ratio %{y:.2f}<br>'+
            '<extra></extra>'
    ))

# show figure
fig.update_layout(width=600, height=450)
fig.show(config=tfb.FIG_CONFIG)

# save figures
if SAVEFIGS:
    pass
    #fig.update_layout(autosize=True, width=None, height=None)
    #tfb.save_fig_html(fig, format='large', name=f'./fig-xp-ratio-distribution-large')
    #fig.update_traces(marker_size=1)
    #tfb.save_fig_html(fig, format='small', name=f'./fig-xp-ratio-distribution-small')

Aberration - eXP Ratio = 0.923
Beast - eXP Ratio = 0.786
Celestial - eXP Ratio = 0.950
Construct - eXP Ratio = 0.912
Dragon - eXP Ratio = 1.069
Elemental - eXP Ratio = 1.034
Fey - eXP Ratio = 0.937
Fiend - eXP Ratio = 1.008
Giant - eXP Ratio = 1.165
Humanoid - eXP Ratio = 1.048
Monstrosity - eXP Ratio = 0.985
Ooze - eXP Ratio = 1.020
Plant - eXP Ratio = 0.691
Undead - eXP Ratio = 0.948

In [9]:
# XP ratio for legendary monsters by monster type
column = 'eXP Ratio'

# create figure
fig = go.Figure()

#monster_types = list(df0['Type'].sort_values().unique())
monster_types = ['Aberration', 'Beast', 'Celestial', 'Construct', 'Dragon', 'Elemental', 'Fey', 'Fiend', 'Giant', 'Humanoid', 'Monstrosity', 'Ooze', 'Plant', 'Undead']

for mt in monster_types:
    book = 'MM (2024)'
    name = mt
    df1 = df0[df0['Book'].isin([book]) & df0['Legendary'].isin(['L','LL']) & df0['Type'].eq(mt)]
    print(f"{name} - {column} = {np.mean(df1[column]):.3f}")
    fig.add_trace(go.Box(
        y=df1[column],
        name=name,
        customdata=df1['Monster'],
        showlegend=False,
        #boxpoints='all',
        jitter=0.8,
        #whiskerwidth=0.4,
        #pointpos=0,
        #line_color = 'rgba(0,0,0,0)',
        #fillcolor = 'rgba(0,0,0,0)',
        #marker_size=2,
        #marker_symbol=group['symbol'],
        #marker_color=group['color'],
        #marker_line_color=group['line_color'],
        #marker_line_width=2,
        hoveron='points',
        hovertemplate=f'<b>{name}</b><br>'+
            '%{customdata}<br>'+
            'XP ratio %{y:.2f}<br>'+
            '<extra></extra>'
    ))

# show figure
fig.update_layout(
    template=tfb.FIG_TEMPLATE,
    margin=dict(l=60, r=40, b=90, t=20, pad=4),
    xaxis=dict(
        autorange=True,
        title_text='monster type',
        #tickmode='array',
        #tickvals=['MM 2014 - normal','MM 2014 - legendary','MM 2024 - normal','MM 2024 - legendary'],
        #ticktext=['normal','legendary','normal','legendary'],
    ),
    yaxis=dict(
        title_text=f'normalized XP',
        tickmode='auto',
        range=[0.0, 3.0],
        tickformat='.1f',
        #tick0=0, dtick=0.5,
        #minor=dict(tick0=0, dtick=0.1),
    ),
    width=600, 
    height=450,
)
fig.show(config=tfb.FIG_CONFIG)

# save figures
if SAVEFIGS:
    pass
    #fig.update_layout(autosize=True, width=None, height=None)
    #tfb.save_fig_html(fig, format='large', name=f'./fig-xp-ratio-distribution-large')
    #fig.update_traces(marker_size=1)
    #tfb.save_fig_html(fig, format='small', name=f'./fig-xp-ratio-distribution-small')

Aberration - eXP Ratio = 1.757
Beast - eXP Ratio = nan
Celestial - eXP Ratio = 1.990
Construct - eXP Ratio = 1.309
Dragon - eXP Ratio = 1.778
Elemental - eXP Ratio = 1.474
Fey - eXP Ratio = 1.612
Fiend - eXP Ratio = 1.398
Giant - eXP Ratio = nan
Humanoid - eXP Ratio = nan
Monstrosity - eXP Ratio = 1.505
Ooze - eXP Ratio = 1.417
Plant - eXP Ratio = nan
Undead - eXP Ratio = 1.665

In [313]:
groups = [
    {
        'name': 'MM 2014 - normal',
        'Book': 'MM (2014)',
        'Legendary': ['N'],
        'CR_range': [2,30],
        'color': COLORS[0], 
        'line_color': COLORS[0], 
        'symbol': 'circle',
    },
    {
        'name': 'MM 2014 - legendary',
        'Book': 'MM (2014)',
        'Legendary': ['L','LL'],
        'CR_range': [2,30],
        'color': COLORS[0],
        'line_color': COLORS[0], 
        'symbol': 'square',
    },
    {
        'name': 'MM 2024 - normal',
        'Book': 'MM (2024)',
        'Legendary': ['N'],
        'CR_range': [2,30],
        'color': COLORS[1],
        'line_color': COLORS[1],
        'symbol': 'circle',
    },
    {
        'name': 'MM 2024 - legendary',
        'Book': 'MM (2024)',
        'Legendary': ['L','LL'],
        'CR_range': [2,30],
        'color': COLORS[1],
        'line_color': COLORS[1],
        'symbol': 'square',
    }
]

# create figure
fig = go.Figure(
    layout=go.Layout(
        template=tfb.FIG_TEMPLATE,
        margin=dict(l=70, r=25, b=55, t=20, pad=4),
        xaxis=dict(
            title_text='eDPR Ratio',
            #type='log',
            #autorange=True,
            tickmode='auto',
            range=[0,3.0],
            #tick0=0, dtick=0.5,
            #minor=dict(tick0=0, dtick=0.1),
            tickformat='.1f',
        ),
        yaxis=dict(
            title_text=f'eHP Ratio',
            #type='log',
            #autorange=True,
            tickmode='auto',
            range=[0,3.0],
            #tick0=0, dtick=0.5,
            #minor=dict(tick0=0, dtick=0.1),
            tickformat='.1f',
        ),
        legend=dict(
            xanchor='right', yanchor='top',
            x=1.00, y=1.00,
            orientation='v',
            tracegroupgap=0,
        )
    )
)

# plot monster data
for group in groups:
    name = group['name']
    book = group['Book']
    df1 = df0[df0['Book'].isin([book]) 
              & df0['Legendary'].isin(group['Legendary'])
              & df0['CR'].between(*group['CR_range'])]
    fig.add_trace(go.Scatter(
        x=df1['eDPR Ratio'], 
        y=df1['eHP Ratio'],
        mode='markers',
        marker_size=4,
        marker_symbol=group['symbol'],
        marker_color=group['color'],
        marker_line_color=group['line_color'],
        marker_line_width=0,
        name=name,
        customdata=np.stack((df1['Monster'], df1['CR']), axis=-1),
        hovertemplate = '<b>%{customdata[0]}' + f' - {name}</b><br>'
            + 'CR %{customdata[1]}<br>'
            + 'eDPR Ratio %{x:.3f}<br>'
            + 'eHP Ratio %{y:.3f}'
            + '<extra></extra>'
    ))

    slope, intercept, r_value, p_value, std_err = scipy.stats.linregress(1/df1['eDPR Ratio'], df1['eHP Ratio'])
    print(f'{name} fit: XP ratio = {intercept + slope:.3f}; r-squared = {r_value**2:.3f}; p-value = {p_value:.3e}')


x = np.linspace(0.2, 3.0, 100)
fig.add_trace(go.Scatter(
    x=x, 
    y=1/x,
    mode='lines', 
    name=f'baseline',
    showlegend=False,
    line_color='black',
    line_dash='dash',
    hoverinfo='skip',
))

x = np.linspace(0.2, 3.0, 100)
fig.add_trace(go.Scatter(
    x=x, 
    y=1.6/x,
    mode='lines', 
    name=f'baseline x1.6',
    showlegend=False,
    line_color='black',
    line_dash='dash',
    hoverinfo='skip',
))

# show figure
fig.update_layout(width=600, height=450)
fig.show(config=tfb.FIG_CONFIG)

# save figures
if SAVEFIGS:
    #fig.update_layout(autosize=True, width=None, height=None)
    #tfb.save_fig_html(fig, format='large', name=f'./fig-xp-ratio-vs-cr-large')
    #tfb.save_fig_html(fig, format='small', name=f'./fig-xp-ratio-vs-cr-small')
    pass

MM 2014 - normal fit: XP ratio = 1.061; r-squared = 0.010; p-value = 1.319e-01
MM 2014 - legendary fit: XP ratio = 1.071; r-squared = 0.348; p-value = 7.731e-05
MM 2024 - normal fit: XP ratio = 1.044; r-squared = 0.252; p-value = 1.853e-19
MM 2024 - legendary fit: XP ratio = 1.545; r-squared = 0.258; p-value = 1.323e-06

In [307]:
groups = [
    {
        'name': 'MM 2014 - normal',
        'Book': 'MM (2014)',
        'Legendary': ['N'],
        'CR_range': [1,30],
        'color': COLORS[0], 
        'line_color': COLORS[0], 
        'symbol': 'circle',
    },
    {
        'name': 'MM 2024 - normal',
        'Book': 'MM (2024)',
        'Legendary': ['N'],
        'CR_range': [1,30],
        'color': COLORS[1],
        'line_color': COLORS[1],
        'symbol': 'circle',
    },
]

# create figure
fig = go.Figure(
    layout=go.Layout(
        template=tfb.FIG_TEMPLATE,
        margin=dict(l=70, r=25, b=55, t=20, pad=4),
        xaxis=dict(
            title_text='adj DPR Ratio',
            #type='log',
            #autorange=True,
            #tickmode='auto',
            #minor_tickmode='auto',
            range=[0,3.0],
            tick0=0, dtick=0.5,
            minor=dict(tick0=0, dtick=0.1),
            tickformat='.1f',
        ),
        yaxis=dict(
            title_text=f'adj HP Ratio',
            #type='log',
            #autorange=True,
            #tickmode='auto',
            #minor_tickmode='auto',
            range=[0,3.0],
            tick0=0, dtick=0.5,
            minor=dict(tick0=0, dtick=0.1),
            tickformat='.1f',
        ),
        legend=dict(
            xanchor='right', yanchor='top',
            x=1.00, y=1.00,
            orientation='v',
            tracegroupgap=0,
        )
    )
)

# plot monster data
for group in groups:
    name = group['name']
    book = group['Book']
    df1 = df0[df0['Book'].isin([book]) 
              & df0['Legendary'].isin(group['Legendary'])
              & df0['CR'].between(*group['CR_range'])]
    fig.add_trace(go.Scatter(
        x=df1['adj DPR Ratio'], 
        y=df1['adj HP Ratio'],
        mode='markers',
        marker_size=4,
        marker_symbol=group['symbol'],
        marker_color=group['color'],
        marker_line_color=group['line_color'],
        marker_line_width=0,
        name=name,
        customdata=np.stack((df1['Monster'], df1['CR'], df1['eXP Ratio']), axis=-1),
        hovertemplate = '<b>%{customdata[0]}' + f' - {name}</b><br>'
            + 'CR %{customdata[1]}<br>'
            + 'eDPR Ratio %{x:.3f}<br>'
            + 'eHP Ratio %{y:.3f}<br>'
            + 'eXP Ratio %{customdata[2]:.3f}'
            + '<extra></extra>'
    ))

    slope, intercept, r_value, p_value, std_err = scipy.stats.linregress(1/df1['eDPR Ratio'], df1['eHP Ratio'])
    print(f'{name} fit: XP ratio = {intercept + slope:.3f}; r-squared = {r_value**2:.3f}; p-value = {p_value:.3e}')


x = np.linspace(0.2, 3.0, 100)
fig.add_trace(go.Scatter(
    x=x, 
    y=1/x,
    mode='lines', 
    name=f'baseline',
    showlegend=False,
    line_color='black',
    line_dash='dash',
    hoverinfo='skip',
))

"""x = np.linspace(0.2, 3.0, 100)
fig.add_trace(go.Scatter(
    x=x, 
    y=1.6/x,
    mode='lines', 
    name=f'baseline x1.6',
    showlegend=False,
    line_color='black',
    line_dash='dash',
    hoverinfo='skip',
))"""

# show figure
fig.update_layout(width=600, height=450)
fig.show(config=tfb.FIG_CONFIG)

# save figures
if SAVEFIGS:
    #fig.update_layout(autosize=True, width=None, height=None)
    #tfb.save_fig_html(fig, format='large', name=f'./fig-xp-ratio-vs-cr-large')
    #tfb.save_fig_html(fig, format='small', name=f'./fig-xp-ratio-vs-cr-small')
    pass

MM 2014 - normal fit: XP ratio = 1.061; r-squared = 0.003; p-value = 3.729e-01
MM 2024 - normal fit: XP ratio = 1.033; r-squared = 0.227; p-value = 8.625e-20

In [32]:
# compares how monster HP changed when losing resistances
df1 = df0[df0['Book'].isin(['MM (2014)','MM (2024)']) & df0['Legendary'].isin(['N','L','LL'])]
dfMP = pd.pivot_table(df1, 
    values=['HP','eXP Ratio','Immunities','Resistances','Mitigation Multiplier'],
    index=['Monster', 'CR'], columns=['Book']).reset_index()
dfMP = dfMP[dfMP['HP']['MM (2014)'].isna() == False]
dfMP = dfMP[dfMP['HP']['MM (2024)'].isna() == False]

"""dfMP = dfMP[dfMP['Immunities']['MM (2014)'].lt(3)]
dfMP = dfMP[dfMP['Immunities']['MM (2024)'].lt(3)]
dfMP = dfMP[dfMP['Resistances']['MM (2014)'].ge(3)]
dfMP = dfMP[dfMP['Resistances']['MM (2024)'].lt(3)]"""

dfMP = dfMP[dfMP['Immunities']['MM (2014)'].ge(3)]
dfMP = dfMP[dfMP['Immunities']['MM (2024)'].lt(3)]
dfMP = dfMP[dfMP['Resistances']['MM (2014)'].lt(3)]
dfMP = dfMP[dfMP['Resistances']['MM (2024)'].lt(3)]

#dfMP = dfMP[dfMP['Mitigation Multiplier']['MM (2014)'].gt(1)]
#dfMP = dfMP[dfMP['Mitigation Multiplier']['MM (2024)'].eq(1)]
dfMP['HP ratio'] = dfMP['HP']['MM (2024)']/dfMP['HP']['MM (2014)']
dfMP['XP ratio'] = (dfMP['eXP Ratio']['MM (2024)']/dfMP['Mitigation Multiplier']['MM (2024)'])/(dfMP['eXP Ratio']['MM (2014)']/dfMP['Mitigation Multiplier']['MM (2014)'])

def cr_groups(row):
    for l0, l1 in [[0,4],[5,10],[11,16],[17,30]]:
        if (row['CR'][0] >= l0) and (row['CR'][0] <= l1):
            return f'{l0}-{l1}'
    return 'unknown'


dfMP['CR group'] = dfMP.apply(lambda row: cr_groups(row), axis=1)

dfG = dfMP[['CR group','XP ratio']].groupby(['CR group']).median()
print(dfG['XP ratio'])

dfG = dfMP[['CR group','Monster']].groupby(['CR group']).count()
print(dfG['Monster'])

CR group
0-4      1.675547
11-16    3.164331
17-30    0.964213
5-10     1.799222
Name: XP ratio, dtype: float64
CR group
0-4      5
11-16    2
17-30    1
5-10     3
Name: Monster, dtype: int64

/var/folders/k4/phz5f3ss2_91t6j4s71jmp540000gn/T/ipykernel_49145/3705269253.py:3: FutureWarning: The default value of observed=False is deprecated and will change to observed=True in a future version of pandas. Specify observed=False to silence this warning and retain the current behavior
  dfMP = pd.pivot_table(df1,
/var/folders/k4/phz5f3ss2_91t6j4s71jmp540000gn/T/ipykernel_49145/3705269253.py:26: FutureWarning: Series.__getitem__ treating keys as positions is deprecated. In a future version, integer keys will always be treated as labels (consistent with DataFrame behavior). To access a value by position, use `ser.iloc[pos]`
  if (row['CR'][0] >= l0) and (row['CR'][0] <= l1):
/var/folders/k4/phz5f3ss2_91t6j4s71jmp540000gn/T/ipykernel_49145/3705269253.py:33: PerformanceWarning: dropping on a non-lexsorted multi-index without a level parameter may impact performance.
  dfG = dfMP[['CR group','XP ratio']].groupby(['CR group']).median()
/var/folders/k4/phz5f3ss2_91t6j4s71jmp540000gn/T/ipykernel_49145/3705269253.py:36: PerformanceWarning: dropping on a non-lexsorted multi-index without a level parameter may impact performance.
  dfG = dfMP[['CR group','Monster']].groupby(['CR group']).count()

In [329]:
column = 'eXP Ratio'
groups = [
    {
        'name': '2024 - normal',
        'Book': 'MM (2024)',
        'Legendary': ['N'],
        'color': COLORS[1], #'rgba(250,0,0,1)',
        'line_color': COLORS[1], #'rgba(250,0,0,1)',
        'symbol': 'circle',
    },
]

# create figure
fig = go.Figure(
    layout=go.Layout(
        template=tfb.FIG_TEMPLATE,
        xaxis=dict(
            #title_text='encounter type',
            autorange=True,
            
        ),
        yaxis=dict(
            title_text=f'{column}',
            #autorange=True,
            range=[0, 2.0],
            #tick0=0, dtick=0.5,
            #minor=dict(tick0=0, dtick=0.1),
        ),
    )
)

for group in groups:
    book = group['Book']
    name = group['name']
    df1 = df0[df0['Book'].isin([book]) & df0['Legendary'].isin(group['Legendary'])]
    df1 = df1[df1['CR'].between(5,10)]
    df1['eXP Ratio'] = df1['eXP Ratio']/df1['Mitigation Multiplier']
    fig.add_trace(go.Box(
        x=df1['Mitigation'],
        y=df1[column],
        name=name,
        customdata=df1['Monster'],
        showlegend=False,
        boxpoints='all',
        jitter=0.4,
        whiskerwidth=0.4,
        marker_size=2,
        marker_symbol=group['symbol'],
        marker_color=group['color'],
        marker_line_color=group['line_color'],
        marker_line_width=2,
        hoveron='points',
        hovertemplate=f'<b>{name}</b><br>'+
            '%{customdata}<br>'+
            column + ' %{y:.2f}<br>'+
            '<extra></extra>'
    ))

# show figure
fig.update_layout(width=600, height=450)
fig.show(config=tfb.FIG_CONFIG)

# save figures
if SAVEFIGS:
    #fig.update_layout(autosize=True, width=None, height=None)
    #tfb.save_fig_html(fig, format='large', name=f'./fig-xp-ratio-vs-cr-large')
    #tfb.save_fig_html(fig, format='small', name=f'./fig-xp-ratio-vs-cr-small')
    pass

In [45]:
from plotly.subplots import make_subplots

column = 'eXP Ratio'
groups = [
    {
        'name': '2014 - normal',
        'Book': 'MM (2014)',
        'Legendary': ['N','L','LL'],
        'CR range': [0,30],
        'color': COLORS[0],
        'line_color': COLORS[0],
        'symbol': 'circle',
        'mitigation': ['R3+','BPS'],
    },
    {
        'name': '2024 - normal',
        'Book': 'MM (2024)',
        'Legendary': ['N'],
        'CR range': [0,30],
        'color': COLORS[1],
        'line_color': COLORS[1],
        'symbol': 'circle',
        'mitigation': ['R3+'],
    },
]


# create figure
fig = make_subplots(rows=1, cols=len(groups), shared_yaxes=True, horizontal_spacing=0.03)

def cr_groups(row):
    for l0, l1 in [[0,4],[5,10],[11,16],[17,30]]:
        if (row['CR'] >= l0) and (row['CR'] <= l1):
            return f'{l0}-{l1}'
    return 'unknown'

for ig in range(len(groups)):
    group = groups[ig]
    book = group['Book']
    name = group['name']
    mitigation = group['mitigation']
    legendary = group['Legendary']
    df1 = df0[df0['Book'].isin([book]) 
              & df0['CR'].between(*group['CR range'])
              & df0['Legendary'].isin(legendary)
              & df0['Mitigation'].isin(mitigation)]
    df1['eXP Ratio'] = df1['eXP Ratio']/df1['Mitigation Multiplier']
    df1['CR group'] = df1.apply(lambda row: cr_groups(row), axis=1)
    df1 = df1.astype({'CR group': 'category'})
    df1['CR group'] = df1['CR group'].cat.set_categories(['0-4','5-10','11-16','17-30'], ordered=True)
    df1.sort_values('CR group', inplace=True)
    
    fig.add_trace(
        go.Box(
            x=df1['CR group'],
            y=df1[column],
            name=name,
            #legendgroup=name,
            #legendgrouptitle=name,
            customdata=df1['Monster'],
            showlegend=True,
            legendgroup='1',
            boxpoints='all',
            jitter=0.4,
            whiskerwidth=0.4,
            marker_size=2,
            marker_symbol=group['symbol'],
            marker_color=group['color'],
            marker_line_color=group['line_color'],
            marker_line_width=2,
            hoveron='points',
            hovertemplate=f'<b>{name}</b><br>'+
                '%{customdata}<br>'+
                column + ' %{y:.2f}<br>'+
                '<extra></extra>'
        ),
        row=1, 
        col=ig+1
    )

    fig.add_trace(
        go.Scatter(
            x=['0-4','5-10','11-16','17-30'],
            y=[1/2,1/1.5,1/1.25,1],
            showlegend=False,
            mode='lines',
            line_color='black',
            line_dash='dash',
        ),
        row=1, 
        col=ig+1
    )

# show figure
fig.update_layout(
    template=tfb.FIG_TEMPLATE,
    xaxis=dict(
        title_text='challenge rating',
        autorange=True,
    ),
    xaxis2=dict(
        title_text='challenge rating',
        autorange=True,
    ),
    yaxis=dict(
        title_text=f'{column}',
        range=[0, 1.5],
        tick0=0, dtick=0.5,
        tickformat='.1f',
        minor=dict(tick0=0, dtick=0.1),
    ),
    legend=dict(
        xanchor='right', yanchor='top',
        x=0.21, y=1.00,
        orientation='v',
        tracegroupgap=0,
    ),
    width=700, 
    height=450,
)
fig.show(config=tfb.FIG_CONFIG)

# save figures
if SAVEFIGS:
    #fig.update_layout(autosize=True, width=None, height=None)
    #tfb.save_fig_html(fig, format='large', name=f'./fig-xp-ratio-vs-cr-large')
    #tfb.save_fig_html(fig, format='small', name=f'./fig-xp-ratio-vs-cr-small')
    pass

In [62]:
#print(monster_offensive_challenge_rating())
print(monster_defensive_challenge_rating(97.5, None))

5

In [65]:
"""
adj HP 97.5 --> D-CR 2
eAC 21.25 - 13 = 8.25 --> D-CR +4
D-CR 6

adj DPR 88.5 --> O-CR 14
eAB +7 - +8 = -1 --> O-CR -0.5
O-CR 13.5
"""

"""without adjustments
adj HP 97.5 --> D-CR 2
eAC 16 - 13 = 3 --> D-CR +1.5
D-CR 3.5

adj DPR 88.5 --> O-CR 14
eAB +7 - +8 = -1 --> O-CR -0.5
O-CR 13.5
"""
df0[df0['Monster'].eq('Assassin')][['Monster','Book','eXP','eAC','adj HP','D-CR Base','D-CR AC Delta','D-CR','adj AB','adj DPR','O-CR Base','O-CR AB Delta','O-CR','eCR']]

,Monster,Book,eXP,eAC,adj HP,D-CR Base,D-CR AC Delta,D-CR,adj AB,adj DPR,O-CR Base,O-CR AB Delta,O-CR,eCR
168,Assassin,MM (2014),3352.500090,16.50,78.0,4.0,1.50,4.0,8.0,99.333336,16.0,-4.0,14.0,8.0
65,Assassin,MM (2024),4355.859375,21.25,97.5,5.0,6.25,8.0,7.0,88.500000,14.0,-4.0,12.0,9.0

In [43]:
from plotly.subplots import make_subplots

column = 'eXP Ratio'
groups = [
    {
        'name': '2014 - normal',
        'Book': 'MM (2014)',
        'Legendary': ['N','L','LL'],
        'CR range': [0,30],
        'color': COLORS[0],
        'line_color': COLORS[0],
        'symbol': 'circle',
        'mitigation': ['I3+'],
    },
    {
        'name': '2024 - normal',
        'Book': 'MM (2024)',
        'Legendary': ['N'],
        'CR range': [0,30],
        'color': COLORS[1],
        'line_color': COLORS[1],
        'symbol': 'circle',
        'mitigation': ['I3+'],
    },
]


# create figure
fig = make_subplots(rows=1, cols=len(groups), shared_yaxes=True, horizontal_spacing=0.03)

def cr_groups(row):
    for l0, l1 in [[0,4],[5,10],[11,16],[17,30]]:
        if (row['CR'] >= l0) and (row['CR'] <= l1):
            return f'{l0}-{l1}'
    return 'unknown'

for ig in range(len(groups)):
    group = groups[ig]
    book = group['Book']
    name = group['name']
    mitigation = group['mitigation']
    legendary = group['Legendary']
    df1 = df0[df0['Book'].isin([book]) 
              & df0['CR'].between(*group['CR range'])
              & df0['Legendary'].isin(legendary)
              & df0['Mitigation'].isin(mitigation)]
    df1['eXP Ratio'] = df1['eXP Ratio']/df1['Mitigation Multiplier']
    df1['CR group'] = df1.apply(lambda row: cr_groups(row), axis=1)
    df1 = df1.astype({'CR group': 'category'})
    df1['CR group'] = df1['CR group'].cat.set_categories(['0-4','5-10','11-16','17-30'], ordered=True)
    df1.sort_values('CR group', inplace=True)
    
    fig.add_trace(
        go.Box(
            x=df1['CR group'],
            y=df1[column],
            name=name,
            #legendgroup=name,
            #legendgrouptitle=name,
            customdata=df1['Monster'],
            showlegend=True,
            legendgroup='1',
            boxpoints='all',
            jitter=0.4,
            whiskerwidth=0.4,
            marker_size=2,
            marker_symbol=group['symbol'],
            marker_color=group['color'],
            marker_line_color=group['line_color'],
            marker_line_width=2,
            hoveron='points',
            hovertemplate=f'<b>{name}</b><br>'+
                '%{customdata}<br>'+
                column + ' %{y:.2f}<br>'+
                '<extra></extra>'
        ),
        row=1, 
        col=ig+1
    )

    fig.add_trace(
        go.Scatter(
            x=['0-4','5-10','11-16','17-30'],
            y=[1/2,1/2,1/1.5,1/1.25],
            showlegend=False,
            mode='lines',
            line_color='black',
            line_dash='dash',
        ),
        row=1, 
        col=ig+1
    )

# show figure
fig.update_layout(
    template=tfb.FIG_TEMPLATE,
    xaxis=dict(
        title_text='challenge rating',
        autorange=True,
    ),
    xaxis2=dict(
        title_text='challenge rating',
        autorange=True,
    ),
    yaxis=dict(
        title_text=f'{column}',
        range=[0, 1.5],
        tick0=0, dtick=0.5,
        tickformat='.1f',
        minor=dict(tick0=0, dtick=0.1),
    ),
    legend=dict(
        xanchor='right', yanchor='top',
        x=0.21, y=1.00,
        orientation='v',
        tracegroupgap=0,
    ),
    width=700, 
    height=450,
)
fig.show(config=tfb.FIG_CONFIG)

# save figures
if SAVEFIGS:
    #fig.update_layout(autosize=True, width=None, height=None)
    #tfb.save_fig_html(fig, format='large', name=f'./fig-xp-ratio-vs-cr-large')
    #tfb.save_fig_html(fig, format='small', name=f'./fig-xp-ratio-vs-cr-small')
    pass

In [448]:
from plotly.subplots import make_subplots

column = 'eXP Ratio'
groups = [
    {
        'name': '2014 - normal',
        'Book': 'MM (2014)',
        'Legendary': ['N','L','LL'],
        'CR range': [0,10],
        'color': COLORS[0],
        'line_color': COLORS[0],
        'symbol': 'circle',
        'mitigation': ['R3+','BPS','none'],
    },
    {
        'name': '2024 - normal',
        'Book': 'MM (2024)',
        'Legendary': ['N'],
        'CR range': [0,10],
        'color': COLORS[1],
        'line_color': COLORS[1],
        'symbol': 'circle',
        'mitigation': ['R3+','BPS','none'],
    },
]


# create figure
fig = make_subplots(rows=1, cols=len(groups), shared_yaxes=True, horizontal_spacing=0.03)

def cr_groups(row):
    for l0, l1 in [[0,4],[5,10],[11,16],[17,30]]:
        if (row['CR'] >= l0) and (row['CR'] <= l1):
            return f'{l0}-{l1}'
    return 'unknown'

for ig in range(len(groups)):
    group = groups[ig]
    book = group['Book']
    name = group['name']
    mitigation = group['mitigation']
    legendary = group['Legendary']
    df1 = df0[df0['Book'].isin([book]) 
              & df0['CR'].between(*group['CR range'])
              & df0['Legendary'].isin(legendary)
              & df0['Mitigation'].isin(mitigation)
              & df0['Immunities'].eq(0)]
    df1['eXP Ratio'] = df1['eXP Ratio']/df1['Mitigation Multiplier']
    df1['CR group'] = df1.apply(lambda row: cr_groups(row), axis=1)
    df1 = df1.astype({'CR group': 'category'})
    df1['CR group'] = df1['CR group'].cat.set_categories(['0-4','5-10','11-16','17-30'], ordered=True)
    df1.sort_values('CR group', inplace=True)
    
    fig.add_trace(
        go.Box(
            x=df1['Resistances'],
            y=df1[column],
            name=name,
            #legendgroup=name,
            #legendgrouptitle=name,
            customdata=df1['Monster'],
            showlegend=True,
            legendgroup='1',
            boxpoints='all',
            jitter=0.4,
            whiskerwidth=0.4,
            marker_size=2,
            marker_symbol=group['symbol'],
            marker_color=group['color'],
            marker_line_color=group['line_color'],
            marker_line_width=2,
            hoveron='points',
            hovertemplate=f'<b>{name}</b><br>'+
                '%{customdata}<br>'+
                column + ' %{y:.2f}<br>'+
                '<extra></extra>'
        ),
        row=1, 
        col=ig+1
    )

# show figure
fig.update_layout(
    template=tfb.FIG_TEMPLATE,
    xaxis=dict(
        title_text='resistances',
        autorange=True,
    ),
    xaxis2=dict(
        title_text='resistances',
        autorange=True,
    ),
    yaxis=dict(
        title_text=f'{column}',
        range=[0, 2.0],
        tick0=0, dtick=0.5,
        tickformat='.1f',
        minor=dict(tick0=0, dtick=0.1),
    ),
    legend=dict(
        xanchor='right', yanchor='top',
        x=0.21, y=1.00,
        orientation='v',
        tracegroupgap=0,
    ),
    width=700, 
    height=450,
)
fig.show(config=tfb.FIG_CONFIG)

# save figures
if SAVEFIGS:
    #fig.update_layout(autosize=True, width=None, height=None)
    #tfb.save_fig_html(fig, format='large', name=f'./fig-xp-ratio-vs-cr-large')
    #tfb.save_fig_html(fig, format='small', name=f'./fig-xp-ratio-vs-cr-small')
    pass

In [445]:
from plotly.subplots import make_subplots

column = 'eXP Ratio'
groups = [
    {
        'name': '2014 - normal',
        'Book': 'MM (2014)',
        'Legendary': ['N','L','LL'],
        'CR range': [0,30],
        'color': COLORS[0],
        'line_color': COLORS[0],
        'symbol': 'circle',
        'mitigation': ['none','R3+','BPS','I3+'],
    },
    {
        'name': '2024 - normal',
        'Book': 'MM (2024)',
        'Legendary': ['N'],
        'CR range': [0,30],
        'color': COLORS[1],
        'line_color': COLORS[1],
        'symbol': 'circle',
        'mitigation': ['none','R3+','BPS','I3+'],
    },
]


# create figure
fig = make_subplots(rows=1, cols=len(groups), shared_yaxes=True, horizontal_spacing=0.03)

def cr_groups(row):
    for l0, l1 in [[0,4],[5,10],[11,16],[17,30]]:
        if (row['CR'] >= l0) and (row['CR'] <= l1):
            return f'{l0}-{l1}'
    return 'unknown'

for ig in range(len(groups)):
    group = groups[ig]
    book = group['Book']
    name = group['name']
    mitigation = group['mitigation']
    legendary = group['Legendary']
    df1 = df0[df0['Book'].isin([book]) 
              & df0['CR'].between(*group['CR range'])
              & df0['Legendary'].isin(legendary)
              & df0['Mitigation'].isin(mitigation)
              & df0['Resistances'].eq(0)]
    df1['eXP Ratio'] = df1['eXP Ratio']/df1['Mitigation Multiplier']
    df1['CR group'] = df1.apply(lambda row: cr_groups(row), axis=1)
    df1 = df1.astype({'CR group': 'category'})
    df1['CR group'] = df1['CR group'].cat.set_categories(['0-4','5-10','11-16','17-30'], ordered=True)
    df1.sort_values('CR group', inplace=True)
    
    fig.add_trace(
        go.Box(
            x=df1['Immunities'],
            y=df1[column],
            name=name,
            #legendgroup=name,
            #legendgrouptitle=name,
            customdata=df1['Monster'],
            showlegend=True,
            legendgroup='1',
            boxpoints='all',
            jitter=0.4,
            whiskerwidth=0.4,
            marker_size=2,
            marker_symbol=group['symbol'],
            marker_color=group['color'],
            marker_line_color=group['line_color'],
            marker_line_width=2,
            hoveron='points',
            hovertemplate=f'<b>{name}</b><br>'+
                '%{customdata}<br>'+
                column + ' %{y:.2f}<br>'+
                '<extra></extra>'
        ),
        row=1, 
        col=ig+1
    )

# show figure
fig.update_layout(
    template=tfb.FIG_TEMPLATE,
    xaxis=dict(
        title_text='immunities',
        autorange=True,
    ),
    xaxis2=dict(
        title_text='immunities',
        autorange=True,
    ),
    yaxis=dict(
        title_text=f'{column}',
        range=[0, 2.0],
        tick0=0, dtick=0.5,
        tickformat='.1f',
        minor=dict(tick0=0, dtick=0.1),
    ),
    legend=dict(
        xanchor='right', yanchor='top',
        x=0.21, y=1.00,
        orientation='v',
        tracegroupgap=0,
    ),
    width=700, 
    height=450,
)
fig.show(config=tfb.FIG_CONFIG)

# save figures
if SAVEFIGS:
    #fig.update_layout(autosize=True, width=None, height=None)
    #tfb.save_fig_html(fig, format='large', name=f'./fig-xp-ratio-vs-cr-large')
    #tfb.save_fig_html(fig, format='small', name=f'./fig-xp-ratio-vs-cr-small')
    pass

In [ ]:
# unadjusted XP ratio by number of immunities
column = 'eXP Ratio' #'eXP Ratio'
books = ['BGDiA', 'BPGotG', 'CM', 'CRCotN', 'CoS', 'DSotDQ', 
         'EGtW', 'ERftLW', 'FToD', 'GGtR', 'GoS', 'HotDQ', 
         'IDRotF', 'JttRC', 'KftGV', 'MM (2014)', 'MOoT', 
         'MPMotM', 'MToF', 'OotA', 'PAitM:MPP', 'PaBTSO', 
         'PotA', 'QftIS', 'RoT', 'SACoC', 'SAiS:BAM', 'SAiS:LoX', 
         'SKT', 'TBoMT', 'TWBtW', 'TftYP', 'ToA', 'VEoR', 
         'VGtM', 'VRGtR', 'WDH', 'WDotMM']
groups = [
    {
        'name': '2014 - normal',
        'Book': books,
        'Legendary': ['N','L','LL'],
        'CR range': [0.5,0.5],
        'color': COLORS[0],
        'line_color': COLORS[0],
        'symbol': 'circle',
        'mitigation': ['none','R3+','BPS','I3+'],
    },
    {
        'name': '2024 - normal',
        'Book': ['MM (2024)'],
        'Legendary': ['N'],
        'CR range': [0.5,0.5],
        'color': COLORS[1],
        'line_color': COLORS[1],
        'symbol': 'circle',
        'mitigation': ['none','R3+','BPS','I3+'],
    },
]


# create figure
fig = go.Figure()

for ig in range(len(groups)):
    group = groups[ig]
    book = group['Book']
    name = group['name']
    mitigation = group['mitigation']
    legendary = group['Legendary']
    df1 = df0[df0['Book'].isin(book) 
              & df0['CR'].between(*group['CR range'])
              & df0['Legendary'].isin(legendary)
              & df0['Mitigation'].isin(mitigation)
              & df0['Resistances'].lt(3)]
    df1[column] = df1[column]/df1['HP Multiplier']
    
    text = []
    for _, row in df1.iterrows():
        t = f'<b>{name}</b><br>'
        t += f"{row['Monster']} (CR {row['CR']}, {row['Book']})<br>"
        t += f"{column} {row[column]:.2f}<br>"
        t += f"Mutliplier {row['HP Multiplier']}<br>"
        if list_resistances(row):
            t += 'Resistances:<br> - ' + '<br> - '.join(list_resistances(row)).lower() + '<br>'
        if list_immunities(row):
            t += 'Immunities:<br> - ' + '<br> - '.join(list_immunities(row)).lower() + '<br>'
        text.append(t)
    
    fig.add_trace(go.Scatter(
        x=jitter(df1['Immunities'], 0.1),
        y=df1[column],
        name=name,
        mode='markers',
        customdata=df1['Monster'],
        marker_size=4,
        marker_symbol=group['symbol'],
        marker_color=group['color'],
        text=text,
        #marker_line_color=group['line_color'],
        #marker_line_width=2,
        hovertemplate='%{text}<extra></extra>'
    ))
    
    dfG = df1[[column,'Immunities']].groupby('Immunities').mean().reset_index()
    fig.add_trace(go.Scatter(
        x=dfG['Immunities'],
        y=dfG[column],
        name=name,
        showlegend=False,
        legendgroup=name,
        mode='lines',
        line_color=group['color'],
        hoverinfo='skip',
    ))

# show figure
fig.update_layout(
    template=tfb.FIG_TEMPLATE,
    xaxis=dict(
        title_text='immunities',
        range=[-0.5,6.5]
    ),
    yaxis=dict(
        title_text=f'{column}',
        range=[0, 2.0],
        tick0=0, dtick=0.5,
        tickformat='.1f',
        minor=dict(tick0=0, dtick=0.1),
    ),
    legend=dict(
        xanchor='right', yanchor='top',
        x=1.00, y=1.00,
        orientation='v',
        tracegroupgap=0,
    ),
    width=600, 
    height=450,
)
#fig.update_layout(width=600, height=450)
fig.show(config=tfb.FIG_CONFIG)

# save figures
if SAVEFIGS:
    #fig.update_layout(autosize=True, width=None, height=None)
    #tfb.save_fig_html(fig, format='large', name=f'./fig-xp-ratio-vs-cr-large')
    #tfb.save_fig_html(fig, format='small', name=f'./fig-xp-ratio-vs-cr-small')
    pass

In [31]:
# unadjusted XP ratio by number of resistances
column = 'eXP Ratio'
books = ['BGDiA', 'BPGotG', 'CM', 'CRCotN', 'CoS', 'DSotDQ', 
         'EGtW', 'ERftLW', 'FToD', 'GGtR', 'GoS', 'HotDQ', 
         'IDRotF', 'JttRC', 'KftGV', 'MM (2014)', 'MOoT', 
         'MPMotM', 'MToF', 'OotA', 'PAitM:MPP', 'PaBTSO', 
         'PotA', 'QftIS', 'RoT', 'SACoC', 'SAiS:BAM', 'SAiS:LoX', 
         'SKT', 'TBoMT', 'TWBtW', 'TftYP', 'ToA', 'VEoR', 
         'VGtM', 'VRGtR', 'WDH', 'WDotMM']
groups = [
    {
        'name': '2014 - normal',
        'Book': books,
        'Legendary': ['N','L','LL'],
        'CR range': [0.5,1],
        'color': COLORS[0],
        'line_color': COLORS[0],
        'symbol': 'circle',
        'mitigation': ['none','R3+','I3+'],
    },
    {
        'name': '2024 - normal',
        'Book': ['MM (2024)'],
        'Legendary': ['N'],
        'CR range': [0.5,1],
        'color': COLORS[1],
        'line_color': COLORS[1],
        'symbol': 'circle',
        'mitigation': ['none','R3+','I3+'],
    },
]

# create figure
fig = go.Figure()

for ig in range(len(groups)):
    group = groups[ig]
    book = group['Book']
    name = group['name']
    mitigation = group['mitigation']
    legendary = group['Legendary']
    df1 = df0[df0['Book'].isin(book) 
              & df0['CR'].between(*group['CR range'])
              & df0['Legendary'].isin(legendary)
              & df0['Mitigation'].isin(mitigation)
              & df0['Immunities'].lt(3)]
    df1[column] = df1[column]/df1['HP Multiplier']
    
    text = []
    for _, row in df1.iterrows():
        t = f'<b>{name}</b><br>'
        t += f"{row['Monster']} (CR {row['CR']}, {row['Book']})<br>"
        t += f"{column} {row[column]:.2f}<br>"
        t += f"Mutliplier {row['HP Multiplier']}<br>"
        if list_resistances(row):
            t += 'Resistances<br> - ' + '<br> - '.join(list_resistances(row)).lower() + '<br>'
        if list_immunities(row):
            t += 'Immunities<br> - ' + '<br> - '.join(list_immunities(row)).lower() + '<br>'
        text.append(t)
    
    x_column = 'Resistances'
    df1['Resistances+Immunities'] = df1['Resistances'] + df1['Immunities']
    fig.add_trace(
        go.Scatter(
            x=jitter(df1[x_column], 0.1),
            y=df1[column],
            name=name,
            legendgroup=name,
            mode='markers',
            marker_size=4,
            marker_symbol=group['symbol'],
            marker_color=group['color'],
            text=text,
            #marker_line_color=group['line_color'],
            #marker_line_width=2,
            hovertemplate='%{text}<extra></extra>',
        )
    )

    dfG = df1[[column,x_column]].groupby(x_column).mean().reset_index()
    fig.add_trace(
        go.Scatter(
            x=dfG[x_column],
            y=dfG[column],
            name=name,
            showlegend=False,
            legendgroup=name,
            mode='lines',
            line_color=group['color'],
            hoverinfo='skip',
        )
    )

# show figure
fig.update_layout(
    template=tfb.FIG_TEMPLATE,
    xaxis=dict(
        title_text='resistances',
        range=[-0.5, 6.5],
    ),
    yaxis=dict(
        title_text=f'{column}',
        range=[0, 2.0],
        tick0=0, dtick=0.5,
        tickformat='.1f',
        minor=dict(tick0=0, dtick=0.1),
    ),
    legend=dict(
        xanchor='right', yanchor='top',
        x=1.00, y=1.00,
        orientation='v',
        tracegroupgap=0,
    ),
    width=600, 
    height=450,
)
#fig.update_layout(width=600, height=450)
fig.show(config=tfb.FIG_CONFIG)

# save figures
if SAVEFIGS:
    #fig.update_layout(autosize=True, width=None, height=None)
    #tfb.save_fig_html(fig, format='large', name=f'./fig-xp-ratio-vs-cr-large')
    #tfb.save_fig_html(fig, format='small', name=f'./fig-xp-ratio-vs-cr-small')
    pass

In [536]:
from plotly.subplots import make_subplots

column = 'eXP Ratio'
groups = [
    {
        'name': '2014 - normal',
        'Book': 'MM (2014)',
        'Legendary': ['N'],
        'CR range': [0,16],
        'color': COLORS[0],
        'line_color': COLORS[0],
        'symbol': 'circle',
        'mitigation': ['none','I3+','BPS','R3+'],
    },
    {
        'name': '2024 - normal',
        'Book': 'MM (2024)',
        'Legendary': ['N'],
        'CR range': [0,16],
        'color': COLORS[1],
        'line_color': COLORS[1],
        'symbol': 'circle',
        'mitigation': ['none','I3+','BPS','R3+'],
    },
]

# create figure
fig = go.Figure(
    layout=go.Layout(
        template=tfb.FIG_TEMPLATE,
        xaxis=dict(
            title_text='multiplier',
            range=[0.9,2.1],
            tickmode='auto',
            minor_tickmode='auto',
        ),
        yaxis=dict(
            title_text=f'{column}',
            #autorange=True,
            range=[0, 2.0],
            tick0=0, dtick=0.5,
            tickformat='.1f',
            minor=dict(tick0=0, dtick=0.1),
        ),
        legend=dict(
            xanchor='left', yanchor='top',
            x=0.0, y=1.00,
            orientation='v',
            tracegroupgap=0,
        ),
    )
)

def cr_groups(row):
    for l0, l1 in [[0,4],[5,10],[11,16],[17,30]]:
        if (row['CR'] >= l0) and (row['CR'] <= l1):
            return f'{l0}-{l1}'
    return 'unknown'

for ig in range(len(groups)):
    group = groups[ig]
    book = group['Book']
    name = group['name']
    color = group['color']
    mitigation = group['mitigation']
    legendary = group['Legendary']
    df1 = df0[df0['Book'].isin([book]) 
              & df0['CR'].between(*group['CR range'])
              & df0['Legendary'].isin(legendary)
              & df0['Mitigation'].isin(mitigation)]
    df1['eXP Ratio'] = df1['eXP Ratio']/df1['Mitigation Multiplier']
    df1['CR group'] = df1.apply(lambda row: cr_groups(row), axis=1)
    df1 = df1.astype({'CR group': 'category'})
    df1['CR group'] = df1['CR group'].cat.set_categories(['0-4','5-10','11-16','17-30'], ordered=True)
    df1.sort_values('CR group', inplace=True)

    fig.add_trace(go.Scatter(
        x=jitter(df1['Mitigation Multiplier'], 0.01),
        y=df1['eXP Ratio'],
        name=name,
        mode='markers',
        line_color=color,
        showlegend=True,
        hoverinfo='skip',
    ))

fig.add_trace(go.Scatter(
    x=[1,2.0],
    y=[1,0.5],
    name=name,
    mode='lines',
    line_color='black',
    showlegend=False,
    hoverinfo='skip',
))

# show figure
fig.update_layout(width=600, height=450)
fig.show(config=tfb.FIG_CONFIG)

# save figures
if SAVEFIGS:
    #fig.update_layout(autosize=True, width=None, height=None)
    #tfb.save_fig_html(fig, format='large', name=f'./fig-xp-ratio-vs-cr-large')
    #tfb.save_fig_html(fig, format='small', name=f'./fig-xp-ratio-vs-cr-small')
    pass

In [311]:
groups = [
    {
        'name': 'MM 2024 - normal',
        'Book': 'MM (2024)',
        'Legendary': ['N','L','LL'],
        'CR_range': [0,30],
        'color': COLORS[1],
        'line_color': COLORS[1],
        'symbol': 'circle',
    },
]

for group in groups:
    name = group['name']
    book = group['Book']
    df1 = df0[df0['Book'].isin([book]) 
        & df0['Legendary'].isin(group['Legendary'])
        & df0['CR'].between(*group['CR_range'])
        & (df0['adj HP'] < 1.25*df0['HP'])]
    df1 = df1.sort_values('eXP Ratio', ascending=False)
    
    for i, row in df1.iterrows():
        nImmunities = row['Immunities']
        physical = 'BSP' if (row['Bludgeoning'] < 1) and (row['Piercing'] < 1) and (row['Slashing'] < 1) else 'no'
        if (nImmunities >= 3) or (physical == 'BPS'):
            print(f"{row['Monster']} (CR {row['CR']}, {row['eXP Ratio']:.3f}) - {row['adj HP Ratio']:.3f}, {row['adj DPR Ratio']:.3f}, {row['Immunities']}, {row['Resistances']}")

# 2014 MM

CR 16+:
Lich (CR 21.0, 0.680) - 0.700, 1.062, 4, 3 () 1.25x HP

CR 11-15:
Marid (CR 11.0, 0.948) - 1.427, 0.579, 0, 3 (no) 1.25x HP
Rakshasa (CR 13.0, 0.132) - 0.706, 0.216, 2, 0 (physical) 1.5x HP

Arcanaloth (CR 12.0, 1.061) - 0.596, 1.731, 2, 6 (physical) 1.25x HP
Ice Devil (CR 14.0, 0.962) - 1.075, 0.868, 3, 3 (physical) 1.5x HP
Archmage (CR 12.0, 0.934) - 0.568, 1.571, 0, 13 (no) 1.25x HP
Erinyes (CR 12.0, 0.817) - 0.878, 0.885, 2, 4 (physical) 1.25x HP
Planetar (CR 16.0, 0.809) - 0.874, 0.847, 0, 4 (physical) 1.25x HP
Nalfeshnee (CR 13.0, 0.785) - 0.979, 0.743, 1, 6 (physical) 1.25x HP
Marilith (CR 16.0, 0.778) - 0.826, 0.916, 1, 6 (physical) 1.25x HP
Iron Golem (CR 16.0, 0.662) - 1.101, 0.598, 3, 0 () 1.5x HP
Ultroloth (CR 13.0, 0.500) - 0.814, 0.635, 2, 6 (physical) 1.25x HP


CR 5-10:
Werebear (CR 5.0, 1.752) - 2.700, 0.693, 3, 0 (physical) 2x HP
Water Elemental (CR 5.0, 1.581) - 1.710, 0.924, 1, 4 (physical) 1.5x HP
Earth Elemental (CR 5.0, 1.574) - 1.890, 0.747, 1, 3 (physical) 1.5x HP
Salamander (CR 5.0, 1.551) - 1.350, 1.107, 1, 3 (physical) 1.5x HP
Fire Elemental (CR 5.0, 1.501) - 1.530, 0.973, 2, 3 (physical) 1.5x HP
Glabrezu (CR 9.0, 1.258) - 1.407, 0.760, 1, 6 (physical) 1.5x HP
Flesh Golem (CR 5.0, 1.240) - 1.870, 0.693, 5, 0 (no) 2x HP
Chain Devil (CR 8.0, 1.231) - 0.844, 1.297, 2, 4 (physical) 1.5x HP
Air Elemental (CR 5.0, 1.209) - 1.350, 0.836, 1, 5 (physical) 1.5x HP
Mezzoloth (CR 5.0, 1.176) - 1.125, 0.871, 2, 6 (physical) 1.5x HP
Barbed Devil (CR 5.0, 1.135) - 1.658, 0.587, 2, 4 (physical) 
Cambion (CR 5.0, 0.971) - 1.238, 0.640, 0, 7 (physical) 
Vampire Spawn (CR 5.0, 0.943) - 1.845, 0.502, 0, 4 (physical) 
Nycaloth (CR 9.0, 0.888) - 1.103, 0.727, 2, 6 (physical) 
Deva (CR 10.0, 0.873) - 1.106, 0.752, 0, 4 (physical) 
Galeb Duhr (CR 6.0, 0.803) - 1.097, 0.713, 1, 3 (physical) 
Clay Golem (CR 9.0, 0.796) - 1.583, 0.529, 6, 0
Grick Alpha (CR 7.0, 0.792) - 0.840, 0.939, 0, 3 (physical) 
Invisible Stalker (CR 6.0, 0.767) - 1.333, 0.460, 1, 0 (physical) 1.5x HP
Vrock (CR 6.0, 0.753) - 1.340, 0.552, 1, 6 (physical) 
Night Hag (CR 5.0, 0.717) - 1.688, 0.347, 0, 5 (physical) 
Yochlol (CR 10.0, 0.673) - 0.921, 0.797, 1, 6 (physical) 
Wraith (CR 5.0, 0.531) - 1.013, 0.560, 2, 8 (physical) 


Blue Slaad (CR 7.0, 1.351) - 1.719, 0.735, 0, 5 (no) 1.5x HP
Green Slaad (CR 8.0, 1.183) - 1.304, 0.917, 0, 5 (no) 1.5x HP
Death Slaad (CR 10.0, 1.170) - 1.355, 0.820, 0, 5 (no) 1.5x HP
Red Slaad (CR 5.0, 1.121) - 1.853, 0.587, 0, 5 (no) 1.5x HP
Gray Slaad (CR 9.0, 1.088) - 1.407, 0.760, 0, 5 (no) 1.5x HP
Xorn (CR 5.0, 0.994) - 1.103, 0.827, 0, 2 (piercing, slashing) 1.5x HP
Chasme (CR 6.0, 0.955) - 1.084, 0.920, 1, 3 (no) 1.5x HP
Treant (CR 9.0, 0.925) - 1.232, 0.727, 0, 2 (bludgeoning, piercing) 1.5x HP
Barlgura (CR 5.0, 0.835) - 1.020, 0.773, 1, 3 (no) 1.5x HP


CR 1-4:
Scarecrow (CR 1.0, 1.495) - 2.250, 0.828, 1, 3 (physical) 
Swarm of Poisonous Snakes (CR 2.0, 1.457) - 1.469, 0.992, 0, 3 (physical) 
Weretiger (CR 4.0, 1.406) - 2.892, 0.566, 3, 0
Fire Snake (CR 1.0, 1.284) - 1.406, 1.034, 1, 3 (physical) 
Bearded Devil (CR 3.0, 1.272) - 1.576, 0.745, 2, 4 (physical) 
Mummy (CR 3.0, 1.228) - 1.773, 0.784, 2, 3 (physical) 
Wereboar (CR 4.0, 1.180) - 2.048, 0.709, 3, 0
Succubus (CR 4.0, 1.127) - 1.590, 0.677, 0, 7 (physical) 
Shadow Demon (CR 4.0, 1.107) - 1.590, 0.540, 3, 7 (physical) 
Flameskull (CR 4.0, 1.103) - 0.976, 1.037, 3, 3 (physical) 
Couatl (CR 4.0, 1.100) - 2.937, 0.317, 4, 1
Banshee (CR 4.0, 0.957) - 1.763, 0.688, 3, 7 (physical) 
Ghost (CR 4.0, 0.945) - 2.169, 0.540, 3, 7 (physical) 
Helmed Horror (CR 4.0, 0.891) - 1.446, 0.508, 3, 3 (physical) 
Specter (CR 1.0, 0.884) - 1.406, 0.724, 2, 8 (physical) 
Water Weird (CR 3.0, 0.859) - 1.773, 0.510, 1, 4 (physical) 
Werewolf (CR 3.0, 0.773) - 1.773, 0.510, 3, 0
Imp (CR 1.0, 0.755) - 0.656, 1.034, 2, 4 (physical) 
Wight (CR 3.0, 0.751) - 1.364, 0.588, 1, 4 (physical) 
Wererat (CR 2.0, 0.583) - 1.347, 0.500, 3, 0
Quasit (CR 1.0, 0.297) - 0.469, 0.621, 1, 6 (physical) 


Incubus (CR 4.0, 1.127) - 1.590, 0.677, 0, 4 (no) 2x HP

# 2024 MM
Animal Lord (Forager) (CR 20.0, 2.677) - 1.948, 1.378, 0, 5 (no) 1x HP
Animal Lord (Hunter) (CR 20.0, 1.936) - 1.225, 1.378, 0, 5 (no) 1x HP
Mummy Lord (CR 15.0, 1.846) - 1.444, 1.325, 2, 0 (no) 1x HP
Sphinx of Valor (CR 17.0, 1.838) - 1.219, 1.483, 1, 2 (no) 1x HP
Animal Lord (Sage) (CR 20.0, 1.785) - 1.225, 1.378, 0, 5 (no) 1x HP
Lich (CR 21.0, 1.688) - 1.194, 1.568, 2, 2 (no) 1x HP
Arch-hag (CR 21.0, 1.671) - 1.240, 1.322, 0, 3 (no) 1x HP
Death Knight (CR 17.0, 1.606) - 0.955, 1.628, 2, 0 (no) 1x HP
Dracolich (CR 17.0, 1.547) - 1.040, 1.375, 2, 0 (no) 1x HP
Vampire Umbral Lord (CR 15.0, 1.504) - 1.186, 1.351, 2, 0 (no) 1x HP
Elemental Cataclysm (CR 22.0, 1.474) - 1.360, 1.054, 6, 0 (no) 1.25x HP
Demilich (CR 18.0, 1.465) - 1.055, 1.504, 3, 3 (physical) 1.25x HP
Pit Fiend (CR 20.0, 1.461) - 1.266, 1.094, 2, 1 (no) 1x HP
Solar (CR 21.0, 1.454) - 1.246, 1.092, 2, 0 (no) 1x HP
Empyrean (CR 23.0, 1.442) - 0.935, 1.429, 2, 3 (physical) 1x HP
Blob of Annihilation (CR 23.0, 1.417) - 1.424, 1.053, 3, 3 (physical) 1.25x HP
Tarrasque (CR 30.0, 1.384) - 1.047, 1.311, 2, 3 (no) 1x HP
Balor (CR 19.0, 1.336) - 1.120, 1.122, 2, 2 (no) 1x HP


CR 11-16:
Sphinx of Lore (CR 11.0, 1.990) - 1.443, 1.483, 1, 2 (no) 1x HP
* Arcanaloth (CR 12.0, 1.737) - 1.414, 1.173, 2, 3 (no) 1.25x HP
* Nalfeshnee (CR 13.0, 1.734) - 0.979, 1.641, 1, 3 (no) 1.25x HP
* Ultroloth (CR 13.0, 1.516) - 1.646, 0.850, 2, 3 (no) 1.25x HP

Ice Devil (CR 14.0, 1.275) - 1.357, 0.911, 3, 0 (no) 1.5x HP
Iron Golem (CR 16.0, 0.987) - 1.322, 0.768, 3, 0 (no) 1.5x HP

CR 5-10:
* Vrock (CR 6.0, 1.871) - 1.949, 0.943, 1, 3 (no) 1.5x HP
* Hezrou (CR 8.0, 1.489) - 1.565, 0.853, 1, 3 (no) 1.5x HP
* Death Slaad (CR 10.0, 1.475) - 2.034, 0.662, 0, 5 (no) 1.5x HP
* Mezzoloth (CR 5.0, 1.464) - 1.125, 1.076, 2, 3 (no) 1.5x HP
Fire Elemental (CR 5.0, 1.405) - 1.403, 1.107, 2, 3 (physical) 1.5x HP
* Green Slaad (CR 8.0, 1.385) - 2.080, 0.654, 0, 5 (no) 1.5 HP
* Yochlol (CR 10.0, 1.301) - 1.720, 0.752, 1, 3 (no) 1.5x HP
* Red Slaad (CR 5.0, 1.273) - 1.544, 0.800, 0, 5 (no) 1.5x HP
Revenant (CR 5.0, 1.251) - 1.890, 0.587, 1, 2 (no) 1.0 HP
* Chasme (CR 6.0, 1.141) - 1.400, 0.851, 1, 3 (no) 1.5x HP

Air Elemental (CR 5.0, 1.080) - 1.350, 0.747, 2, 4 (physical) 1.5x HP
Gray Slaad (CR 9.0, 0.970) - 1.286, 0.678, 0, 5 (no) 1.0x HP
* Clay Golem (CR 9.0, 0.703) - 1.103, 0.656, 3, 3 (physical) 1.5x HP --> 2x HP
Chain Devil (CR 8.0, 0.566) - 0.844, 0.569, 2, 4 (physical) 1.5x HP
Wraith (CR 5.0, 0.531) - 1.013, 0.560, 2, 6 (physical) 1.5x HP


CR 1-4:
* Incubus (CR 4.0, 1.954) - 1.590, 1.175, 0, 4 (no) 2x HP
* Succubus (CR 4.0, 1.888) - 2.067, 0.873, 0, 4 (no) 2x HP
? Awakened Tree (CR 2.0, 1.592) - 2.429, 0.650, 0, 2 (bludgeoning, piercing, fire vulnerable) 2x HP
Black Pudding (CR 4.0, 1.502) - 1.639, 1.402, 4, 0 (slashing) 2x HP
Ghost (CR 4.0, 1.446) - 1.446, 1.238, 2, 8 (physical) 2x HP
Swarm of Venomous Snakes (CR 2.0, 1.322) - 1.469, 0.900, 0, 3 (physical) 2x HP
? Imp (CR 1.0, 1.287) - 1.312, 0.931, 2, 1 (no) 2x HP
Swarm of Stirges (CR 2.0, 1.257) - 1.469, 0.912, 0, 3 (physical) 2x HP
Empyrean Iota (CR 1.0, 1.212) - 1.906, 0.517, 0, 3 (physical) 2x HP
Flameskull (CR 4.0, 1.209) - 0.976, 1.164, 3, 0 (no) 2x HP


Shadow Demon (CR 4.0, 1.096) - 1.590, 0.524, 2, 8 (physical) 2x HP
Will-o’-Wisp (CR 2.0, 0.956) - 1.122, 0.550, 2, 7 (physical) 2x HP
Banshee (CR 4.0, 0.946) - 1.301, 0.847, 3, 7 (physical) 2x HP
Swarm of Piranhas (CR 1.0, 0.903) - 1.750, 0.466, 0, 3 (physical) 2x HP
Poltergeist (CR 2.0, 0.877) - 0.918, 0.800, 2, 8 (physical) 2x HP
Swarm of Crawling Claws (CR 3.0, 0.801) - 1.500, 0.647, 2, 3 (physical) 2x HP
? Sphinx of Wonder (CR 1.0, 0.778) - 1.531, 0.483, 0, 3 (no) 2x HP
Couatl (CR 4.0, 0.747) - 1.446, 0.365, 2, 3 (physical) 2x HP
Swarm of Larvae (CR 1.0, 0.703) - 1.406, 0.552, 0, 3 (physical) 2x HP
Swarm of Dretches (CR 4.0, 0.608) - 1.084, 0.698, 1, 6 (physical) 2x HP
Specter (CR 1.0, 0.589) - 1.406, 0.483, 2, 8 (physical) 2x HP
? Quasit (CR 1.0, 0.587) - 1.562, 0.379, 1, 3 (no) 2x HP
Swarm of Lemures (CR 3.0, 0.431) - 1.364, 0.392, 2, 4 (physical) 2x HP






CR 0-1/2:
* Slaad Tadpole (CR 0.125, 1.589) - 1.579, 1.100, 0, 5 (no) 2x HP
* Manes (CR 0.125, 1.246) - 1.895, 1.000, 1, 3 (no) 2x HP
* Shadow (CR 0.5, 1.188) - 1.638, 0.524, 2, 5 (no) 1.25x HP
* Dretch (CR 0.25, 1.064) - 2.400, 0.562, 1, 3 (no) 2x HP

Swarm of Ravens (CR 0.25, 0.656) - 1.467, 0.500, 0, 3 (physical) 2x HP
Swarm of Insects (CR 0.5, 0.631) - 1.857, 0.452, 0, 3 (physical) 2x HP
Swarm of Rats (CR 0.25, 0.602) - 1.867, 0.469, 0, 3 (physical) 2x HP
Swarm of Bats (CR 0.25, 0.600) - 1.467, 0.469, 0, 3 (physical) 2x HP

In [312]:
groups = [
    {
        'name': 'MM 2014 - normal',
        'Book': 'MM (2014)',
        'Legendary': ['N'],
        'CR_range': [1,30],
        'color': COLORS[0], 
        'line_color': COLORS[0], 
        'symbol': 'circle',
    },
    {
        'name': 'MM 2024 - normal',
        'Book': 'MM (2024)',
        'Legendary': ['N'],
        'CR_range': [1,30],
        'color': COLORS[1],
        'line_color': COLORS[1],
        'symbol': 'circle',
    },
]

# create figure
fig = go.Figure(
    layout=go.Layout(
        template=tfb.FIG_TEMPLATE,
        margin=dict(l=70, r=25, b=55, t=20, pad=4),
        xaxis=dict(
            title_text='DPR Ratio',
            #type='log',
            #autorange=True,
            #tickmode='auto',
            #minor_tickmode='auto',
            range=[0,3.0],
            tick0=0, dtick=0.5,
            minor=dict(tick0=0, dtick=0.1),
            tickformat='.1f',
        ),
        yaxis=dict(
            title_text=f'HP Ratio',
            #type='log',
            #autorange=True,
            #tickmode='auto',
            #minor_tickmode='auto',
            range=[0,3.0],
            tick0=0, dtick=0.5,
            minor=dict(tick0=0, dtick=0.1),
            tickformat='.1f',
        ),
        legend=dict(
            xanchor='right', yanchor='top',
            x=1.00, y=1.00,
            orientation='v',
            tracegroupgap=0,
        )
    )
)

# plot monster data
for group in groups:
    name = group['name']
    book = group['Book']
    df1 = df0[df0['Book'].isin([book]) 
              & df0['Legendary'].isin(group['Legendary'])
              & df0['CR'].between(*group['CR_range'])]
    fig.add_trace(go.Scatter(
        x=df1['DPR Ratio'], 
        y=df1['HP Ratio'],
        mode='markers',
        marker_size=4,
        marker_symbol=group['symbol'],
        marker_color=group['color'],
        marker_line_color=group['line_color'],
        marker_line_width=0,
        name=name,
        customdata=np.stack((df1['Monster'], df1['CR']), axis=-1),
        hovertemplate = '<b>%{customdata[0]}' + f' - {name}</b><br>'
            + 'CR %{customdata[1]}<br>'
            + 'eDPR Ratio %{x:.3f}<br>'
            + 'eHP Ratio %{y:.3f}'
            + '<extra></extra>'
    ))

    slope, intercept, r_value, p_value, std_err = scipy.stats.linregress(1/df1['eDPR Ratio'], df1['eHP Ratio'])
    print(f'{name} fit: XP ratio = {intercept + slope:.3f}; r-squared = {r_value**2:.3f}; p-value = {p_value:.3e}')


x = np.linspace(0.2, 3.0, 100)
fig.add_trace(go.Scatter(
    x=x, 
    y=1/x,
    mode='lines', 
    name=f'baseline',
    showlegend=False,
    line_color='black',
    line_dash='dash',
    hoverinfo='skip',
))

"""x = np.linspace(0.2, 3.0, 100)
fig.add_trace(go.Scatter(
    x=x, 
    y=1.6/x,
    mode='lines', 
    name=f'baseline x1.6',
    showlegend=False,
    line_color='black',
    line_dash='dash',
    hoverinfo='skip',
))"""

# show figure
fig.update_layout(width=600, height=450)
fig.show(config=tfb.FIG_CONFIG)

# save figures
if SAVEFIGS:
    #fig.update_layout(autosize=True, width=None, height=None)
    #tfb.save_fig_html(fig, format='large', name=f'./fig-xp-ratio-vs-cr-large')
    #tfb.save_fig_html(fig, format='small', name=f'./fig-xp-ratio-vs-cr-small')
    pass

MM 2014 - normal fit: XP ratio = 1.061; r-squared = 0.003; p-value = 3.729e-01
MM 2024 - normal fit: XP ratio = 1.033; r-squared = 0.227; p-value = 8.625e-20

In [ ]:
groups = [
    {
        'name': 'MM 2014',
        'Book': 'MM (2014)',
        'Legendary': ['N'],
        'color': COLORS[0],
        'line_color': COLORS[0],
        'symbol': 'circle',
    },
    {
        'name': 'MM 2024',
        'Book': 'MM (2024)',
        'Legendary': ['N'],
        'color': COLORS[1],
        'line_color': COLORS[1],
        'symbol': 'circle',
    },
]

# create figure
fig = go.Figure(
    layout=go.Layout(
        template=tfb.FIG_TEMPLATE,
        margin=dict(l=70, r=25, b=55, t=20, pad=4),
        barmode='relative',
        xaxis=dict(
            title_text='CR delta',
            range=[-6,6],
        ),
        yaxis=dict(
            title_text='percent of monsters',
            autorange=True,
            #range=[0,100],
            tick0=0, dtick=0.1,
            minor=dict(tick0=0, dtick=0.05),
            tickformat='.0%',
        ),
        legend=dict(
            xanchor='left', yanchor='top',
            x=0.00, y=1.00,
            orientation='v',
            tracegroupgap=0,
            traceorder='normal',
        )
    )
)

for group in groups:
    name = group['name']
    book = group['Book']
    dtG = df0[df0['Legendary'].isin(group['Legendary'])].groupby(['Book','eCR Delta'], observed=False).count()['Monster']
    x_vals = list(dtG[book].keys())
    y_vals = list(dtG[book].values/sum(dtG[book].values))
    vals = {x: y for x, y in zip(x_vals, y_vals)}
    x_vals = np.linspace(min(x_vals)-1, max(x_vals) + 1, int(max(x_vals) - min(x_vals) + 3))
    y_vals = [vals.get(x, 0) for x in x_vals]
    fig.add_trace(go.Scatter(
        x=x_vals,
        y=y_vals,
        name=name,
        line_shape='hvh',
        fill='tozeroy',
        hoveron='points',
        hovertemplate = f'<b>{name}</b><br>'
            + 'CR delta %{x:.0f}<br>'
            + 'Monsters %{y:.1%}'
            + '<extra></extra>'
    ))

# show figure
fig.update_layout(width=600, height=450)
fig.show(config=tfb.FIG_CONFIG)

# save figures
if SAVEFIGS:
    #fig.update_layout(autosize=True, width=None, height=None)
    #tfb.save_fig_html(fig, format='large', name=f'./fig-sp-delta-by-ability-large')
    #tfb.save_fig_html(fig, format='small', name=f'./fig-sp-delta-by-ability-small')
    pass

In [ ]:
groups = [
    {
        'name': 'MM 2014',
        'Book': 'MM (2014)',
        'Legendary': ['L','LL'],
        'color': COLORS[0],
        'line_color': COLORS[0],
        'symbol': 'circle',
    },
    {
        'name': 'MM 2024',
        'Book': 'MM (2024)',
        'Legendary': ['L','L'],
        'color': COLORS[1],
        'line_color': COLORS[1],
        'symbol': 'circle',
    },
]

# create figure
fig = go.Figure(
    layout=go.Layout(
        template=tfb.FIG_TEMPLATE,
        margin=dict(l=70, r=25, b=55, t=20, pad=4),
        barmode='relative',
        xaxis=dict(
            title_text='CR delta',
            range=[-6,6],
        ),
        yaxis=dict(
            title_text='percent of monsters',
            autorange=True,
            #range=[0,100],
            tick0=0, dtick=0.1,
            minor=dict(tick0=0, dtick=0.05),
            tickformat='.0%',
        ),
        legend=dict(
            xanchor='left', yanchor='top',
            x=0.00, y=1.00,
            orientation='v',
            tracegroupgap=0,
            traceorder='normal',
        )
    )
)

for group in groups:
    name = group['name']
    book = group['Book']
    dtG = df0[df0['Legendary'].isin(group['Legendary'])].groupby(['Book','eCR Delta'], observed=False).count()['Monster']
    x_vals = list(dtG[book].keys())
    y_vals = list(dtG[book].values/sum(dtG[book].values))
    vals = {x: y for x, y in zip(x_vals, y_vals)}
    x_vals = np.linspace(min(x_vals)-1, max(x_vals) + 1, int(max(x_vals) - min(x_vals) + 3))
    y_vals = [vals.get(x, 0) for x in x_vals]
    fig.add_trace(go.Scatter(
        x=x_vals,
        y=y_vals,
        name=name,
        line_shape='hvh',
        fill='tozeroy',
        hoveron='points',
        hovertemplate = f'<b>{name}</b><br>'
            + 'CR delta %{x:.0f}<br>'
            + 'Monsters %{y:.1%}'
            + '<extra></extra>'
    ))

# show figure
fig.update_layout(width=600, height=450)
fig.show(config=tfb.FIG_CONFIG)

# save figures
if SAVEFIGS:
    #fig.update_layout(autosize=True, width=None, height=None)
    #tfb.save_fig_html(fig, format='large', name=f'./fig-sp-delta-by-ability-large')
    #tfb.save_fig_html(fig, format='small', name=f'./fig-sp-delta-by-ability-small')
    pass

In [ ]:
# plot the number of monsters by the type of change
import math

# create figure
fig = go.Figure(
    layout=go.Layout(
        template=tfb.FIG_TEMPLATE,
        margin=dict(l=70, r=25, b=55, t=20, pad=4),
        barmode='relative',
        #xaxis=dict(title_text='change'),
        yaxis=dict(
            title_text='monsters changed (%)',
            #range=[0,100],
            tick0=0, dtick=10,
            minor=dict(tick0=0, dtick=2),
        ),
        legend=dict(
            xanchor='left', yanchor='top',
            x=0.00, y=1.00,
            orientation='v',
            tracegroupgap=0,
            traceorder='normal',
        )
    )
)

stats = ['HP','AC','SB','DPR','AB','DC']

df1 = df0[df0['Book'].isin(['MM (2014)','MM (2024)']) & df0['Legendary'].isin(['N','L','LL'])]
dfMP = pd.pivot_table(df1, 
    values=['eXP'] + stats, 
    index=['Monster', 'CR'], columns=['Book']).reset_index()
dfMP = dfMP[dfMP['eXP']['MM (2014)'].isna() == False]
dfMP = dfMP[dfMP['eXP']['MM (2024)'].isna() == False]
m_count = dfMP.shape[0]

data = {}
for stat in stats:
    monsters = dfMP['Monster'].to_list()
    vals_24 = dfMP[stat]['MM (2024)'].to_list()
    vals_14 = dfMP[stat]['MM (2014)'].to_list()
    delta = []
    for v2, v1, m in zip(vals_24, vals_14, monsters):
        if math.isnan(v2) and math.isnan(v1):
            delta.append(False)
        elif math.isnan(v2):
            delta.append(False)
            #print(m, v2, v1, delta[-1])
        elif math.isnan(v1):
            delta.append(True)
            #print(m, v2, v1, delta[-1])
        else:
            delta.append(v2 > v1)
    data[stat] = np.sum(delta)
    #data[stat] = np.sum((dfMP[stat]['MM (2024)'] - dfMP[stat]['MM (2014)']) > 0)

fig.add_trace(go.Bar(
    x=np.array(list(data.keys())),
    y=np.array(list(data.values()))*(100/m_count),
    name='higher',
    hovertemplate = ''
        + 'Raw %{y:,.1f}%'
        + '<extra></extra>'
))

data = {}
for stat in stats:
    monsters = dfMP['Monster'].to_list()
    vals_24 = dfMP[stat]['MM (2024)'].to_list()
    vals_14 = dfMP[stat]['MM (2014)'].to_list()
    delta = []
    for v2, v1, m in zip(vals_24, vals_14, monsters):
        if math.isnan(v2) and math.isnan(v1):
            delta.append(False)
        elif math.isnan(v2):
            delta.append(True)
        elif math.isnan(v1):
            delta.append(False)
        else:
            delta.append(v2 < v1)
        #print(v2, v1, delta[-1])
    data[stat] = np.sum(delta)
    #data[stat] = np.sum((dfMP[stat]['MM (2024)'] - dfMP[stat]['MM (2014)']) < 0)

fig.add_trace(go.Bar(
    x=np.array(list(data.keys())),
    y=np.array(list(data.values()))*(-100/m_count),
    name='lower',
    hovertemplate = ''
        + 'Raw %{y:,.1f}%'
        + '<extra></extra>'
))

# show figure
fig.update_layout(width=600, height=450, hovermode='x unified')
fig.show(config=tfb.FIG_CONFIG)

# save figures
if SAVEFIGS:
    fig.update_layout(autosize=True, width=None, height=None)
    #tfb.save_fig_html(fig, format='large', name=f'./fig-stat-changes-large')
    #tfb.save_fig_html(fig, format='small', name=f'./fig-stat-changes-small')

/var/folders/k4/phz5f3ss2_91t6j4s71jmp540000gn/T/ipykernel_25198/484191064.py:30: FutureWarning:

The default value of observed=False is deprecated and will change to observed=True in a future version of pandas. Specify observed=False to silence this warning and retain the current behavior

In [ ]:
# plot the number of monsters by the type of change
# create figure
fig = go.Figure(
    layout=go.Layout(
        template=tfb.FIG_TEMPLATE,
        margin=dict(l=70, r=25, b=55, t=20, pad=4),
        barmode='relative',
        #xaxis=dict(title_text='change'),
        yaxis=dict(
            title_text='monsters changed (%)',
            #range=[0,100],
            tick0=0, dtick=10,
            minor=dict(tick0=0, dtick=2),
        ),
        legend=dict(
            xanchor='left', yanchor='top',
            x=0.00, y=1.00,
            orientation='v',
            tracegroupgap=0,
            traceorder='normal',
        )
    )
)

stats = ['adj HP','adj AC','adj SB','adj DPR','adj AB','adj DC']

df1 = df0[df0['Book'].isin(['MM (2014)','MM (2024)']) & df0['Legendary'].isin(['N','L','LL'])]
dfMP = pd.pivot_table(df1, 
    values=['eXP'] + stats, 
    index=['Monster', 'CR'], columns=['Book']).reset_index()
dfMP = dfMP[dfMP['eXP']['MM (2014)'].isna() == False]
dfMP = dfMP[dfMP['eXP']['MM (2024)'].isna() == False]
m_count = dfMP.shape[0]
print(m_count)

data = {}
for stat in stats:
    data[stat] = np.sum((dfMP[stat]['MM (2024)'] - dfMP[stat]['MM (2014)']) > 0)

fig.add_trace(go.Bar(
    x=np.array(list(data.keys())),
    y=np.array(list(data.values()))*(100/m_count),
    name='higher',
    hovertemplate = ''
        + 'Raw %{y:,.1f}%'
        + '<extra></extra>'
))

data = {}
for stat in stats:
    data[stat] = np.sum((dfMP[stat]['MM (2024)'] - dfMP[stat]['MM (2014)']) < 0)

fig.add_trace(go.Bar(
    x=np.array(list(data.keys())),
    y=np.array(list(data.values()))*(-100/m_count),
    name='lower',
    hovertemplate = ''
        + 'Raw %{y:,.1f}%'
        + '<extra></extra>'
))

# show figure
fig.update_layout(width=600, height=450, hovermode='x unified')
fig.show(config=tfb.FIG_CONFIG)

# save figures
if SAVEFIGS:
    fig.update_layout(autosize=True, width=None, height=None)
    #tfb.save_fig_html(fig, format='large', name=f'./fig-stat-changes-large')
    #tfb.save_fig_html(fig, format='small', name=f'./fig-stat-changes-small')

263

/var/folders/k4/phz5f3ss2_91t6j4s71jmp540000gn/T/ipykernel_25198/1197957297.py:28: FutureWarning:

The default value of observed=False is deprecated and will change to observed=True in a future version of pandas. Specify observed=False to silence this warning and retain the current behavior

In [ ]:
# plot the number of monsters by the type of change
# create figure
fig = go.Figure(
    layout=go.Layout(
        template=tfb.FIG_TEMPLATE,
        margin=dict(l=70, r=55, b=85, t=20, pad=4),
        barmode='relative',
        #xaxis=dict(title_text='change'),
        yaxis=dict(
            title_text='monsters changed (%)',
            #range=[0,100],
            tick0=0, dtick=2,
            minor=dict(tick0=0, dtick=1),
        ),
        legend=dict(
            xanchor='left', yanchor='top',
            x=0.00, y=1.00,
            orientation='v',
            tracegroupgap=0,
            traceorder='normal',
        )
    )
)

df1 = df0[df0['Book'].isin(['MM (2014)','MM (2024)']) & df0['Legendary'].isin(['N','L','LL'])]
dfMP = pd.pivot_table(df1, 
    values=['HP'] + CONDITION_COLUMNS, 
    index=['Monster', 'CR'], columns=['Book']).reset_index()
dfMP = dfMP[dfMP['HP']['MM (2014)'].isna() == False]
dfMP = dfMP[dfMP['HP']['MM (2024)'].isna() == False]
m_count = dfMP.shape[0]
print(m_count)

stats = CONDITION_COLUMNS
data = {}
for stat in stats:
    data[stat] = np.sum((dfMP[stat]['MM (2024)'] - dfMP[stat]['MM (2014)']) > 0)

fig.add_trace(go.Bar(
    x=np.array(list(data.keys())),
    y=np.array(list(data.values()))*(100/m_count),
    name='higher',
    hovertemplate = ''
        + 'Raw %{y:,.1f}%'
        + '<extra></extra>'
))
print(data)

stats = CONDITION_COLUMNS
data = {}
for stat in stats:
    data[stat] = np.sum((dfMP[stat]['MM (2024)'] - dfMP[stat]['MM (2014)']) < 0)

fig.add_trace(go.Bar(
    x=np.array(list(data.keys())),
    y=np.array(list(data.values()))*(-100/m_count),
    name='lower',
    hovertemplate = ''
        + 'Raw %{y:,.1f}%'
        + '<extra></extra>'
))
print(data)

# show figure
fig.update_layout(width=600, height=450, hovermode='x unified')
fig.show(config=tfb.FIG_CONFIG)

# save figures
if SAVEFIGS:
    fig.update_layout(autosize=True, width=None, height=None)
    #tfb.save_fig_html(fig, format='large', name=f'./fig-stat-changes-large')
    #tfb.save_fig_html(fig, format='small', name=f'./fig-stat-changes-small')

/var/folders/k4/phz5f3ss2_91t6j4s71jmp540000gn/T/ipykernel_25198/2840225865.py:26: FutureWarning:

The default value of observed=False is deprecated and will change to observed=True in a future version of pandas. Specify observed=False to silence this warning and retain the current behavior

263
{'Blinded': 3, 'Charmed': 7, 'Deafened': 4, 'Exhaustion': 6, 'Frightened': 10, 'Grappled': 3, 'Incapacitated': 0, 'Invisible': 0, 'Paralyzed': 2, 'Petrified': 4, 'Poisoned': 2, 'Prone': 0, 'Restrained': 4, 'Stunned': 3, 'Unconscious': 4}
{'Blinded': 5, 'Charmed': 0, 'Deafened': 0, 'Exhaustion': 0, 'Frightened': 0, 'Grappled': 0, 'Incapacitated': 0, 'Invisible': 0, 'Paralyzed': 0, 'Petrified': 0, 'Poisoned': 0, 'Prone': 0, 'Restrained': 0, 'Stunned': 0, 'Unconscious': 0}

In [ ]:
def get_mitigation_type(val):
    if val == 0:
        mt = 'I'
    elif val == 2:
        mt = 'V'
    elif val == 1:
        mt = 'N'
    elif val == 0.5:
        mt = 'R'
    elif val < 0.5:
        mt = 'I-N'
    elif val < 1.0:
        mt = 'R-N'
    else:
        mt = '?'
    return mt

{
    'R-N -> R': 10,
    'R-N -> N': 43,
    'I-N -> R': 4,
    'I-N -> N': 11,
    'N -> R': 1,
    'N -> I': 0,
    'R -> N': 0,
    'R -> I': 0,
    'I -> N': 0,
    'I -> R': 0,
}


df1 = df0[df0['Book'].isin(['MM (2014)','MM (2024)']) & df0['Legendary'].isin(['N','L','LL'])]
dfMP = pd.pivot_table(df1, 
    values=['HP','adj HP'] + DAMAGE_COLUMNS, 
    index=['Monster', 'CR'], columns=['Book']).reset_index()
dfMP = dfMP[dfMP['HP']['MM (2014)'].isna() == False]
dfMP = dfMP[dfMP['HP']['MM (2024)'].isna() == False]

cm = 0
for dt in ['Bludgeoning','Slashing','Piercing']:
    cv = {}
    mt14 = dfMP.apply(lambda r: get_mitigation_type(r[dt]['MM (2014)']), axis=1).to_list()
    mt24 = dfMP.apply(lambda r: get_mitigation_type(r[dt]['MM (2024)']), axis=1).to_list()

    cmt = []
    for m1, m2 in zip(mt14, mt24):
        cv[f'{m1} -> {m2}'] = cv.get(f'{m1} -> {m2}', 0) + 1
        if f'{m1} -> {m2}' in ['N -> N','R -> R','I -> I','V -> V']:
            cmt.append(0)
        else:
            cmt.append(1)
    cm += np.array(cmt)

    print(dt)
    for k, v in cv.items():
        if k in ['N -> N','R -> R','I -> I','V -> V']: continue
        print(f'  {k}: {v}')

print(f'total monsters changed: {np.count_nonzero(cm)}/{len(cm)}')


monster = dfMP['Monster'].to_list()
cr = dfMP['CR'].to_list()
hp14 = dfMP['HP']['MM (2014)'].to_list()
hp24 = dfMP['HP']['MM (2024)'].to_list()
ahp14 = dfMP['adj HP']['MM (2014)'].to_list()
ahp24 = dfMP['adj HP']['MM (2024)'].to_list()
changed_monsters = {
    'CR': [],
    'Monster': [],
    'HP ratio': [],
    'adj HP ratio': [],
}
for i in range(len(cm)):
    if cm[i] > 0:
        changed_monsters['CR'].append(cr[i])
        changed_monsters['Monster'].append(monster[i])
        changed_monsters['HP ratio'].append(hp24[i]/hp14[i])
        changed_monsters['adj HP ratio'].append(ahp24[i]/ahp14[i])

dfCM = pd.DataFrame(changed_monsters)
print('average HP change:', np.mean(dfCM['HP ratio']))
print('average adj HP change:', np.mean(dfCM['adj HP ratio']))
#dfCM

/var/folders/k4/phz5f3ss2_91t6j4s71jmp540000gn/T/ipykernel_25198/1227488626.py:33: FutureWarning:

The default value of observed=False is deprecated and will change to observed=True in a future version of pandas. Specify observed=False to silence this warning and retain the current behavior

Bludgeoning
  R-N -> R: 10
  R-N -> N: 43
  I-N -> R: 4
  I-N -> N: 11
  N -> R: 1
Slashing
  R-N -> R: 10
  R-N -> N: 44
  I-N -> R: 4
  I-N -> N: 11
  N -> R: 1
Piercing
  R-N -> R: 10
  R-N -> N: 44
  I-N -> R: 4
  R -> N: 1
  I-N -> N: 10
  N -> R: 1
total monsters changed: 71/263
average HP change: 1.2847376010230849
average adj HP change: 1.1261230734377539

In [ ]:
# create figure
fig = go.Figure(
    layout=go.Layout(
        template=tfb.FIG_TEMPLATE,
        barmode='stack',
        yaxis=dict(
            title_text='monsters',
            range=[0,120],
            tick0=0, dtick=20,
            minor=dict(tick0=0, dtick=5),
        ),
        legend=dict(
            xanchor='left', yanchor='top',
            x=0.01, y=0.99,
            orientation='v',
            tracegroupgap=0,
            traceorder='normal',
        )
    )
)

def get_mitigation_type(val):
    if val == 0:
        mt = 'I'
    elif val == 2:
        mt = 'V'
    elif val == 1:
        mt = 'N'
    elif val == 0.5:
        mt = 'R'
    elif val < 0.5:
        mt = 'I-N'
    elif val < 1.0:
        mt = 'R-N'
    else:
        mt = '?'
    return mt

conv_types = {
    'R -> I': '#1f77b4',
    'R -> N': 0,
    'R-N -> R': 10,
    'R-N -> N': 43,
    'I -> R': 0,
    'I -> N': 0,
    'I-N -> R': 4,
    'I-N -> N': 11,
    'N -> I': 0,
    'N -> R': 1,
}


df1 = df0[df0['Book'].isin(['MM (2014)','MM (2024)']) & df0['Legendary'].isin(['N','L','LL'])]
dfMP = pd.pivot_table(df1, 
    values=['HP','adj HP'] + DAMAGE_COLUMNS, 
    index=['Monster', 'CR'], columns=['Book']).reset_index()
dfMP = dfMP[dfMP['HP']['MM (2014)'].isna() == False]
dfMP = dfMP[dfMP['HP']['MM (2024)'].isna() == False]

cv_dict = {}
columns = DAMAGE_COLUMNS[:3]
for dt in columns:
    cv = {}
    mt14 = dfMP.apply(lambda r: get_mitigation_type(r[dt]['MM (2014)']), axis=1).to_list()
    mt24 = dfMP.apply(lambda r: get_mitigation_type(r[dt]['MM (2024)']), axis=1).to_list()

    cv_dict[dt] = {}
    for m1, m2 in zip(mt14, mt24):
        ct = f'{m1} -> {m2}'
        cv_dict[dt][ct] = cv_dict[dt].get(ct, 0) + 1


for ct in conv_types:
    y = [cv_dict[column].get(ct, 0) for column in columns]
    if sum(y) == 0: continue
    #y = np.array(y)
    #text = [f'{ty} out of {tt}' for ty, tt in zip(y, t)]
    fig.add_trace(go.Bar(
        x=columns,
        y=y,
        name=ct,
        #text=text,
        textposition='none',
        #marker_color=color,
        #hovertemplate=
        #    '<b>' + name + ' to %{x}</b><br>'+
        #    '%{y:.1f}% (%{text})'+
        #    '<extra></extra>'
    ))

# show figure
fig.update_layout(width=600, height=450)
fig.show(config=tfb.FIG_CONFIG)

# save figures
if SAVEFIGS:
    #fig.update_layout(autosize=True, width=None, height=None)
    #tfb.save_fig_html(fig, format='large', name='fig-physical-modifier-types-by-damage-large')
    #tfb.save_fig_html(fig, format='small', name='fig-physical-modifier-types-by-damage-small', style='aspect-ratio: 600/500;')
    pass

/var/folders/k4/phz5f3ss2_91t6j4s71jmp540000gn/T/ipykernel_25198/1983577789.py:54: FutureWarning:

The default value of observed=False is deprecated and will change to observed=True in a future version of pandas. Specify observed=False to silence this warning and retain the current behavior

In [ ]:
# shows the change in damage mitigation from 2014 to 2024


def get_mitigation_type(val):
    if val == 0:
        mt = 'I'
    elif val == 2:
        mt = 'V'
    elif val == 1:
        mt = 'N'
    elif val == 0.5:
        mt = 'R'
    elif val < 0.5:
        mt = 'I-N'
    elif val < 1.0:
        mt = 'R-N'
    else:
        mt = '?'
    return mt

conv_types = {
    #'R -> I': {'offsetgroup': 'R', 'sign':  1, 'color': '#1f77b4'},
    'R -> N': {'offsetgroup': 'R', 'sign': -1, 'color': '#79CFFC'},
    #'R-N -> I': {'offsetgroup': 'R', 'sign':  1, 'color': '#1f77b4'},
    #'R-N -> R': {'offsetgroup': 'R', 'sign':  1, 'color': ''},
    'R-N -> N': {'offsetgroup': 'R', 'sign': -1, 'color': '#79CFFC'},
    #'I -> R': {'offsetgroup': 'I', 'sign': -1, 'color': '#ff7f0e'},
    'I -> N': {'offsetgroup': 'I', 'sign': -1, 'color': '#FDBD00'},
    #'I-N -> R': {'offsetgroup': 'I', 'sign': -1, 'color': '#ff7f0e'},
    'I-N -> N': {'offsetgroup': 'I', 'sign': -1, 'color': '#FDBD00'},
    'N -> I': {'offsetgroup': 'N', 'sign':  1, 'color': '#2ca02c'},
    'N -> R': {'offsetgroup': 'N', 'sign':  1, 'color': '#83d983'},
}

groups = [
    ('resistant', ['R','R-D','R-M'], '#1f77b4'),
    ('resistant (non-magical)', ['R-N','R-NA','R-ND','R-NS'], '#79CFFC'),
    ('immune', ['I','I-F'], '#ff7f0e'),
    ('immune (non-magical)', ['I-N','I-NA','I-NS'], '#FDBD00'),
    ('vulnerable', ['V'], '#2ca02c'),
]


df1 = df0[df0['Book'].isin(['MM (2014)','MM (2024)']) & df0['Legendary'].isin(['N','L','LL'])]
dfMP = pd.pivot_table(df1, 
    values=['HP','adj HP'] + DAMAGE_COLUMNS, 
    index=['Monster', 'CR'], columns=['Book']).reset_index()
dfMP = dfMP[dfMP['HP']['MM (2014)'].isna() == False]
dfMP = dfMP[dfMP['HP']['MM (2024)'].isna() == False]

cv_dict = {}
columns = DAMAGE_COLUMNS[0:]
for dt in columns:
    cv = {}
    mt14 = dfMP.apply(lambda r: get_mitigation_type(r[dt]['MM (2014)']), axis=1).to_list()
    mt24 = dfMP.apply(lambda r: get_mitigation_type(r[dt]['MM (2024)']), axis=1).to_list()

    cv_dict[dt] = {}
    for m1, m2 in zip(mt14, mt24):
        ct = f'{m1} -> {m2}'
        cv_dict[dt][ct] = cv_dict[dt].get(ct, 0) + 1

data = []
total = 0
for ct in conv_types:
    s = conv_types[ct]['sign']
    y = [s*cv_dict[column].get(ct, 0) for column in columns]
    color = conv_types[ct]['color']
    if sum(y) == 0: continue
    #y = np.array(y)
    #text = [f'{ty} out of {tt}' for ty, tt in zip(y, t)]
    total += sum(y)
    data.append(go.Bar(
        x=columns,
        y=y,
        name=ct,
        #text=text,
        #textposition='none',
        offsetgroup=conv_types[ct]['offsetgroup'],
        marker_color=color,
        hovertemplate=
            '<b>%{x}</b><br>'+
            ct+' %{y:.0f} monsters'+
            '<extra></extra>'
    ))
print(total)

# create figure
fig = go.Figure(
    layout=go.Layout(
        template=tfb.FIG_TEMPLATE,
        margin=dict(l=70, r=35, b=70, t=20, pad=4),
        barmode='relative',
        yaxis=dict(
            title_text='monsters',
            range=[-8,8],
            tick0=0, dtick=2,
            minor=dict(tick0=0, dtick=1),
            #autorange=True,
            #tickmode='auto',
            #minor_tickmode='auto',
        ),
        legend=dict(
            xanchor='right', yanchor='bottom',
            x=1.00, y=0.0,
            orientation='v',
            tracegroupgap=0,
            traceorder='normal',
        )
    ),
    data=data,
)

# show figure
fig.update_layout(width=600, height=450)
fig.show(config=tfb.FIG_CONFIG)

# save figures
if SAVEFIGS:
    #fig.update_layout(autosize=True, width=None, height=None)
    #tfb.save_fig_html(fig, format='large', name='fig-physical-modifier-types-by-damage-large')
    #tfb.save_fig_html(fig, format='small', name='fig-physical-modifier-types-by-damage-small', style='aspect-ratio: 600/500;')
    pass

/var/folders/k4/phz5f3ss2_91t6j4s71jmp540000gn/T/ipykernel_25198/1842762560.py:45: FutureWarning:

The default value of observed=False is deprecated and will change to observed=True in a future version of pandas. Specify observed=False to silence this warning and retain the current behavior

-159

In [172]:
def get_mitigation_type(val):
    if val == 0:
        mt = 'I'
    elif val == 2:
        mt = 'V'
    elif val == 1:
        mt = 'N'
    elif val == 0.5:
        mt = 'R'
    elif val < 0.5:
        mt = 'I-N'
    elif val < 1.0:
        mt = 'R-N'
    else:
        mt = '?'
    return mt

df1 = df0[df0['Book'].isin(['MM (2024)']) & df0['Legendary'].isin(['N','L','LL'])]

for dt in DAMAGE_COLUMNS:
    cv = {}
    mt = df1.apply(lambda r: get_mitigation_type(r[dt]), axis=1).to_list()

    for m in mt:
        cv[m] = cv.get(m, 0) + 1
    print(dt)
    for k, v in cv.items():
        print(f'  {k}: {v}')

Bludgeoning
  N: 375
  R: 28
  V: 2
Piercing
  N: 377
  R: 28
Slashing
  N: 377
  R: 26
  I: 2
Acid
  N: 365
  I: 22
  R: 18
Cold
  N: 316
  I: 27
  R: 59
  V: 3
Fire
  N: 308
  I: 48
  R: 43
  V: 6
Force
  N: 405
Lightning
  N: 349
  I: 24
  R: 32
Necrotic
  N: 351
  R: 24
  I: 30
Poison
  N: 294
  I: 107
  R: 4
Psychic
  N: 374
  R: 15
  I: 16
Radiant
  N: 387
  R: 14
  I: 3
  V: 1
Thunder
  N: 390
  I: 4
  R: 10
  V: 1

In [ ]:
# plot the number of monsters by the type of change
# create figure
fig = go.Figure(
    layout=go.Layout(
        template=tfb.FIG_TEMPLATE,
        margin=dict(l=70, r=35, b=75, t=20, pad=4),
        barmode='relative',
        #xaxis=dict(title_text='change'),
        yaxis=dict(
            title_text='monsters changed (%)',
            #range=[0,100],
            tick0=0, dtick=2,
            minor=dict(tick0=0, dtick=1),
        ),
        legend=dict(
            xanchor='right', yanchor='bottom',
            x=1.00, y=0.00,
            orientation='v',
            tracegroupgap=0,
            traceorder='normal',
        )
    )
)

df1 = df0[df0['Book'].isin(['MM (2014)','MM (2024)']) & df0['Legendary'].isin(['N','L','LL'])]
dfMP = pd.pivot_table(df1, 
    values=['HP'] + DAMAGE_COLUMNS, 
    index=['Monster', 'CR'], columns=['Book']).reset_index()
dfMP = dfMP[dfMP['HP']['MM (2014)'].isna() == False]
dfMP = dfMP[dfMP['HP']['MM (2024)'].isna() == False]
m_count = dfMP.shape[0]
print(m_count)

stats = DAMAGE_COLUMNS

data = {}
for stat in stats:
    data[stat] = np.sum((dfMP[stat]['MM (2024)'] - dfMP[stat]['MM (2014)']) < 0)

fig.add_trace(go.Bar(
    x=np.array(list(data.keys())),
    y=np.array(list(data.values()))*(100/m_count),
    name='higher',
    hovertemplate = ''
        + 'Raw %{y:,.1f}%'
        + '<extra></extra>'
))
print(data)

data = {}
for stat in stats:
    data[stat] = np.sum((dfMP[stat]['MM (2024)'] - dfMP[stat]['MM (2014)']) > 0)

fig.add_trace(go.Bar(
    x=np.array(list(data.keys())),
    y=np.array(list(data.values()))*(-100/m_count),
    name='lower',
    hovertemplate = ''
        + 'Raw %{y:,.1f}%'
        + '<extra></extra>'
))
print(data)

# show figure
fig.update_layout(width=600, height=450, hovermode='x unified')
fig.show(config=tfb.FIG_CONFIG)

# save figures
if SAVEFIGS:
    fig.update_layout(autosize=True, width=None, height=None)
    #tfb.save_fig_html(fig, format='large', name=f'./fig-stat-changes-large')
    #tfb.save_fig_html(fig, format='small', name=f'./fig-stat-changes-small')

263
{'Bludgeoning': 11, 'Piercing': 11, 'Slashing': 11, 'Acid': 2, 'Cold': 4, 'Fire': 1, 'Force': 0, 'Lightning': 0, 'Necrotic': 7, 'Poison': 1, 'Psychic': 5, 'Radiant': 5, 'Thunder': 1}
{'Bludgeoning': 58, 'Piercing': 59, 'Slashing': 59, 'Acid': 1, 'Cold': 4, 'Fire': 1, 'Force': 2, 'Lightning': 6, 'Necrotic': 2, 'Poison': 1, 'Psychic': 0, 'Radiant': 1, 'Thunder': 2}

/var/folders/k4/phz5f3ss2_91t6j4s71jmp540000gn/T/ipykernel_25198/1040065386.py:26: FutureWarning:

The default value of observed=False is deprecated and will change to observed=True in a future version of pandas. Specify observed=False to silence this warning and retain the current behavior

In [ ]:
# plot the number of monsters by the type of change
# create figure
fig = go.Figure(
    layout=go.Layout(
        template=tfb.FIG_TEMPLATE,
        margin=dict(l=70, r=25, b=55, t=20, pad=4),
        barmode='relative',
        #xaxis=dict(title_text='change'),
        yaxis=dict(
            title_text='monsters changed (%)',
            #range=[0,100],
            tick0=0, dtick=2,
            minor=dict(tick0=0, dtick=1),
        ),
        legend=dict(
            xanchor='left', yanchor='top',
            x=0.00, y=1.00,
            orientation='v',
            tracegroupgap=0,
            traceorder='normal',
        )
    )
)

df1 = df0[df0['Book'].isin(['MM (2014)','MM (2024)']) & df0['Legendary'].isin(['N','L','LL'])]
dfMP = pd.pivot_table(df1, 
    values=['HP'] + ABILITY_MOD_COLUMNS, 
    index=['Monster', 'CR'], columns=['Book']).reset_index()
dfMP = dfMP[dfMP['HP']['MM (2014)'].isna() == False]
dfMP = dfMP[dfMP['HP']['MM (2024)'].isna() == False]
m_count = dfMP.shape[0]
print(m_count)

stats = ABILITY_MOD_COLUMNS

data = {}
for stat in stats:
    data[stat] = np.sum((dfMP[stat]['MM (2024)'] - dfMP[stat]['MM (2014)']) > 0)

fig.add_trace(go.Bar(
    x=np.array(list(data.keys())),
    y=np.array(list(data.values()))*(100/m_count),
    name='higher',
    hovertemplate = ''
        + 'Raw %{y:,.1f}%'
        + '<extra></extra>'
))
print(data)

data = {}
for stat in stats:
    data[stat] = np.sum((dfMP[stat]['MM (2024)'] - dfMP[stat]['MM (2014)']) < 0)

fig.add_trace(go.Bar(
    x=np.array(list(data.keys())),
    y=np.array(list(data.values()))*(-100/m_count),
    name='lower',
    hovertemplate = ''
        + 'Raw %{y:,.1f}%'
        + '<extra></extra>'
))
print(data)

# show figure
fig.update_layout(width=600, height=450, hovermode='x unified')
fig.show(config=tfb.FIG_CONFIG)

# save figures
if SAVEFIGS:
    fig.update_layout(autosize=True, width=None, height=None)
    #tfb.save_fig_html(fig, format='large', name=f'./fig-stat-changes-large')
    #tfb.save_fig_html(fig, format='small', name=f'./fig-stat-changes-small')

263
{'Str Mod': 11, 'Dex Mod': 13, 'Con Mod': 3, 'Int Mod': 3, 'Wis Mod': 8, 'Cha Mod': 25}
{'Str Mod': 2, 'Dex Mod': 0, 'Con Mod': 2, 'Int Mod': 1, 'Wis Mod': 0, 'Cha Mod': 3}

/var/folders/k4/phz5f3ss2_91t6j4s71jmp540000gn/T/ipykernel_25198/393895027.py:26: FutureWarning:

The default value of observed=False is deprecated and will change to observed=True in a future version of pandas. Specify observed=False to silence this warning and retain the current behavior

In [ ]:
# plot the number of monsters by the type of change
# create figure
fig = go.Figure(
    layout=go.Layout(
        template=tfb.FIG_TEMPLATE,
        margin=dict(l=70, r=25, b=55, t=20, pad=4),
        barmode='relative',
        #xaxis=dict(title_text='change'),
        yaxis=dict(
            title_text='monsters changed (%)',
            #range=[0,100],
            tick0=0, dtick=2,
            minor=dict(tick0=0, dtick=1),
        ),
        legend=dict(
            xanchor='left', yanchor='top',
            x=0.00, y=1.00,
            orientation='v',
            tracegroupgap=0,
            traceorder='normal',
        )
    )
)

df1 = df0[df0['Book'].isin(['MM (2014)','MM (2024)']) & df0['Legendary'].isin(['N','L','LL'])]
dfMP = pd.pivot_table(df1, 
    values=['HP'] + SAVE_BONUS_COLUMNS, 
    index=['Monster', 'CR'], columns=['Book']).reset_index()
dfMP = dfMP[dfMP['HP']['MM (2014)'].isna() == False]
dfMP = dfMP[dfMP['HP']['MM (2024)'].isna() == False]
m_count = dfMP.shape[0]
print(m_count)

stats = SAVE_BONUS_COLUMNS

data = {}
for stat in stats:
    data[stat] = np.sum((dfMP[stat]['MM (2024)'] - dfMP[stat]['MM (2014)']) > 0)

fig.add_trace(go.Bar(
    x=np.array(list(data.keys())),
    y=np.array(list(data.values()))*(100/m_count),
    name='higher',
    hovertemplate = ''
        + 'Raw %{y:,.1f}%'
        + '<extra></extra>'
))
print(data)

data = {}
for stat in stats:
    data[stat] = np.sum((dfMP[stat]['MM (2024)'] - dfMP[stat]['MM (2014)']) < 0)

fig.add_trace(go.Bar(
    x=np.array(list(data.keys())),
    y=np.array(list(data.values()))*(-100/m_count),
    name='lower',
    hovertemplate = ''
        + 'Raw %{y:,.1f}%'
        + '<extra></extra>'
))
print(data)

# show figure
fig.update_layout(width=600, height=450, hovermode='x unified')
fig.show(config=tfb.FIG_CONFIG)

# save figures
if SAVEFIGS:
    fig.update_layout(autosize=True, width=None, height=None)
    #tfb.save_fig_html(fig, format='large', name=f'./fig-stat-changes-large')
    #tfb.save_fig_html(fig, format='small', name=f'./fig-stat-changes-small')

263
{'Str Save': 16, 'Dex Save': 20, 'Con Save': 10, 'Int Save': 3, 'Wis Save': 12, 'Cha Save': 8}
{'Str Save': 5, 'Dex Save': 1, 'Con Save': 46, 'Int Save': 12, 'Wis Save': 4, 'Cha Save': 62}

/var/folders/k4/phz5f3ss2_91t6j4s71jmp540000gn/T/ipykernel_25198/3606748560.py:26: FutureWarning:

The default value of observed=False is deprecated and will change to observed=True in a future version of pandas. Specify observed=False to silence this warning and retain the current behavior

In [176]:
column = 'Initiative'
groups = [
    {
        'name': 'MM 2024 - normal',
        'Book': 'MM (2024)',
        'Legendary': ['N'],
        'color': COLORS[1],
        'line_color': COLORS[1],
        'symbol': 'circle',
    },
]

# create figure
fig = go.Figure(
    layout=go.Layout(
        template=tfb.FIG_TEMPLATE,
        margin=dict(l=70, r=25, b=55, t=20, pad=4),
        xaxis=dict(
            title_text='size',
            autorange=True,
            #range=[0,31],
            #tick0=0, dtick=5,
            #minor=dict(tick0=0, dtick=1),
        ),
        yaxis=dict(
            title_text='initiative proficiency',
            autorange=True,
            #range=[0,3],
            #tick0=0, dtick=50,
            #minor=dict(tick0=0, dtick=10),
            tickformat='.1f',
        ),
        legend=dict(
            xanchor='right', yanchor='bottom',
            x=1.00, y=0.15,
            orientation='v',
            tracegroupgap=0,
        )
    )
)

# plot monster data
for group in groups:
    name = group['name']
    book = group['Book']
    legendary = group['Legendary']
    df1 = df0[df0['Book'].isin([book]) & df0['Legendary'].isin(legendary) & df0['CR'].between(0,30)]
    df1['Initiative ratio'] = (df1['Initiative'] - df1['Dex Mod'])/df1['PB']
    dfG = df1[['Size','Initiative ratio']].groupby(['Size'], observed=False).mean().reset_index()
    fig.add_trace(go.Scatter(
        x=dfG['Size'], 
        y=dfG['Initiative ratio'],
        mode='markers+lines', 
        name=name,
        marker_color=group['color'],
        marker_symbol=group['symbol'],
        line_color=group['line_color'],
        hovertemplate = f'<b>{name}</b><br>'
            + 'CR %{x:.0f}<br>'
            + 'Proficiency %{y:.2f}'
            + '<extra></extra>'
    ))

# show figure
fig.update_layout(width=600, height=450)
fig.show(config=tfb.FIG_CONFIG)

# save figures
if SAVEFIGS:
    fig.update_layout(autosize=True, width=None, height=None)
    #tfb.save_fig_html(fig, format='large', name=f'./fig-initiative-proficiency-vs-cr-large')
    #tfb.save_fig_html(fig, format='small', name=f'./fig-initiative-proficiency-vs-cr-small')

In [6]:
groups = [
    {
        'name': 'MM 2024 - normal dragons',
        'Book': 'MM (2024)',
        'Legendary': ['N'],
        'CR_range': [2,30],
        'types': ['Dragon'],
        'color': COLORS[0],
        'line_color': COLORS[0],
        'symbol': 'circle',
    },
    {
        'name': 'MM 2024 - legendary dragons',
        'Book': 'MM (2024)',
        'Legendary': ['L','LL'],
        'CR_range': [2,30],
        'types': ['Dragon'],
        'color': COLORS[1],
        'line_color': COLORS[1],
        'symbol': 'square',
    }
]

# create figure
fig = go.Figure()

# plot monster data
for group in groups:
    name = group['name']
    book = group['Book']
    df1 = df0[df0['Book'].isin([book]) 
              & df0['Legendary'].isin(group['Legendary'])
              & df0['CR'].between(*group['CR_range'])
              & df0['Type'].isin(group['types'])]
    fig.add_trace(go.Scatter(
        x=df1['adj DPR Ratio'], 
        y=df1['adj HP Ratio'],
        mode='markers',
        marker_size=6,
        marker_symbol=group['symbol'],
        marker_color=group['color'],
        marker_line_color=group['line_color'],
        marker_line_width=0,
        name=name,
        customdata=np.stack((df1['Monster'], df1['CR']), axis=-1),
        hovertemplate = '<b>%{customdata[0]}' + f' - {name}</b><br>'
            + 'CR %{customdata[1]}<br>'
            + 'eDPR Ratio %{x:.3f}<br>'
            + 'eHP Ratio %{y:.3f}'
            + '<extra></extra>'
    ))

    slope, intercept, r_value, p_value, std_err = scipy.stats.linregress(1/df1['eDPR Ratio'], df1['eHP Ratio'])
    print(f'{name} fit: XP ratio = {intercept + slope:.3f}; r-squared = {r_value**2:.3f}; p-value = {p_value:.3e}')


x = np.linspace(0.2, 3.0, 100)
fig.add_trace(go.Scatter(
    x=x, 
    y=1/x,
    mode='lines', 
    name=f'baseline',
    showlegend=False,
    line_color='black',
    line_dash='dash',
    hoverinfo='skip',
))

"""x = np.linspace(0.2, 3.0, 100)
fig.add_trace(go.Scatter(
    x=x, 
    y=1.6/x,
    mode='lines', 
    name=f'baseline x1.6',
    showlegend=False,
    line_color='black',
    line_dash='dash',
    hoverinfo='skip',
))"""

# show figure
fig.update_layout(
    template=tfb.FIG_TEMPLATE,
    margin=dict(l=70, r=25, b=55, t=20, pad=4),
    xaxis=dict(
        title_text='eDPR Ratio',
        tickmode='auto',
        range=[0.6,1.9],
        tickformat='.1f',
    ),
    yaxis=dict(
        title_text=f'eHP Ratio',
        tickmode='auto',
        range=[0.6,1.9],
        tickformat='.1f',
    ),
    legend=dict(
        xanchor='right', yanchor='top',
        x=1.00, y=1.00,
        orientation='v',
        tracegroupgap=0,
    ),
    width=600, 
    height=450,
)
fig.show(config=tfb.FIG_CONFIG)

# save figures
if SAVEFIGS:
    #fig.update_layout(autosize=True, width=None, height=None)
    #tfb.save_fig_html(fig, format='large', name=f'./fig-xp-ratio-vs-cr-large')
    #tfb.save_fig_html(fig, format='small', name=f'./fig-xp-ratio-vs-cr-small')
    pass

MM 2024 - normal dragons fit: XP ratio = 1.070; r-squared = 0.292; p-value = 7.770e-03
MM 2024 - legendary dragons fit: XP ratio = 1.458; r-squared = 0.153; p-value = 1.254e-02